- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleChangeling
  name: Changeling Role
  components:
  - type: MindRole
    antagPrototype: Changeling
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-changeling
  - type: ChangelingRole
