# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuitBlack
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSBlack

- type: loadout
  id: HeadofSecurityJumpskirtBlack
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSBlack

    #Shoulder Mantle
- type: loadout
  id: HeadofSecurityShoulderMantle
  equipment:
    neck: ClothingNeckMantleHOSShoulder
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS
