- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2h # Corvax-RoleTime
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen
  #ADT-Tweak-Start
  - !type:AddSpeciesComponentSpecial
    species: IPC
    components:
      - type: BorgChassis
        maxModules: 1
        moduleWhitelist:
          tags:
          - BorgModuleGeneric
          - BorgModuleMedical
        ipc: true
  #ADT-Tweak-End

- type: startingGear
  id: DoctorGear
  equipment:
    ears: ClothingHeadsetMedical
#    belt: ClothingBeltMedicalFilled ADT tweak
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: MedicalDoctorChameleonOutfit
  job: MedicalDoctor
  equipment:
    head: ClothingHeadNurseHat
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
