- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleGhoul
  name: Ghoul Role
#  description: mind-role-initial-infected-description
  components:
  - type: MindRole
    antagPrototype: Ghoul # ERROR!!
    exclusiveAntag: true
  - type: InitialInfectedRole
  - type: GhoulRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHeretic
  name: Heretic Role
#  description: mind-role-initial-infected-description
  components:
  - type: MindRole
    antagPrototype: Heretic
    exclusiveAntag: true
  - type: HereticRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleChangeling
  name: Changeling Role
  components:
  - type: MindRole
    antagPrototype: Changeling
    exclusiveAntag: true
  - type: ChangelingRole
