using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map.Components;
using Robust.Shared.Threading;

namespace Content.Client.Shuttles.UI;

/// <summary>
/// Provides common functionality for radar-like displays on shuttle consoles.
/// </summary>
[GenerateTypedNameReferences]
[Virtual]
public partial class BaseShuttleControl : MapGridControl
{
    [Dependency] private readonly IParallelManager _parallel = default!;

    protected readonly SharedMapSystem Maps;
    protected readonly Font Font;
    protected readonly GridRadarRenderer GridRenderer;

    public BaseShuttleControl() : this(32f, 32f, 32f)
    {
    }

    public BaseShuttleControl(float minRange, float maxRange, float range)
        : base(minRange, maxRange, range)
    {
        RobustXamlLoader.Load(this);
        Maps = EntManager.System<SharedMapSystem>();
        Font = new VectorFont(
            IoCManager.Resolve<IResourceCache>()
                .GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Regular.ttf"),
            12);
        GridRenderer = new GridRadarRenderer(Maps, _parallel);
    }

    protected void DrawData(DrawingHandleScreen handle, string text)
    {
        var dimensions = handle.GetDimensions(Font, text, 1f);
        const float margin = 5f;
        handle.DrawString(
            Font,
            new Vector2(margin, PixelHeight) - new Vector2(0f, dimensions.Y + margin),
            text,
            Color.FromSrgb(IFFComponent.SelfColor));
    }

    protected void DrawCircles(DrawingHandleScreen handle)
    {
        const float multiplier = 2f;
        var minDistance = MathF.Pow(multiplier, multiplier * 1.5f);
        var maxDistance = MathF.Pow(2f, multiplier * 6f);
        var cornerDistance = MathF.Sqrt(WorldRange * WorldRange * 2f);
        var origin = ScalePosition(-new Vector2(Offset.X, -Offset.Y));

        for (var radius = minDistance; radius <= maxDistance; radius *= multiplier)
        {
            if (radius > cornerDistance)
                continue;

            var color = Color.LightGray.WithAlpha(0.05f);
            var text = $"{radius:0}m";
            var dimensions = handle.GetDimensions(Font, text, UIScale);
            handle.DrawCircle(origin, MinimapScale * radius, color, false);
            handle.DrawString(
                Font,
                ScalePosition(new Vector2(0f, -radius)) - new Vector2(0f, dimensions.Y),
                text,
                UIScale,
                color);
        }

        const int radialLines = 8;
        for (var i = 0; i < radialLines; i++)
        {
            Angle angle = Math.PI / radialLines * i;
            var extent = angle.ToVec() * ScaledMinimapRadius * 1.42f;
            handle.DrawLine(
                origin - extent,
                origin + extent,
                Color.MediumSpringGreen.WithAlpha(0.02f));
        }
    }

    protected void DrawGrid(
        DrawingHandleScreen handle,
        Matrix3x2 gridToView,
        Entity<MapGridComponent> grid,
        Color color,
        float alpha = 0.01f)
    {
        GridRenderer.DrawGrid(handle, gridToView, grid, color, alpha);
    }
}
