- type: entity
  id: ADTIndustrialSMESMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Industrial SMES machine board
  description: A machine printed circuit board for a SMES.
  components:
    - type: MachineBoard
      prototype: ADTIndustrialSMESEmpty
      stackRequirements:
        Capacitor: 4
        CableHV: 30
      componentRequirements:
        PowerCell:
          amount: 16
          defaultPrototype: PowerCellSmall

- type: entity
  id: ADTUniversalPipeDispenserCircuitboard
  parent: BaseMachineCircuitboard
  name: universal pipe dispenser board
  description: A machine circuit board for a universal pipe dispenser. Exists in a single copy.
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: ADTUniversalPipeDispenser
      stackRequirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker

# Оригинал данного прототипа был сделан @temporaldarkness (discord). Прототип был взят с https://github.com/ss14-ganimed/ENT14-Master.
# Ganimed-Book-Printer-Start
- type: entity
  id: ADTBookPrinterMachineCircuitboard
  categories: [ HideSpawnMenu ]
  parent: BaseMachineCircuitboard
  name: book printer machine board
  components:
  - type: MachineBoard
    prototype: ADTBookPrinter
    stackRequirements:
      Capacitor: 2
      Manipulator: 2
      MatterBin: 2
# Ganimed-Book-Printer-End

- type: entity
  id: ADTBarmenKettleCircuit
  parent: BaseMachineCircuitboard
  name: kettle machine board
  description: A machine printed circuit board for a kettle.
  components:
    - type: MachineBoard
      prototype: ADTBarmenKettle
      stackRequirements:
        Capacitor: 2
        Glass: 1

#Taken from [2670] Pull Request DeltaV
- type: entity
  id: ADTAdvancedMicrowaveMachineCircuitBoard
  parent: MicrowaveMachineCircuitboard
  name: adt-advanced-microwave-machineboard
  components:
  - type: MachineBoard
    prototype: ADTAdvancedMicrowave
    stackRequirements:
      Capacitor: 4
      Glass: 4
      Cable: 5
    tagRequirements:
      GlassBeaker:
        amount: 1
        defaultPrototype: Beaker
#End of DeltaV

# Taken from Frontier Station
- type: entity
  id: ADTMedicalAssemblerMachineCircuitBoard
  parent: BaseMachineCircuitboard
  name: medical assembler machine board
  description: A machine printed circuit board for a medical assembler.
  components:
    - type: Sprite
      state: medical
    - type: MachineBoard
      prototype: ADTMedicalAssembler
      requirements:
        Capacitor: 3
      stackRequirements:
        Steel: 5
        Glass: 2
        Cable: 4

- type: entity
  id: ADTElectricRangeMachineCircuitBoard
  parent: BaseMachineCircuitboard
  name: electric range machine board
  description: A machine printed circuit board for an electric range.
  components:
     - type: Sprite
       state: service
     - type: MachineBoard
       prototype: ADTKitchenElectricRange
       requirements:
         Capacitor: 3
       stackRequirements:
         Steel: 5
         Glass: 2
         Cable: 4

- type: entity
  id: ADTSyndicateElectricRangeMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: syndicate electric range machine board
  description: A machine printed circuit board for an syndicate electric range.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ADTSyndicateKitchenElectricRange
      requirements:
        Capacitor: 3
      stackRequirements:
        Steel: 5
        Glass: 2
        Cable: 4

- type: entity
  id: ADTKitchenAssemblerMachineCircuitBoard
  parent: BaseMachineCircuitboard
  name: kitchen assembler machine board
  description: A machine printed circuit board for a Food-O-Mat, suitable for a kitchen.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ADTKitchenAssembler
      requirements:
        Capacitor: 1
      stackRequirements:
        Glass: 2
        Cable: 2

#End of Frontier Station
