- type: entity
  id: ADTIndustrialSMESMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Industrial SMES machine board
  description: A machine printed circuit board for a SMES.
  components:
    - type: MachineBoard
      prototype: ADTIndustrialSMESEmpty
      stackRequirements:
        Capacitor: 4
        CableHV: 30
      componentRequirements:
        PowerCell:
          amount: 16
          defaultPrototype: PowerCellSmall

- type: entity
  id: ADTUniversalPipeDispenserCircuitboard
  parent: BaseMachineCircuitboard
  name: universal pipe dispenser board
  description: A machine circuit board for a universal pipe dispenser. Exists in a single copy.
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: ADTUniversalPipeDispenser
      stackRequirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker

- type: entity
  id: ADTBookPrinterMachineCircuitboard
  abstract: true
  parent: BaseMachineCircuitboard
  name: book printer machine board
  components:
  - type: MachineBoard
    prototype: ADTBookPrinter
    stackRequirements:
      Capacitor: 2
      Manipulator: 2
      MatterBin: 2
