- type: entity
  id: ADTUniversalPipeDispenserCircuitboard
  parent: BaseMachineCircuitboard
  name: universal pipe dispenser board
  description: A machine circuit board for a universal pipe dispenser. Exists in a single copy.
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: ADTUniversalPipeDispenser
      stackRequirements:
        Manipulator: 4
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker

# Оригинал данного прототипа был сделан @temporaldarkness (discord). Прототип был взят с https://github.com/ss14-ganimed/ENT14-Master.
# Ganimed-Book-Printer-Start
- type: entity
  id: ADTBookPrinterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: book printer machine board
  components:
  - type: MachineBoard
    prototype: ADTBookPrinter
    stackRequirements:
      Manipulator: 2
# Ganimed-Book-Printer-End

- type: entity
  id: ADTBarmenKettleCircuit
  parent: BaseMachineCircuitboard
  name: kettle machine board
  description: A machine printed circuit board for a kettle.
  components:
    - type: MachineBoard
      prototype: ADTBarmenKettle
      stackRequirements:
        Glass: 1

#Taken from [2670] Pull Request DeltaV
- type: entity
  id: ADTAdvancedMicrowaveMachineCircuitBoard
  parent: MicrowaveMachineCircuitboard
  name: adt-advanced-microwave-machineboard
  components:
  - type: MachineBoard
    prototype: ADTAdvancedMicrowave
    stackRequirements:
      Glass: 4
      Cable: 5
    tagRequirements:
      GlassBeaker:
        amount: 1
        defaultPrototype: Beaker
#End of DeltaV


###  КОФЕ БРЕЙК ДА?!
- type: entity
  id: ADTCoffeeMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: coffee machine machine board
  description: A machine printed circuit board for a soda dispenser.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ADTCoffeeMachineEmpty
      stackRequirements:
        Steel: 5
      tagRequirements:
          GlassBeaker:
            amount: 1
            defaultPrototype: Beaker


- type: entity
  id: ADTCoffeeMachineBluespaceCircuitboard
  parent: BaseMachineCircuitboard
  name: coffee machine bluespace machine board
  description: A machine printed circuit board for a soda dispenser.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ADTCoffeeMachineBluespace
      stackRequirements:
        Steel: 5
        Plasma: 5
        Manipulator: 3
        Glass: 5
      tagRequirements:
          GlassBeaker:
            amount: 1
            defaultPrototype: Beaker

### немного обновления наркоты
- type: entity
  id: ADTColdplateMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: coldplate machine board
  description: A machine printed circuit board for a coldplate.
  components:
    - type: MachineBoard
      prototype: ADTChemistryColdplate
      stackRequirements:
        Glass: 1

#Corvax Next Advanced Service Machinery Start
- type: entity
  id: ADTHydroponicsTrayAdvancedMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: advanced hydroponics tray machine board
  description: A machine printed circuit board for a advanced hydroponics tray.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ADTHydroponicsTrayAdvanced
      stackRequirements:
        Glass: 5
        Cable: 4
        Plasma: 5
      tagRequirements:
        GlassBeaker:
          amount: 3
          defaultPrototype: Beaker

- type: entity
  id: ADTAdvancedReagentGrinderMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: advanced reagent grinder machine board
  description: A machine printed circuit board for a reagent grinder.
  components:
    - type: MachineBoard
      prototype: ADTAdvancedKitchenReagentGrinder
      stackRequirements:
        Manipulator: 6
        Plasma: 5
      tagRequirements:
        GlassBeaker:
          amount: 1
          defaultPrototype: Beaker
#Corvax Next Advanced Service Machinery End

# Taken from Frontier Station
- type: entity
  id: ADTMedicalAssemblerMachineCircuitBoard
  parent: BaseMachineCircuitboard
  name: medical assembler machine board
  description: A machine printed circuit board for a medical assembler.
  components:
    - type: Sprite
      state: medical
    - type: MachineBoard
      prototype: ADTMedicalAssembler
      stackRequirements:
        Manipulator: 1
        Steel: 5
        Glass: 2
        Cable: 4
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker

- type: entity
  id: ADTElectricRangeMachineCircuitBoard
  parent: BaseMachineCircuitboard
  name: electric range machine board
  description: A machine printed circuit board for an electric range.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ADTKitchenElectricRange
      stackRequirements:
        Steel: 5
        Glass: 2
        Cable: 4
      tagRequirements:
        Igniter:
          amount: 1
          defaultPrototype: Igniter

- type: entity
  id: ADTSyndicateElectricRangeMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: syndicate electric range machine board
  description: A machine printed circuit board for an syndicate electric range.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ADTSyndicateKitchenElectricRange
      stackRequirements:
        Steel: 5
        Glass: 2
        Cable: 4
      tagRequirements:
        Igniter:
          amount: 1
          defaultPrototype: Igniter

- type: entity
  id: ADTKitchenAssemblerMachineCircuitBoard
  parent: BaseMachineCircuitboard
  name: kitchen assembler machine board
  description: A machine printed circuit board for a Food-O-Mat, suitable for a kitchen.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ADTKitchenAssembler
      stackRequirements:
        Manipulator: 2
        Glass: 2
        Cable: 2
      tagRequirements:
        GlassBeaker:
          amount: 1
          defaultPrototype: Beaker

#End of Frontier Station

# Блюспейс харвестер, чё уж

- type: entity
  id: ADTMachineBluespaceHarvesterCircuitboard
  parent: BaseMachineCircuitboard
  name: Bluespace Harvester board
  description: A machine board for a Bluespace Harvester
  components:
  - type: Sprite
    sprite: ADT/Objects/Misc/module_bluespace.rsi
    state: bluespace
  - type: MachineBoard
    prototype: ADTBluespaceHarvester
    stackRequirements:
      Glass: 15
      Steel: 15
      CableHV: 5
      Manipulator: 20
      ADTBScrystalArt: 10
    tagRequirements:
      GlassBeaker:
        amount: 5
        defaultPrototype: Beaker
  - type: Item
    size: Normal

# движки

- type: entity
  id: ADTMachineMediumLongThrusterCircuitboard #1x3
  parent: BaseMachineCircuitboard
  name: medium long thruster board
  components:
  - type: Sprite
    state: supply
  - type: MachineBoard
    prototype: ADTMediumLongThruster
    stackRequirements:
      Capacitor: 12
      Steel: 15
      ADTBScrystalArt: 6

- type: entity
  id: ADTMachineBigThrusterCircuitboard #3x3
  parent: BaseMachineCircuitboard
  name: big thruster board
  components:
  - type: Sprite
    state: supply
  - type: MachineBoard
    prototype: ADTBigThruster
    stackRequirements:
      Capacitor: 36
      Steel: 45
      ADTBScrystalArt: 18

- type: entity
  id: ADTMachineMediumThrusterCircuitboard #2x2
  parent: BaseMachineCircuitboard
  name: medium thruster board
  components:
  - type: Sprite
    state: supply
  - type: MachineBoard
    prototype: ADTMediumThruster
    stackRequirements:
      Capacitor: 16
      Steel: 20
      ADTBScrystalArt: 8