- type: entity
  id: ADTIndustrialSMESMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Industrial SMES machine board
  description: A machine printed circuit board for a SMES.
  components:
    - type: MachineBoard
      prototype: ADTIndustrialSMESEmpty
      stackRequirements:
        Capacitor: 4
        CableHV: 30
      componentRequirements:
        PowerCell:
          amount: 16
          defaultPrototype: PowerCellSmall
