using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.MiningShop;

[GenerateTypedNameReferences]
public sealed partial class MiningShopButton : Button
{
    public event Action? OnDrawModeChanged;

    public MiningShopButton()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void DrawModeChanged()
    {
        OnDrawModeChanged?.Invoke();
    }
}

