using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.MiningShop;

[GenerateTypedNameReferences]
public sealed partial class MiningShopEntry : Control
{
    public MiningShopEntry()
    {
        RobustXamlLoader.Load(this);
    }
}

