using Content.Client.Message;
using Content.Shared.ADT.Xenobiology;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client.ADT.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class SlimeScannerWindow : BaseWindow
{
    private readonly IEntityManager _entityManager;
    private readonly IPrototypeManager _prototypes;

    public SlimeScannerWindow()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();

        CloseButton.OnPressed += _ => Close();
    }

    public void SetWindowTitle(string title) => TitleLabel.Text = title;

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos) => DragMode.Move;

    public void Populate(SlimeScannerScannedMessage msg)
    {
        var targetEntity = _entityManager.GetEntity(msg.TargetEntity);
        if (!_entityManager.EntityExists(targetEntity))
        {
            NoDataLabel.Visible = true;
            SlimeInfoContainer.Visible = false;
            ExtractInfoContainer.Visible = false;
            return;
        }

        TargetNameLabel.Text = Identity.Name(targetEntity, _entityManager);
        NoDataLabel.Visible = false;

        if (!string.IsNullOrEmpty(msg.BreedName) && !string.IsNullOrEmpty(msg.ColorHex))
        {
            SlimeInfoContainer.Visible = true;
            ExtractInfoContainer.Visible = false;

            BreedNameLabel.Text = msg.BreedName;
            ColorDisplay.ModulateSelfOverride = Color.FromHex(msg.ColorHex);

            MutationChanceLabel.Text = msg.MutationChance.HasValue
                ? $"{msg.MutationChance.Value * 100:F0}%"
                : Loc.GetString("slime-scanner-unknown");

            ExtractsProducedLabel.Text = msg.ExtractsProduced?.ToString() ?? "0";

            MutationsContainer.RemoveAllChildren();
            if (msg.Mutations != null && msg.Mutations.Count > 0)
            {
                foreach (var mutationName in msg.Mutations)
                {
                    MutationsContainer.AddChild(new Label { Text = $"• {mutationName}" });
                }
            }
            else
            {
                MutationsContainer.AddChild(new Label { Text = Loc.GetString("slime-scanner-no-mutations") });
            }

            if (msg.LocalSlimeCount.HasValue && msg.MaxSlimesPerGrid.HasValue && msg.BreedingSlowdown.HasValue)
            {
                DensityWarningLabel.Visible = true;
                DensityWarningLabel.HorizontalExpand = true;
                DensityWarningLabel.Text = Loc.GetString(
                    "slime-scanner-population-ok",
                    ("count", msg.LocalSlimeCount.Value),
                    ("max", msg.MaxSlimesPerGrid.Value));

                if (msg.BreedingSlowdown.Value > 0f)
                {
                    var pct = (int)MathF.Round(msg.BreedingSlowdown.Value * 100f);
                    var warning = Loc.GetString(
                        "slime-scanner-overcrowding-warning",
                        ("count", msg.LocalSlimeCount.Value),
                        ("max", msg.MaxSlimesPerGrid.Value),
                        ("pct", pct));
                    DensityWarningLabel.SetMarkup(warning);
                }
            }
            else
            {
                DensityWarningLabel.Visible = false;
            }
        }
        else if (msg.Reagents != null && msg.Reagents.Count > 0)
        {
            SlimeInfoContainer.Visible = false;
            ExtractInfoContainer.Visible = true;

            ReagentsContainer.RemoveAllChildren();
            foreach (var reagentInfo in msg.Reagents)
            {
                var color = Color.FromHex(reagentInfo.ColorHex);
                var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 2) };
                var colorRect = new PanelContainer { MinWidth = 20, MinHeight = 20, Margin = new Thickness(0, 0, 5, 0) };
                colorRect.PanelOverride = new StyleBoxFlat(color);
                row.AddChild(colorRect);

                var reagentName = reagentInfo.ReagentId;
                if (_prototypes.TryIndex<ReagentPrototype>(reagentInfo.ReagentId, out var reagentProto))
                    reagentName = reagentProto.LocalizedName;

                row.AddChild(new Label { Text = reagentName });
                ReagentsContainer.AddChild(row);
            }
        }
        else
        {
            NoDataLabel.Visible = true;
            SlimeInfoContainer.Visible = false;
            ExtractInfoContainer.Visible = false;
        }
    }
}
