using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.Modsuits.UI;

[GenerateTypedNameReferences]
public sealed partial class ModuleControl : Control
{
    [Dependency] private readonly IEntityManager _ent = default!;
    public event Action? OnRemoveButtonPressed;
    public event Action? OnActivateButtonPressed;
    public event Action? OnDeactivateButtonPressed;

    public ModuleControl(EntityUid entity, string itemName, bool active, Control? fragment)
    {
        RobustXamlLoader.Load(this);

        EquipmentName.SetMessage(itemName);
        EquipmentView.SetEntity(entity);

        if (fragment != null)
        {
            Separator.Visible = true;
            CustomControlContainer.AddChild(fragment);
        }

        StartupButtons(active);
    }

    private void StartupButtons(bool active)
    {
        var activateText = active ? Loc.GetString("mod-activate-nonactive") : Loc.GetString("mod-activate-active");
        var deactivateText = active ? Loc.GetString("mod-deactivate-active") : Loc.GetString("mod-deactivate-nonactive");
        var ejectText = Loc.GetString("mod-eject");

        ActivateButton.Panel.AddChild(new Label() { Text = activateText, HorizontalAlignment = HAlignment.Center });
        DeactivateButton.Panel.AddChild(new Label() { Text = deactivateText, HorizontalAlignment = HAlignment.Center });
        EjectButton.Panel.AddChild(new Label() { Text = ejectText, HorizontalAlignment = HAlignment.Center });

        ActivateButton.Button.Disabled = active;
        DeactivateButton.Button.Disabled = !active;

        (ActivateButton.Color, DeactivateButton.Color, EjectButton.Color) =
                    (Color.FromHex("#121923ff"), Color.FromHex("#121923ff"), Color.FromHex("#121923ff"));

        (ActivateButton.DisabledColor, DeactivateButton.DisabledColor, EjectButton.DisabledColor) =
                    (Color.FromHex("#04060aFF"), Color.FromHex("#04060aFF"), Color.FromHex("#04060aFF"));

        (ActivateButton.HoveredColor, DeactivateButton.HoveredColor, EjectButton.HoveredColor) =
                    (Color.FromHex("#153b66"), Color.FromHex("#153b66"), Color.FromHex("#153b66"));

        (ActivateButton.BorderColor, DeactivateButton.BorderColor, EjectButton.BorderColor) =
                    (Color.FromHex("#153b66"), Color.FromHex("#153b66"), Color.FromHex("#153b66"));

        ActivateButton.UpdateColor();
        DeactivateButton.UpdateColor();
        EjectButton.UpdateColor();

        EjectButton.OnPressed += _ => OnRemoveButtonPressed?.Invoke();
        ActivateButton.OnPressed += _ => OnActivateButtonPressed?.Invoke();
        DeactivateButton.OnPressed += _ => OnDeactivateButtonPressed?.Invoke();
    }
}
