- type: gameMapPool
  id: SDMapPool
  maps:
  # - Atlas
  # - Bagel
  # - Box
  # - Cog
  # - Cluster
  # - Core
  # - Fland
  # - Marathon
  # - Meta
  # - Oasis
  # - Omega
  # - Origin
  # - Saltern
  # - Packed
  # - Reach
  # - Train

# SD Maps Базовые Актуальные

  - SD_Flicker
  - SD_Newton
  - SD_Pascal
  - SD_Joule
  - SD_Barracuda
  - SD_Whiteout
