- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  # Highpop
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxAstra
  - CorvaxPilgrim
  - CorvaxGlacier
  - Box
  # Midpop
  - CorvaxPaper
  - CorvaxPearl
  - Bagel
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Saltern
  - Packed
  - Omega
