using Content.Client.Lathe;
using Content.Shared.ADT.Research;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.ADT.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class TechnologyInfoPanel : Control
{
    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    private readonly LatheSystem _lathe;

    public TechnologyPrototype Prototype;
    public Action<TechnologyPrototype>? BuyAction;
    public TechnologyInfoPanel(TechnologyPrototype proto, SpriteSystem sprite, bool hasAccess, ResearchAvailablity availablity)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _lathe = _ent.System<LatheSystem>();
        Prototype = proto;
        TechnologyNameLabel.Text = Loc.GetString(proto.Name);
        DisciplineTexture.Texture = sprite.Frame0(_proto.Index<TechDisciplinePrototype>(proto.Discipline).Icon);
        TechnologyTexture.Texture = sprite.Frame0(proto.Icon);

        UnlocksContainer.DisposeAllChildren();
        foreach (var item in proto.RecipeUnlocks)
        {
            var recipe = _proto.Index(item);
            var control = new MiniRecipeCardControl(proto, recipe, _proto, sprite, _lathe);
            UnlocksContainer.AddChild(control);
        }
        if (!hasAccess)
            ResearchButton.ToolTip = Loc.GetString("research-console-no-access-popup");

        Color? color = null;
        switch (availablity)
        {
            case ResearchAvailablity.Researched:
                {
                    ResearchButton.Text = Loc.GetString("research-console-menu-server-researched-button");
                    color = Color.LimeGreen;
                    break;
                }
            case ResearchAvailablity.Unavailable:
                {
                    color = Color.Crimson;
                    break;
                }
            case ResearchAvailablity.Available:
                break;
        }
        TechnologyCostLabel.SetMessage(Loc.GetString("research-console-tech-cost-label", ("cost", proto.Cost)), defaultColor: color);

        ResearchButton.Disabled = !hasAccess || availablity != ResearchAvailablity.Available;
        ResearchButton.OnPressed += Bought;
    }

    protected override void Dispose(bool disposing)
    {
        ResearchButton.OnPressed -= Bought;
        base.Dispose(disposing);
    }
    private void Bought(BaseButton.ButtonEventArgs args)
    {
        BuyAction?.Invoke(Prototype);
    }
}
