using System.Text;
using Content.Shared.ADT.PlantAnalyzer;
using Content.Shared.Atmos;
using Content.Shared.Atmos.Prototypes;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.ADT.PlantAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private const string IndentedNewline = "\n   ";

    public PlantAnalyzerWindow(PlantAnalyzerBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DeathGeneWarning.Text = Loc.GetString("plant-analyzer-warning-death-gene");
        DeathGeneWarning.FontColorOverride = Color.Red;

        MutatingLabel.Text = Loc.GetString("plant-analyzer-warning-mutating");
        MutatingLabel.FontColorOverride = new Color(1f, 0.65f, 0f);

        Tabs.SetTabTitle(0, Loc.GetString("plant-analyzer-window-tab-basics"));
        Tabs.SetTabTitle(1, Loc.GetString("plant-analyzer-window-tab-tolerances"));
        Tabs.SetTabTitle(2, Loc.GetString("plant-analyzer-window-tab-mutations"));
    }

    public void Populate(PlantAnalyzerScannedSeedPlantInformation msg)
    {
        var target = _entityManager.GetEntity(msg.TargetEntity);

        if (target is null)
        {
            NoData.Visible = true;
            Tabs.Visible = false;
            WarningsContainer.Visible = false;
            return;
        }

        NoData.Visible = false;
        Tabs.Visible = true;

        DeathGeneWarning.Visible = !msg.AdvancedInfo.Viable;
        MutatingLabel.Visible = msg.IsMutating;
        
        WarningsContainer.Visible = DeathGeneWarning.Visible || MutatingLabel.Visible;

        StringBuilder chemString = new();
        if (msg.SeedChem is not null)
        {
            foreach (var chem in msg.SeedChem)
            {
                chemString.Append(IndentedNewline);
                if (_prototypeManager.TryIndex<ReagentPrototype>(chem, out var reagent))
                {
                    chemString.Append(reagent.LocalizedName);
                }
                else
                {
                    chemString.Append(chem);
                }
            }
        }

        var exudeGases = GetGasNamesString(msg.ExudeGases);
        var consumeGases = GetGasNamesString(msg.ConsumeGases);

        var noneStr = Loc.GetString("plant-analyzer-plant-gases-none");

        if (msg.IsTray)
            PlantName.Text = Loc.GetString("plant-analyzer-window-label-name-scanned-plant", ("seedName", Loc.GetString(string.IsNullOrEmpty(msg.SeedName) ? "plant-analyzer-unknown-plant" : msg.SeedName)));
        else
            PlantName.Text = Loc.GetString("plant-analyzer-window-label-name-scanned-seed", ("seedName", Loc.GetString(string.IsNullOrEmpty(msg.SeedName) ? "plant-analyzer-unknown-plant" : msg.SeedName)));

        PlantYield.Text = Loc.GetString("plant-analyzer-plant-yield-text", ("seedYield", $"{msg.SeedYield:D0}"));
        Potency.Text = Loc.GetString("plant-analyzer-plant-potency-text", ("seedPotency", $"{msg.SeedPotency:F0}"));
        Endurance.Text = Loc.GetString("plant-analyzer-plant-endurance-text", ("seedEndurance", $"{msg.Endurance:F0}"));
        Repeat.Text = Loc.GetString("plant-analyzer-plant-harvest-text", ("plantHarvestType", Loc.GetString($"plant-analyzer-harvest-{msg.HarvestType}")));
        Lifespan.Text = Loc.GetString("plant-analyzer-plant-lifespan-text", ("lifespan", $"{msg.Lifespan:F1}"));
        Maturation.Text = Loc.GetString("plant-analyzer-plant-maturation-text", ("maturation", $"{msg.Maturation:F1}"));
        Production.Text = Loc.GetString("plant-analyzer-plant-production-text", ("production", $"{msg.Production:F1}"));
        GrowthStages.Text = Loc.GetString("plant-analyzer-plant-growthstages-text", ("growthStages", $"{msg.GrowthStages:D0}"));
        Chemicals.Text = Loc.GetString("plant-analyzer-plant-chemistry-text", ("seedChem", chemString));
        ExudeGases.Text = Loc.GetString("plant-analyzer-plant-exude-text", ("gases", exudeGases.Length == 0 ? noneStr : exudeGases.ToString()));
        ConsumeGases.Text = Loc.GetString("plant-analyzer-plant-consume-text", ("gases", consumeGases.Length == 0 ? noneStr : consumeGases.ToString()));

        var adv = msg.AdvancedInfo;
        NutrientUsage.Text = Loc.GetString("plant-analyzer-tolerance-nutrient-usage", ("nutrientUsage", $"{adv.NutrientConsumption:F2}"));
        WaterUsage.Text = Loc.GetString("plant-analyzer-tolerance-water-usage", ("waterUsage", $"{adv.WaterConsumption:F2}"));
        IdealHeat.Text = Loc.GetString("plant-analyzer-tolerance-ideal-heat", ("idealHeat", $"{adv.IdealHeat:F0}"));
        HeatTolerance.Text = Loc.GetString("plant-analyzer-tolerance-heat-tolerance", ("heatTolerance", $"{adv.HeatTolerance:F1}"));
        IdealLight.Text = Loc.GetString("plant-analyzer-tolerance-ideal-light", ("idealLight", $"{adv.IdealLight:F1}"));
        LightTolerance.Text = Loc.GetString("plant-analyzer-tolerance-light-tolerance", ("lightTolerance", $"{adv.LightTolerance:F1}"));
        ToxinsTolerance.Text = Loc.GetString("plant-analyzer-tolerance-toxin-tolerance", ("toxinsTolerance", $"{adv.ToxinsTolerance:F1}"));
        LowPressureTolerance.Text = Loc.GetString("plant-analyzer-tolerance-low-pressure", ("lowPressureTolerance", $"{adv.LowPressureTolerance:F1}"));
        HighPressureTolerance.Text = Loc.GetString("plant-analyzer-tolerance-high-pressure", ("highPressureTolerance", $"{adv.HighPressureTolerance:F1}"));
        PestTolerance.Text = Loc.GetString("plant-analyzer-tolerance-pest-tolerance", ("pestTolerance", $"{adv.PestTolerance:F1}"));
        WeedTolerance.Text = Loc.GetString("plant-analyzer-tolerance-weed-tolerance", ("weedTolerance", $"{adv.WeedTolerance:F1}"));

        var mutations = new List<string>();
        if (adv.Mutations.HasFlag(MutationFlags.TurnIntoKudzu))
        {
            mutations.Add(Loc.GetString("plant-analyzer-mutation-turnintokudzu"));
        }

        if (adv.Mutations.HasFlag(MutationFlags.Seedless))
        {
            mutations.Add(Loc.GetString("plant-analyzer-mutation-seedless"));
        }

        if (adv.Mutations.HasFlag(MutationFlags.Ligneous))
        {
            mutations.Add(Loc.GetString("plant-analyzer-mutation-ligneous"));
        }

        if (adv.Mutations.HasFlag(MutationFlags.CanScream))
        {
            mutations.Add(Loc.GetString("plant-analyzer-mutation-canscream"));
        }

        PlantTraits.Text = mutations.Count == 0 ? "-" : string.Join(IndentedNewline, mutations);

        if (msg.Speciation is null || msg.Speciation.Length == 0)
        {
            PlantSpeciation.Text = "-";
        }
        else
        {
            var speciationList = new List<string>();
            foreach (var species in msg.Speciation)
            {
                speciationList.Add(Loc.GetString(species));
            }
            PlantSpeciation.Text = string.Join(IndentedNewline, speciationList);
        }
    }

    private StringBuilder GetGasNamesString(Gas[] gases)
    {
        var output = new StringBuilder();
        foreach (var gas in gases)
        {
            var proto = _prototypeManager.Index<GasPrototype>(((int)gas).ToString());
            output.Append(IndentedNewline);
            output.Append(Loc.GetString(proto.Name));
        }
        return output;
    }
}
