using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.Telephone;

[GenerateTypedNameReferences]
public sealed partial class ADTPhoneWindow : DefaultWindow
{
    public ADTPhoneWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
