- type: job
  id: ADTJobAdminGod
  name: job-name-admin-god
  description: job-description-magistrat
  playTimeTracker: JobAdminGod
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 600000
  startingGear: ADTAdminGodlGear
  icon: "JobIconMagistrat" # По умолчанию поставится Unknown
  requireAdminNotify: true
  overrideConsoleVisibility: false
  joinNotifyCrew: false
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
    - Command
    - Brig
    - Maintenance
    - Service
    - Security
    - Magistrate
    - Lawyer
    - IAA
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ADTAdminGodlGear
  equipment:
    shoes: ADTClothingFootCloudGod
