- type: startingGear
  id: ADTCBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesNightVisionAdvanced
    ears: ClothingHeadsetAltCentCom
    neck: ADTClothingBeltHolsterN1984Fill
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ADTClothingShoesBootsMagERT
    id: CBURNPDA
    pocket2: WeaponLaserGun
    belt: ClothingBeltMilitaryWebbing
    suitstorage: JetpackBlackFilled
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - CrowbarOrange
    - Chainsaw
    - ADTMedkitERTFilled
    - MagazineShotgunIncendiary
    - MagazineShotgunIncendiary
    - MagazineShotgun
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - SpaceCash500
    - BoxShotgunIncendiary
    - BoxLethalshot
    - WeaponShotgunEnforcer
    - CombatKnife

- type: startingGear
  id: ADTCmndCBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesNightVisionAdvanced
    ears: ClothingHeadsetAltCentCom
    neck: ADTClothingBeltHolsterN1984Fill
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURNLeader
    shoes: ADTClothingShoesBootsMagERT
    id: CBURNPDA
    pocket1: WeaponPulsePistol
    pocket2: DoubleEmergencyOxygenTankFilled
    suitstorage: JetpackBlackFilled
    belt: ADTClothingBeltMilitaryWebbingCBURNFilled
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalEngineering
    - JawsOfLife
    - Chainsaw
    - ADTMedkitERTFilled
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - RubberStampCentcom
    - SpaceCash1000
    - ADTertRevolutionaryMechUplink
    - WeaponShotgunBulldog
    - CombatKnife
