- type: job
  id: ADTJobTimePatrol
  name: job-name-time-patrol
  description: job-description-magistrat
  playTimeTracker: JobTimePatrol
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 600000
  startingGear: ADTTimePatrolGear
  icon: "JobIconMagistrat"
  requireAdminNotify: true
  overrideConsoleVisibility: false
  joinNotifyCrew: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
    - Command
    - Brig
    - Maintenance
    - Service
    - Security
    - Magistrate
    - Lawyer
    - IAA
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ADTTimePatrolGear
  equipment:
    back: ADTClothingBackpackTimePatrol
    belt: EmergencyOxygenTankFilled
    neck: ADTClothingNeckMantleTimePatrol
    mask: ADTChronosMask
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ADTClothingShoesBootsCombatTimePatrol
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: ADTClothingOuterHardsuitTimePatrol
    suitstorage: ADTWeaponPulseTimePatrol
    pocket1: EnergySword
    pocket2: MindFlushingFlash
