using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.GPS;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.GPS.UI;

[GenerateTypedNameReferences]
public sealed partial class GpsWindow : DefaultWindow
{
    private static readonly Color StripeColor = new(1f, 1f, 1f, 0.05f);

    public event Action? OnTogglePressed;
    public event Action? OnRangePressed;
    public event Action<string>? OnTagEntered;

    public GpsWindow()
    {
        RobustXamlLoader.Load(this);

        PowerButton.OnPressed += _ => OnTogglePressed?.Invoke();
        RangeButton.OnPressed += _ => OnRangePressed?.Invoke();
        TagButton.OnPressed += _ => SubmitTag();
        TagEdit.OnTextEntered += _ => SubmitTag();
    }

    private void SubmitTag()
    {
        OnTagEntered?.Invoke(TagEdit.Text);
    }

    public void UpdateState(GpsBoundUserInterfaceState state)
    {
        PowerButton.Disabled = !state.CanToggle;
        PowerButton.Text = Loc.GetString(state.Tracking
            ? "adt-gps-window-power-on"
            : "adt-gps-window-power-off");

        RangeButton.Text = Loc.GetString(state.SameMapOnly
            ? "adt-gps-window-range-local"
            : "adt-gps-window-range-global");

        if (!TagEdit.HasKeyboardFocus())
            TagEdit.Text = state.Tag;

        UpdateStatus(state);
        UpdateSignals(state);
    }

    private void UpdateStatus(GpsBoundUserInterfaceState state)
    {
        if (state.Emped)
        {
            LocationLabel.Text = Loc.GetString("adt-gps-window-emped");
            PositionLabel.Visible = false;
            return;
        }

        if (!state.Tracking)
        {
            LocationLabel.Text = Loc.GetString("adt-gps-window-disabled");
            PositionLabel.Visible = false;
            return;
        }

        LocationLabel.Text = state.Location ?? Loc.GetString("adt-gps-signal-unknown");
        PositionLabel.Visible = true;
        PositionLabel.Text = state.Position == null
            ? Loc.GetString("adt-gps-signal-unknown")
            : FormatPosition(state.Position.Value);
    }

    private void UpdateSignals(GpsBoundUserInterfaceState state)
    {
        SignalList.RemoveAllChildren();

        var showSignals = state.Tracking && !state.Emped;
        SignalsLabel.Visible = showSignals;

        for (var i = 0; i < state.Signals.Count; i++)
        {
            SignalList.AddChild(BuildRow(state.Signals[i], state.Position, striped: i % 2 == 0));
        }

        EmptyLabel.Visible = showSignals && state.Signals.Count == 0;
    }

    private Control BuildRow(GpsSignalData signal, Vector2i? origin, bool striped)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6,
            Margin = new Thickness(4, 2, 4, 2),
        };

        row.AddChild(new Label
        {
            Text = signal.Tag,
            FontColorOverride = signal.Color,
            MinWidth = 130,
            ClipText = true,
        });

        row.AddChild(new Label
        {
            Text = signal.Description ?? string.Empty,
            HorizontalExpand = true,
            ClipText = true,
            StyleClasses = { StyleNano.StyleClassLabelSubText },
        });

        var icon = new ADTDirectionIcon(snap: false, minDistance: 0.5f)
        {
            SetSize = new Vector2(16, 16),
            VerticalAlignment = VAlignment.Center,
        };
        row.AddChild(icon);

        var distance = new Label
        {
            MinWidth = 55,
            Align = Label.AlignMode.Right,
        };
        row.AddChild(distance);

        var position = new Label
        {
            MinWidth = 95,
            Align = Label.AlignMode.Right,
            StyleClasses = { StyleNano.StyleClassLabelSubText },
        };
        row.AddChild(position);

        FillMeasurements(signal, origin, icon, distance, position);

        if (!striped)
            return row;

        var stripe = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = StripeColor,
            },
        };

        stripe.AddChild(row);
        return stripe;
    }

    private void FillMeasurements(GpsSignalData signal, Vector2i? origin, ADTDirectionIcon icon, Label distance, Label position)
    {
        if (signal.Position == null)
        {
            position.Text = Loc.GetString("adt-gps-signal-unknown");
            distance.Text = Loc.GetString("adt-gps-signal-unknown");
            return;
        }

        position.Text = FormatPosition(signal.Position.Value);

        if (!signal.SameMap || origin == null)
        {
            distance.Text = Loc.GetString("adt-gps-signal-off-map");
            return;
        }

        var delta = (Vector2) (signal.Position.Value - origin.Value);

        icon.UpdateDirection(delta, Angle.Zero);
        distance.Text = Loc.GetString("adt-gps-signal-distance", ("distance", (int) delta.Length()));
    }

    private static string FormatPosition(Vector2i position)
    {
        return Loc.GetString("adt-gps-signal-position", ("x", position.X), ("y", position.Y));
    }
}
