using System.Linq;
using System.Numerics;
using Content.Shared.ADT.Body.Allergies;
using Content.Shared.Atmos;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.Damage.Systems;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.ADT.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaHealthScanControl : BoxContainer
{
    private static readonly Color Green = Color.FromHex("#00FF00");
    private static readonly Color Red = Color.FromHex("#FF0000");

    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;
    private readonly DamageableSystem _damageable;
    private Color _monitorFg = Color.White;
    private Color _dividerColor = Color.FromHex("#8A8A8A");

    public PdaHealthScanControl()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();
        _damageable = _entityManager.System<DamageableSystem>();
    }

    public void ApplyDividerColor(Color color)
    {
        _dividerColor = color;
        var box = new StyleBoxFlat { BackgroundColor = color };
        PanelDivider.PanelOverride = box;
        PatientDivider.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
        AlertsDivider.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
        ChemicalsDivider.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
    }

    public void ApplyMonitorTextTheme(Color fg)
    {
        _monitorFg = fg;
        ApplyTextColor(this, fg);
    }

    private static void ApplyTextColor(Control control, Color fg)
    {
        switch (control)
        {
            case Label label when label.FontColorOverride == null
                                  || Color.ToHsv(label.FontColorOverride.Value).Z < 0.4f:
                label.FontColorOverride = fg;
                break;
            case RichTextLabel:
                break;
        }

        foreach (var child in control.Children)
            ApplyTextColor(child, fg);
    }

    public void Populate(HealthAnalyzerUiState state)
    {
        var target = _entityManager.GetEntity(state.TargetEntity);

        if (target == null
            || !_entityManager.TryGetComponent<DamageableComponent>(target, out _))
        {
            NoPatientDataText.Visible = true;
            PatientIdentityContainer.Visible = false;
            VitalsStatusContainer.Visible = false;
            PatientDivider.Visible = false;
            GroupsContainer.RemoveAllChildren();
            ChemicalsContainer.RemoveAllChildren();
            ChemicalsDivider.Visible = false;
            ChemicalsContainer.Visible = false;
            ChemicalsHeader.Visible = false;
            ChemicalsScroll.Visible = false;
            TraumaTotalLabel.Text = string.Empty;
            return;
        }

        NoPatientDataText.Visible = false;
        PatientIdentityContainer.Visible = true;
        VitalsStatusContainer.Visible = true;
        PatientDivider.Visible = true;

        ScanModeLabel.Text = state.ScanMode.HasValue
            ? state.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");
        ScanModeLabel.FontColorOverride = state.ScanMode is true ? Color.Green : Color.Red;

        SpriteView.SetEntity(target.Value);
        SpriteView.Visible = state.ScanMode is true;
        NoDataTex.Visible = !SpriteView.Visible;

        var name = new FormattedMessage();
        name.PushColor(_monitorFg);
        name.AddText(_entityManager.HasComponent<MetaDataComponent>(target.Value)
            ? Identity.Name(target.Value, _entityManager)
            : Loc.GetString("health-analyzer-window-entity-unknown-text"));
        NameLabel.SetMessage(name);

        SpeciesLabel.Text =
            _entityManager.TryGetComponent<HumanoidProfileComponent>(target.Value, out var humanoid)
                ? Loc.GetString(_prototypes.Index(humanoid.Species).Name)
                : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        TemperatureLabel.Text = !float.IsNaN(state.Temperature)
            ? $"{state.Temperature - Atmospherics.T0C:F1} °C ({state.Temperature:F1} K)"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        if (!float.IsNaN(state.BloodLevel))
        {
            var bloodPercent = state.BloodLevel;
            var exclamations = bloodPercent switch
            {
                <= 0f => "!!!!",
                <= 0.25f => "!!!",
                <= 0.5f => "!!",
                <= 0.75f => "!",
                _ => ""
            };
            BloodLabel.Text = $"{bloodPercent * 100:F1}%{exclamations}";
            var clampedPercent = Math.Max(bloodPercent, 0.5f);
            var scaled = (clampedPercent - 0.5f) / 0.5f;
            BloodLabel.FontColorOverride = Color.InterpolateBetween(Red, Green, scaled);
        }
        else
        {
            BloodLabel.Text = Loc.GetString("health-analyzer-window-entity-unknown-value-text");
            BloodLabel.FontColorOverride = null;
        }

        AllergyText.Visible = _entityManager.HasComponent<AllergicComponent>(target.Value);

        StatusLabel.Text =
            _entityManager.TryGetComponent<MobStateComponent>(target.Value, out var mobState)
                ? GetStatus(mobState.CurrentState)
                : Loc.GetString("health-analyzer-window-entity-unknown-text");

        TraumaTotalLabel.Text = _damageable.GetTotalDamage(target.Value).ToString();

        var showAlerts = state.Unrevivable == true || state.Bleeding == true;
        AlertsDivider.Visible = showAlerts;
        AlertsContainer.Visible = showAlerts;
        if (showAlerts)
            AlertsContainer.RemoveAllChildren();

        if (state.Unrevivable == true)
        {
            // ADT-Tweak Start - alert formatter
            AlertsContainer.AddChild(CreateAlertLabel(
                Loc.GetString("health-analyzer-window-entity-unrevivable-text"),
                Color.Yellow));
        }

        if (state.Bleeding == true)
        {
            AlertsContainer.AddChild(CreateAlertLabel(
                Loc.GetString("health-analyzer-window-entity-bleeding-text"),
                Color.Red));
            // ADT-Tweak End
        }

        var damagePerType = _damageable.GetAllDamage(target.Value).DamageDict;
        var groupOrder = new List<ProtoId<DamageGroupPrototype>> { "Burn", "Brute", "Airloss", "Toxin", "Genetic" };
        var sortedGroups = _damageable.GetDamagePerGroup(target.Value)
            .Where(g => g.Value > 0)
            .OrderBy(g => groupOrder.IndexOf(g.Key))
            .ToDictionary(g => g.Key, g => g.Value);

        DrawDiagnosticGroups(sortedGroups, damagePerType);
        DrawMetabolizingChemicals(state.MetabolizingReagents);
        ApplyTextColor(GroupsContainer, _monitorFg);
        ApplyTextColor(ChemicalsContainer, _monitorFg);
        ApplyTextColor(VitalsStatusContainer, _monitorFg);
    }

    private static string GetStatus(MobState mobState)
    {
        return mobState switch
        {
            MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
            MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
            MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
        };
    }

    private void DrawDiagnosticGroups(
        Dictionary<ProtoId<DamageGroupPrototype>, FixedPoint2> groups,
        IReadOnlyDictionary<ProtoId<DamageTypePrototype>, FixedPoint2> damageDict)
    {
        GroupsContainer.RemoveAllChildren();

        BoxContainer? currentRow = null;
        var columnIndex = 0;
        foreach (var (damageGroupId, damageAmount) in groups)
        {
            if (columnIndex % 2 == 0)
            {
                currentRow = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    SeparationOverride = 2,
                    Margin = columnIndex == 0 ? default : new Thickness(0, 2, 0, 0),
                };
                GroupsContainer.AddChild(currentRow);
            }

            var groupTitleText = _prototypes.Index<DamageGroupPrototype>(damageGroupId).LocalizedName;

            var groupBox = new PanelContainer
            {
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1,
                MinWidth = 120,
            };

            groupBox.PanelOverride = new StyleBoxFlat
            {
                BorderColor = _dividerColor,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4,
            };

            var groupContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            groupContainer.AddChild(CreateDiagnosticGroupTitleRow(groupTitleText, (float)damageAmount, damageGroupId));

            var divider = new PanelContainer
            {
                MinHeight = 1,
                Margin = new Thickness(0, 0, 0, 4),
                HorizontalExpand = true,
            };
            divider.PanelOverride = new StyleBoxFlat(_dividerColor);
            groupContainer.AddChild(divider);

            var group = _prototypes.Index<DamageGroupPrototype>(damageGroupId);
            foreach (var type in group.DamageTypes)
            {
                if (!damageDict.TryGetValue(type, out var typeAmount) || typeAmount <= 0)
                    continue;

                var damageRow = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    Margin = new Thickness(0, 2),
                    HorizontalExpand = true,
                };
                damageRow.AddChild(new TextureRect
                {
                    SetSize = new Vector2(15, 15),
                    Texture = GetTexture(type.ToString().ToLowerInvariant()),
                    Margin = new Thickness(0, 0, 4, 0),
                    VerticalAlignment = VAlignment.Center,
                });
                damageRow.AddChild(new Label
                {
                    Text = _prototypes.Index<DamageTypePrototype>(type).LocalizedName,
                    HorizontalExpand = true,
                    ClipText = true,
                });
                damageRow.AddChild(new Label
                {
                    Text = typeAmount.ToString(),
                    Margin = new Thickness(6, 0, 0, 0),
                    HorizontalAlignment = HAlignment.Right,
                    VerticalAlignment = VAlignment.Center,
                });
                groupContainer.AddChild(damageRow);
            }

            groupBox.AddChild(groupContainer);
            currentRow!.AddChild(groupBox);
            columnIndex++;
        }

        if (currentRow != null && columnIndex % 2 == 1)
        {
            currentRow.AddChild(new Control
            {
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1,
            });
        }
    }

    private void DrawMetabolizingChemicals(List<(string ReagentId, FixedPoint2 Quantity)>? reagents)
    {
        ChemicalsContainer.RemoveAllChildren();
        var hasChemicals = reagents != null && reagents.Count > 0;
        ChemicalsDivider.Visible = hasChemicals;
        ChemicalsContainer.Visible = hasChemicals;
        ChemicalsHeader.Visible = hasChemicals;
        ChemicalsScroll.Visible = hasChemicals;

        if (!hasChemicals || reagents == null)
            return;

        foreach (var reagent in reagents.OrderByDescending(r => r.Quantity))
        {
            var reagentName = reagent.ReagentId;
            var reagentColor = Color.Gray;
            if (_prototypes.TryIndex<ReagentPrototype>(reagent.ReagentId, out var reagentProto))
            {
                reagentName = reagentProto.LocalizedName;
                reagentColor = reagentProto.SubstanceColor;
            }

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2),
            };
            var colorBar = new PanelContainer
            {
                MinWidth = 10,
                MinHeight = 16,
                Margin = new Thickness(0, 0, 6, 0),
                VerticalAlignment = VAlignment.Center,
            };
            colorBar.PanelOverride = new StyleBoxFlat(reagentColor);
            row.AddChild(colorBar);
            row.AddChild(new Label
            {
                Text = reagentName,
                HorizontalExpand = true,
                ClipText = true,
                VerticalAlignment = VAlignment.Center,
            });
            row.AddChild(new Label
            {
                Text = $"{reagent.Quantity}u",
                Margin = new Thickness(4, 0, 0, 0),
                HorizontalAlignment = HAlignment.Right,
                VerticalAlignment = VAlignment.Center,
            });
            ChemicalsContainer.AddChild(row);
        }
    }

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/ADT/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);
        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out _))
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");
        return _spriteSystem.Frame0(rsiSprite);
    }

    private BoxContainer CreateDiagnosticGroupTitleRow(string text, float damageAmount, string damageGroupId)
    {
        var clampedDamage = Math.Min(damageAmount, 100f);
        var titleColor = Color.InterpolateBetween(Green, Red, clampedDamage / 100f);
        var exclamations = damageAmount switch
        {
            > 200f => " !!!!",
            > 100f => " !!!",
            > 75f => " !!",
            > 50f => " !",
            _ => ""
        };

        var titleRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 4),
            HorizontalExpand = true,
        };
        titleRow.AddChild(new TextureRect
        {
            SetSize = new Vector2(15, 15),
            Texture = GetTexture(damageGroupId.ToLowerInvariant()),
            Margin = new Thickness(0, 0, 4, 0),
            VerticalAlignment = VAlignment.Center,
        });
        titleRow.AddChild(new Label
        {
            Text = text + exclamations,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = titleColor,
        });
        return titleRow;
    }

    // ADT-Tweak Start - alert formatter
    private static RichTextLabel CreateAlertLabel(string text, Color color)
    {
        var label = new RichTextLabel
        {
            HorizontalExpand = true,
            Margin = new Thickness(4, 4),
        };
        label.SetMessage(FormattedMessage.FromMarkupPermissive(
            $"[color={color.ToHex()}]{FormattedMessage.EscapeText(text)}[/color]"));
        return label;
    }
    // ADT-Tweak End
}
