- type: job
  id: ADTBattleShipMarineLeutenantKMT
  name: job-name-marine-leutenant-kmt
  description: job-description-marine-leutenant-kmt
  playTimeTracker: JobADTBattleShipMarineLeutenantKMT
  requirements:
    - !type:SexRequirement
      allowedSex:
      - Male
    - !type:SpeciesRequirement
      inverted: false
      species:
      - Human
    - !type:DepartmentTimeRequirement
      department: Security
      time: 144000 #40 hrs # ADT-RoleTime
    - !type:AgeRequirement #ADT-Tweak
      requiredAge: 25
  startingGear: ADTBattleShipMarineLeutenantKMTGear
  icon: "JobIconMarineLeutenantKMT"
  joinNotifyCrew: true
  weight: 10
  supervisors: job-supervisors-kmt-captain
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - KMT
    - type: FriendlyFire
      enabled: true
    - type: FriendlyFireToggleable

- type: startingGear
  id: ADTBattleShipMarineLeutenantKMTGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetERTSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ADTBaseUplinkBOBERT
  storage:
    back:
    - BoxSurvivalEngineering
    - BoxZiptie
    - CrowbarRed
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
