using Content.Client.Humanoid;
using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.CharecterFlavor;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC; // Add this

namespace Content.Client.ADT.CharecterFlavor;

[GenerateTypedNameReferences]
public sealed partial class CharecterFlavorWindow : FancyWindow
{
    private readonly IEntityManager _entityManager;
    private EntityUid _charecter;
    public CharecterFlavorWindow()
    {
        RobustXamlLoader.Load(this);
        _entityManager = IoCManager.Resolve<IEntityManager>();
    }

    public void SetEntity(EntityUid uid)
    {
        CharecterView.SetEntity(uid);
        _charecter = uid;
        if (!_entityManager.TryGetComponent<CharecterFlavorComponent>(_charecter, out var flavor))
            return;
        if (!_entityManager.TryGetComponent<MetaDataComponent>(uid, out var metaData))
            return;
        Title = metaData.EntityName;
        FlavorTextLabel.Text = flavor.FlavorText;
        OOCNotesLabel.Text = flavor.OOCNotes;
    }
}