using System.Numerics;
using Content.Client.Humanoid;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.CharecterFlavor;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.CharecterFlavor;

[GenerateTypedNameReferences]
public sealed partial class CharacterFlavorWindow : FancyWindow
{
    private readonly IEntityManager _entityManager;
    private readonly IClyde _clyde = default!;
    private EntityUid _charecter;

    public CharacterFlavorWindow()
    {
        RobustXamlLoader.Load(this);
        _entityManager = IoCManager.Resolve<IEntityManager>();
        _clyde = IoCManager.Resolve<IClyde>();

        HeadshotLoadingLabel.SetMarkup(Loc.GetString("headshot-loading"));
    }

    public void SetEntity(EntityUid uid)
    {
        CharecterView.SetEntity(uid);
        _charecter = uid;

        if (!_entityManager.TryGetComponent<CharacterFlavorComponent>(_charecter, out var flavor))
            return;

        if (!_entityManager.TryGetComponent<MetaDataComponent>(uid, out var metaData))
            return;

        if (flavor.HeadshotUrl != string.Empty)
        {
            HeadshotImage.TexturePath = "/Textures/ADT/Interface/headshot-loading.png";
            HeadshotLoadingLabel.Visible = true;
        }

        Title = metaData.EntityName;
        FlavorTextLabel.Text = flavor.FlavorText;
        OOCNotesLabel.Text = flavor.OOCNotes;
    }

    public void SetHeadshot(byte[] image)
    {
        var headshot = LoadTextureFromBytes(image);

        if (headshot != null)
        {
            HeadshotImage.Texture = headshot;
            HeadshotImage.ModulateSelfOverride = null;
            HeadshotLoadingLabel.Visible = false;
        }
        else
            HeadshotContainer.Visible = false;
    }

    private Texture? LoadTextureFromBytes(byte[] imageBytes)
    {
        try
        {
            using var memoryStream = new System.IO.MemoryStream(imageBytes);
            using var image = SixLabors.ImageSharp.Image.Load<SixLabors.ImageSharp.PixelFormats.Rgba32>(memoryStream);
            return _clyde.LoadTextureFromImage(image);
        }
        catch
        {
            return null;
        }
    }
}
