using Content.Client.ADT.VendingMachines.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.VendingMachines;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client.ADT.Colormat.UI;

[GenerateTypedNameReferences]
public sealed partial class ADTColormatWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    private EntityUid? _item;
    private EntityUid? _dummy;

    public event Action? OnEject;
    public event Action<Color?>? OnSaveColor;

    public ADTColormatWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SaveButton.OnPressed += _ => OnSaveColor?.Invoke(ColorPicker.CurrentColor);
        EjectButton.OnPressed += _ => OnEject?.Invoke();
    }

    public override void Close()
    {
        DeleteDummy();
        base.Close();
    }

    public void Update(EntityUid? item)
    {
        DeleteDummy();
        _item = item;

        if (item is { } uid)
        {
            if (_entMan.TryGetComponent(uid, out MetaDataComponent? meta) && meta.EntityPrototype is { } proto)
            {
                _dummy = _entMan.Spawn(proto.ID);
                ColorPicker.SetDummy(_dummy);
            }

            if (_entMan.TryGetComponent(uid, out ADTClothingPaintComponent? paint))
                ColorPicker.SetColor(paint.PaintColor ?? Color.White);
            else
                ColorPicker.SetColor(Color.White);

            ItemNameLabel.Text = _entMan.GetComponent<MetaDataComponent>(uid).EntityName;
            ColorPicker.Visible = true;
        }
        else
        {
            ColorPicker.SetDummy(null);
            ColorPicker.Visible = false;
            ItemNameLabel.Text = Loc.GetString("colormat-insert-hint");
        }

        SaveButton.Disabled = item == null;
        EjectButton.Disabled = item == null;
    }

    private void DeleteDummy()
    {
        if (_dummy is { } dummy)
        {
            _entMan.DeleteEntity(dummy);
            _dummy = null;
        }
    }
}