using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.Minesweeper;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.ADT.Minesweeper;

[GenerateTypedNameReferences]
public sealed partial class MinesweeperWindow : FancyWindow
{
    private int GridSize = 10;
    private int MineCount = 15;

    private Button[,] _buttons = new Button[1, 1];
    private bool[,] _mines = new bool[1, 1];
    private bool[,] _revealed = new bool[1, 1];
    private bool[,] _flags = new bool[1, 1];
    private readonly Random _rand = new();

    private GridContainer _mineGrid = default!;

    private bool _minesPlaced = false;
    private bool _flagMode = false;
    private MinesweeperComponent _comp = default!;
    // private float _elapsedTime = 0f;
    private bool _gameEnd = false;
    private Stopwatch _stopwatch = new();
    // private List<MinesweeperRecord> _records = new();

    // Список сложностей для выбора
    private readonly List<(string name, int size, int mines)> _difficulties = new()
    {
        ("Debug", 4, 1),
        ("Легко", 8, 10),
        ("Средне", 10, 15),
        ("Сложно", 15, 35)
    };

    public MinesweeperWindow()
    {
        RobustXamlLoader.Load(this);

        ToggleFlagButton.OnPressed += _ => ToggleFlagMode();
        NewGameButton.OnPressed += _ => NewGame();

        InitializeDifficultyOptions();

        NewGame();
    }

    protected override void Opened()
    {
        base.Opened();
    }

    private void InitializeDifficultyOptions()
    {
        DifficultySelect.Clear();

        for (int i = 0; i < _difficulties.Count; i++)
        {
            DifficultySelect.AddItem(_difficulties[i].name, i); // id - индекс
        }

        DifficultySelect.OnItemSelected += args =>
        {
            int index = (int)args.Id;
            var selected = _difficulties[index];
            GridSize = selected.size;
            MineCount = selected.mines;
            DifficultySelect.SelectId(index);
            NewGame();
        };

        DifficultySelect.SelectId(1); // Выбираем "Средне" по умолчанию (индекс 1)
    }

    private void NewGame()
    {
        _gameEnd = false;
        // _elapsedTime = 0f;
        _stopwatch.Restart();
        GameStatusLabel.Text = "Игра началась...";
        GameStatusLabel.FontColorOverride = Color.Green;


        _minesPlaced = false;
        _flagMode = false;
        ToggleFlagButton.Text = "Режим: Открыть";

        _buttons = new Button[GridSize, GridSize];
        _mines = new bool[GridSize, GridSize];
        _revealed = new bool[GridSize, GridSize];
        _flags = new bool[GridSize, GridSize];

        MineContainer.RemoveAllChildren();

        _mineGrid = new GridContainer
        {
            Columns = GridSize,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        MineContainer.AddChild(_mineGrid);

        GenerateGrid();
    }

    private void GenerateGrid()
    {
        for (int y = 0; y < GridSize; y++)
        {
            for (int x = 0; x < GridSize; x++)
            {
                var button = new Button
                {
                    MinSize = new Vector2(32, 32),
                    MaxSize = new Vector2(32, 32),
                    StyleClasses = { StyleBase.ButtonSquare },
                    Text = "",
                    Disabled = false,
                    Modulate = Color.White
                };

                int localX = x, localY = y;
                button.OnPressed += _ => OnTileClicked(localX, localY);

                _buttons[x, y] = button;
                _mineGrid.AddChild(button);
            }
        }
    }

    private void PlaceMinesExceptFirstClick(int safeX, int safeY)
    {
        int placed = 0;
        while (placed < MineCount)
        {
            int x = _rand.Next(GridSize);
            int y = _rand.Next(GridSize);

            if (x >= safeX - 1 && x <= safeX + 1 &&
                y >= safeY - 1 && y <= safeY + 1)
                continue;

            if (_mines[x, y])
                continue;

            _mines[x, y] = true;
            placed++;
        }
    }

    private void OnTileClicked(int x, int y)
    {
        if (_gameEnd) return;

        if (!_minesPlaced)
        {
            PlaceMinesExceptFirstClick(x, y);
            _minesPlaced = true;
        }

        if (_flagMode)
        {
            if (!_revealed[x, y])
            {
                _flags[x, y] = !_flags[x, y];
                _buttons[x, y].Text = _flags[x, y] ? "🏳" : "";
            }
            return;
        }

        if (_revealed[x, y] || _flags[x, y])
            return;

        _revealed[x, y] = true;

        if (_mines[x, y])
        {
            _buttons[x, y].Text = "💣";
            _buttons[x, y].Modulate = Color.Red;
            RevealAllMines();
            GameStatusLabel.Text = "💣 Вы подорвались на мине!";
            GameStatusLabel.FontColorOverride = Color.Red;
            _gameEnd = true;
            return;
        }

        int count = CountAdjacentMines(x, y);
        _buttons[x, y].Text = count > 0 ? count.ToString() : "";
        _buttons[x, y].Disabled = true;
        _buttons[x, y].Modulate = Color.White;

        if (count == 0)
        {
            RevealEmptyTiles(x, y);
        }

        CheckWinCondition();
    }

    private void RevealEmptyTiles(int x, int y)
    {
        for (int dx = -1; dx <= 1; dx++)
            for (int dy = -1; dy <= 1; dy++)
            {
                int nx = x + dx;
                int ny = y + dy;
                if (nx >= 0 && ny >= 0 && nx < GridSize && ny < GridSize && !_revealed[nx, ny])
                {
                    OnTileClicked(nx, ny);
                }
            }
    }

    private void RevealAllMines()
    {
        for (int y = 0; y < GridSize; y++)
            for (int x = 0; x < GridSize; x++)
            {
                if (_mines[x, y])
                {
                    _buttons[x, y].Text = "💣";
                    _buttons[x, y].Modulate = Color.DarkRed;
                }
            }
    }

    private int CountAdjacentMines(int x, int y)
    {
        int count = 0;
        for (int dx = -1; dx <= 1; dx++)
            for (int dy = -1; dy <= 1; dy++)
            {
                int nx = x + dx;
                int ny = y + dy;
                if (nx >= 0 && ny >= 0 && nx < GridSize && ny < GridSize && _mines[nx, ny])
                    count++;
            }
        return count;
    }

    private void ToggleFlagMode()
    {
        _flagMode = !_flagMode;
        ToggleFlagButton.Text = _flagMode ? "Режим: Флажок" : "Режим: Открыть";
    }

    private void CheckWinCondition()
    {
        for (int y = 0; y < GridSize; y++)
            for (int x = 0; x < GridSize; x++)
            {
                if (!_mines[x, y] && !_revealed[x, y])
                    return;
            }
        // if (_comp != null)
        //     _comp.Dirty();

        // Победа
        // _stopwatch.Stop
        _gameEnd = true;
        RevealAllMines();
        GameStatusLabel.Text = "✓ Победа! Все мины разминированы.";

        // TODO: Доделать запись результатов
        // var nameUser = _comp?.LastOpenedBy ?? "Unknow";
        // var record = new MinesweeperRecord
        // {
        //     Difficulty = _difficulties[DifficultySelect.SelectedId].name,
        //     TimeSeconds = (float)_stopwatch.Elapsed.TotalSeconds,
        //     EntityName = nameUser
        // };
        // // Сохраняем локально для демонстрации
        // _records.Add(record);
        // _boundUserInterface.SendMessage(new MinesweeperWinMessage(_difficulties[DifficultySelect.SelectedId].name, (float)_stopwatch.Elapsed.TotalSeconds));
        // if (_comp != null)
        //     _comp.Dirty();
        // UpdateRecordsDisplay();
    }

    // public void LoadRecords(List<MinesweeperRecord> records, EntityUid uid, MinesweeperComponent component, BoundUserInterface boundUserInterface)
    // {
    //     _records = records;
    //     _boundUserInterface = boundUserInterface;
    //     _uid = uid;
    //     _comp = component;
    // }

    // private void UpdateRecordsDisplay()
    // {
    //     _recordListLabel.Text = string.Join("\n", _records.Select(r => r.ToString()));
    // }
}
