- type: entity
  name: Papaver somniferum
  parent: FoodProduceBase
  id: ADTFoodPapaverSomniferum
  description: A flower which extracts used in making medicine. And narcotics.
  components:
  - type: FlavorProfile
    flavors:
      - Bitter
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 16
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Toxin
          Quantity: 4
        - ReagentId: ADTOpium
          Quantity: 10
  - type: Sprite
    sprite: ADT/Objects/Specific/Hydroponics/papaver_somniferum.rsi
  - type: Produce
    seedId: ADTPapaverSomniferum
  - type: Extractable
    grindableSolutionName: food
  - type: Tag
    tags:
    - Flower

- type: entity
  name: strawberry
  parent: ProduceSliceBase
  id: ADTFoodStrawberry
  description: berry - the symbol of summer.
  components:
  - type: Sprite
    sprite: ADT/Objects/Specific/Hydroponics/strawberry.rsi
    state: produce
  - type: FlavorProfile
    flavors:
      - ADTStrawberryFlavor
  - type: Produce
    seedId: ADTStrawberry
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 9
        reagents:
        - ReagentId: Nutriment
          Quantity: 5
        - ReagentId: Vitamin
          Quantity: 4
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: ADTJuiceStrawberry
        Quantity: 10
  - type: Tag
    tags:
    - Fruit
