using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.ADT.Roadmap;

[GenerateTypedNameReferences]
public sealed partial class RoadmapWindow : DefaultWindow
{
    public RoadmapWindow()
    {
        RobustXamlLoader.Load(this);
        var msg = new FormattedMessage();
        var currentYear = System.DateTime.Now.Year;

        msg.AddMarkupOrThrow($"[font size=24]ДОРОЖНАЯ КАРТА [bold]{currentYear}[/bold][/font]");
        Header.SetMessage(msg);
    }
}
