using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;

namespace Content.Client.ADT.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class ClothingColorWindow : FancyWindow
{
    public event Action<Color?>? OnColorChanged;

    public ClothingColorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Picker.OnColorChanged += color => OnColorChanged?.Invoke(color);
        ColorCloseButton.OnPressed += _ => Close();
    }

    public void SetDummy(EntityUid dummy)
    {
        Picker.SetDummy(dummy);
    }

    public void SetColor(Color color)
    {
        Picker.SetColor(color);
    }
}