using System.Linq;
using Content.Client.Stylesheets;
using Content.Shared.ADT.TTS;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.ADT.TTS;

[GenerateTypedNameReferences]
public sealed partial class TTSTab : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly Content.Client.ADT.Sponsors.SponsorManager _adtSponsors = default!;
    [Dependency] private readonly Robust.Client.Player.IPlayerManager _players = default!;

    public event Action<string>? OnVoiceSelected;
    public event Action<string>? OnPreviewRequested;

    private List<TTSVoicePrototype> _allVoices = new();
    private readonly List<TTSVoicePrototype> _filteredVoices = new();
    private string? _selectedVoiceId;

    public TTSTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UpdateResults();
        SearchEdit.OnTextChanged += OnSearchChanged;

        _adtSponsors.Updated += UpdateResults;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            _adtSponsors.Updated -= UpdateResults;
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        UpdateResults();
    }

    private void UpdateResults()
    {
        VoicesGrid.RemoveAllChildren();
        _filteredVoices.Clear();

        var searchText = SearchEdit.Text.ToLowerInvariant();

        foreach (var voice in _allVoices)
        {
            if (string.IsNullOrEmpty(searchText) ||
                voice.Name.ToLowerInvariant().Contains(searchText) ||
                voice.ID.ToLowerInvariant().Contains(searchText))
            {
                _filteredVoices.Add(voice);
            }
        }

        foreach (var voice in _filteredVoices)
        {
            var canSelectVoice = CanUseVoice(voice);

            var voiceContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };

            var selectButton = new Button
            {
                Text = voice.Name,
                ToolTip = canSelectVoice ? voice.ID : Loc.GetString("humanoid-profile-editor-voice-tooltip-sponsoronly"),
                HorizontalExpand = true,
                Disabled = !canSelectVoice,
                StyleClasses = { StyleClass.ButtonOpenRight },
            };

            if (voice.ID == _selectedVoiceId)
                selectButton.AddStyleClass(StyleClass.Negative);

            selectButton.OnPressed += _ =>
            {
                if (canSelectVoice)
                    OnVoiceSelected?.Invoke(voice.ID);
            };

            var previewButton = new Button
            {
                Text = Loc.GetString("humanoid-profile-editor-voice-play"),
                MinWidth = 30,
                ToolTip = Loc.GetString("humanoid-profile-editor-voice-tooltip-play"),
                StyleClasses = { StyleClass.ButtonOpenLeft },
            };

            previewButton.OnPressed += _ => OnPreviewRequested?.Invoke(voice.ID);

            voiceContainer.AddChild(selectButton);
            voiceContainer.AddChild(previewButton);

            VoicesGrid.AddChild(voiceContainer);
        }

        ResultsLabel.Text = Loc.GetString("humanoid-profile-editor-voice-match",
            ("filtered", _filteredVoices.Count), ("all", _allVoices.Count));
    }

    private bool CanUseVoice(TTSVoicePrototype voice)
    {
        if (!voice.SponsorOnly)
            return true;

        return _adtSponsors.IsTtsVoiceAllowed(_players.LocalSession, voice.ID);
    }

    public void UpdateControls(HumanoidCharacterProfile? profile, Sex sex, ProtoId<SpeciesPrototype> species)
    {
        if (profile == null)
            return;

        _selectedVoiceId = profile.Voice;

        _allVoices = _prototypeManager
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(o => o.RoundStart && HumanoidCharacterProfile.CanHaveVoice(o, sex, species))
            .OrderBy(o => o.Name)
            .ToList();

        UpdateResults();
    }

    public void SetSelectedVoice(string voiceId)
    {
        _selectedVoiceId = voiceId;
        UpdateResults();
    }
}
