- type: job
  id: ADTBattleShipNavigatorKMT
  name: job-name-navigator-kmt
  description: job-description-navigator-kmt
  playTimeTracker: JobADTBattleShipNavigatorKMT
  requirements:
    - !type:SpeciesRequirement
      inverted: false
      species:
      - Human
    - !type:OverallPlaytimeRequirement
      time: 72000 #20 hrs 
  startingGear: ADTBattleShipNavigatorKMTGear
  icon: "JobIconNavigatorKMT"
  supervisors: job-supervisors-kmt-commander
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Engineering
  - External
  - Atmospherics
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - KMT
    - type: FriendlyFire
      enabled: true
    - type: FriendlyFireToggleable

- type: startingGear
  id: ADTBattleShipNavigatorKMTGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetERTSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ADTBaseUplinkBOBERT
  storage:
    back:
    - BoxSurvivalEngineering
    - BoxZiptie
    - CrowbarRed
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
