- type: job
  id: ADTBattleShipPilotKMT
  name: job-name-pilot-kmt
  description: job-description-pilot-kmt
  playTimeTracker: JobADTBattleShipPilotKMT
  requirements:
    - !type:SpeciesRequirement
      inverted: false
      species:
      - Human
    - !type:OverallPlaytimeRequirement
      time: 72000 #20 hrs 
  startingGear: ADTBattleShipPilotKMTGear
  icon: "JobIconPilotKMT"
  supervisors: job-supervisors-kmt-gunner
  canBeAntag: false
  overrideConsoleVisibility: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Engineering
  - External
  - Atmospherics
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - KMT
    - type: FriendlyFire
      enabled: true
    - type: FriendlyFireToggleable

- type: startingGear
  id: ADTBattleShipPilotKMTGear
  equipment:
    jumpsuit: ADTShipBattleClothingUniformPilotKMT
    back: ADTShipBattleClothingBlackBackpackJetKMT
    shoes: ADTShipBattleClothingShoesBootsMagFleet
    # head: ADTShipBattleClothingHeadHatGunnerTSF
    eyes: ClothingEyesGlassesMeson
    gloves: ADTShipBattleClothingHandsGlovesGunnerBlack
    outerClothing: ADTShipBattleClothingOuterHardsuitPilotKMT
    id: ADTShipBattleDogtagPilotKMT
    ears: ADTShipBattleClothingHeadsetPilotKMT
    belt: ADTShipBattleClothingBeltWarbelt
    # pocket1: DoubleEmergencyOxygenTankFilled
    # pocket2: ADTBaseUplinkBOBERT
    underwearb: ADTClothingUnderwearBottomBoxersWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksBlack
  storage:
    back:
    - BoxSurvivalEngineering
    - CrowbarRed
    - SpaceCash500
    - ADTShipBattleClothingHeadHelmetHardsuitPilotKMT
