- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - Atlas
  # - Bagel
  # - Box
  # - Cog
  # - Cluster
  # - Core
  # - Fland
  # - Marathon
  # - Meta
  # - Oasis
  # - Omega
  # - Origin
  # - Saltern
  # - Packed
  # - Reach
  # - Train
# adt_maps
  # - ADT_Astra в комментерии до ремапа
  - ADT_Frontier
  # - ADT_FrontierHalloween
  # - ADT_TrainHalloween
  # - ADT_SalternHalloween
  - ADT_Pie
  - ADT_Avrit
  - ADT_Bagel
  - ADT_Box
  - ADT_Cluster
  - ADT_Cluster_Legacy
  # - ADT_Core #В рамках уменьшения числа карт
  # - ADT_Fland #В рамках уменьшения числа карт
  - ADT_kilo
  - ADT_Marathon
  # - ADT_Meta
  # - ADT_Origin
  - ADT_Saltern
  # - ADT_Packed #В рамках уменьшения числа карт
  # - ADT_Train #В рамках уменьшения числа карт
  - ADT_Delta
  # - ADT_Oasis удалён чтоб жизнь малиной не казалась
  - ADT_Gemini
  - ADT_Aspid
  # - ADT_Moose #В рамках уменьшения числа карт
  # - ADT_Alley до ремонта
