- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - Atlas
  # - Bagel
  # - Box
  # - Cog
  # - Cluster
  # - Core
  # - Fland
  # - Marathon
  # - Meta
  # - Oasis
  # - Omega
  # - Origin
  # - Saltern
  # - Packed
  # - Reach
  # - Train

# ADT Maps Базовые Актуальные
  - ADT_Bagel
  - ADT_Box
  - ADT_Cluster
  # - ADT_Cluster_Legacy
  - ADT_Gemini
  # - ADT_Fland
  - ADT_Marathon
  # - ADT_Meta
  # - ADT_Saltern
  # - ADT_Packed
  # - ADT_Aspid

# SD maps Актуальные

  - SD_Radiance

# ADT Maps Выведенные на переработку
  # - ADT_Avrit требуется декорваксизация
  # - ADT_Alley до ремонта
  # - ADT_Astra в комментерии до ремапа
  # - ADT_Core #В рамках уменьшения числа карт
  # - ADT_Meta
  # - ADT_Moose #В рамках уменьшения числа карт
  # - ADT_Oasis удалён чтоб жизнь малиной не казалась
  # - ADT_Origin
  # - ADT_Packed #В рамках уменьшения числа карт
  # - ADT_Train #В рамках уменьшения числа карт
  # - ADT_Delta Выведена из-за наличия Кербероса

# ADT Halloween (Не забудьте отключить обычные)
  # - ADT_TrainHalloween
  # - ADT_SalternHalloween

# ADT NewYear (Не забудьте отключить обычные)
  # - ADT_AspidNewYear
  # - ADT_BagelNewYear
  # - ADT_BoxNewYear
  # - ADT_Cluster_LegacyNewYear
  # - ADT_DeltaNewYear
  # - ADT_GeminiNewYear
  # - ADT_PieNewYear
  # - ADT_SalternNewYear
