- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - Atlas
  # - Bagel
  # - Box
  # - Cog
  # - Cluster
  # - Core
  # - Fland
  # - Marathon
  # - Meta
  # - Oasis
  # - Omega
  # - Origin
  # - Saltern
  # - Packed
  # - Reach
  # - Train
# adt_maps
  # - ADT_Astra в комментерии до ремапа
  - ADT_FrontierHalloween
  - ADT_TrainHalloween
  - ADT_SalternHalloween
  - ADT_Avrit
  - ADT_Bagel
  - ADT_Box
  - ADT_Cluster
  - ADT_Core
  - ADT_Fland
  - ADT_Marathon
  - ADT_Meta
  - ADT_Origin
  # - ADT_Saltern - до конца хеллоуинских дней
  - ADT_Packed
  # - ADT_Train - до конца хеллоуинских дней
  - ADT_Delta
  # - ADT_Oasis удалён чтоб жизнь малиной не казалась
  - ADT_Gemini
  - ADT_Aspid
  - ADT_Moose
  # - ADT_Alley до ремонта
