- type: job
  id: Zookeeper
  name: job-name-zookeeper
  description: job-description-zookeeper
  playTimeTracker: JobZookeeper
  startingGear: ZookeeperGear
  icon: "JobIconZookeeper"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MonkeyDay
    prototype: MonkeyCubeBox
  #ADT-Tweak-Start
  - !type:AddSpeciesComponentSpecial
    species: IPC
    components:
      - type: BorgChassis
        maxModules: 1
        moduleWhitelist:
          tags:
          - BorgModuleGeneric
          - BorgModuleService
        ipc: true
  #ADT-Tweak-End

- type: startingGear
  id: ZookeeperGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSafari
    head: ClothingHeadSafari
    shoes: ClothingShoesColorWhite
    id: ZookeeperPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ZookeeperChameleonOutfit
  job: Zookeeper
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterColorLightBrown
    neck: ClothingNeckScarfStripedBrown
    belt: ClothingBeltStorageWaistbag
    gloves: ClothingHandsGlovesColorBrown

