using Content.Client.ADT.Discord;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class DiscordLinkWindow : DefaultWindow
{
    public static bool HasLinkedDiscord { get; private set; }

    [Dependency] private readonly IClipboardManager _clipboard = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly DiscordIdManager _discordIdManager = default!;
    [Dependency] private readonly IUriOpener _uriOpener = default!;

    private string? _discordId;
    private string? _discordUsername;
    private bool _isLinked = false;

    public DiscordLinkWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (_discordIdManager.TryGetDiscordId(out var discordId))
        {
            _discordId = discordId;
            _isLinked = true;
        }

        if (_discordIdManager.TryGetDiscordUsername(out var discordUsername))
        {
            _discordUsername = discordUsername;
        }

        UpdateStatus();

        CopyUidButton.OnPressed += _ =>
        {
            var uid = _player.LocalSession?.UserId.ToString() ?? "UNKNOWN";
            _clipboard.SetText(uid);
        };

        OpenDiscordButton.OnPressed += _ =>
        {
            var url = "https://discord.com/channels/901772674865455115/1351213738774237184";
            _uriOpener.OpenUri(url);
        };

        CopyInstructionButton.OnPressed += _ =>
        {
            // TODO: Можно вывести подсказку пользователю о копировании
            if (InstructionText.Text != null)
                _clipboard.SetText(InstructionText.Text);
            else
                _clipboard.SetText("");
        };
    }

    private void UpdateStatus()
    {
        HasLinkedDiscord = _isLinked;

        if (_isLinked)
        {
            var uid = _player.LocalSession?.UserId.ToString() ?? "UNKNOWN";
            var icName = _player.LocalPlayer?.Name ?? "Неизвестно";

            var message = new FormattedMessage();
            message.AddMarkupOrThrow(
                $"[color=green]✓ Вы успешно привязали Discord![/color]\n" +
                $"Имя: [color=lightblue]{_discordUsername}[/color] ([color=gray]{_discordId}[/color])\n" +
                $"UID: [color=yellow]{uid}[/color]\n" +
                $"Никнейм: [color=orange]{icName}[/color]");

            SuccessRichText.SetMessage(message);

            InstructionContainer.Visible = false;
            SuccessContainer.Visible = true;
        }
        else
        {
            var instructionMessage = new FormattedMessage();
            instructionMessage.AddMarkupOrThrow(
                "[color=white]Чтобы привязать Discord:[/color]\n" +
                "1. Скопируйте ваш UID.\n" +
                "2. Перейдите в канал Discord [color=yellow]https://discord.com/channels/901772674865455115/1351213738774237184[/color].\n" +
                "3. В дискорд канале нажмите кнопку `Привязать аккаунт` и туда введите свой UID."
            );

            InstructionText.SetMessage(instructionMessage);

            InstructionContainer.Visible = true;
            SuccessContainer.Visible = false;
        }
    }
}
