
using Content.Shared.Preferences;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.ADT.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class QuirkPanel : Control
{
    public QuirkPanel(HumanoidCharacterProfile profile, TraitPrototype proto)
    {
        RobustXamlLoader.Load(this);
        var color = Color.LightGray;
        switch (proto.Cost)
        {
            case > 0:
                color = Color.LightGreen;
                break;
            case < 0:
                color = Color.LightCoral;
                break;
        }

        string cost = proto.Cost > 0 ? (-proto.Cost).ToString() : $"+{-proto.Cost}";
        Label.SetMessage(FormattedMessage.FromUnformatted($"{Loc.GetString(proto.Name)}. {cost} оч."), null, color);
        DescLabel.SetMessage(FormattedMessage.FromUnformatted(Loc.GetString(proto.Description?.ToString() ?? "а?")));
        Panel.Button.Text = Loc.GetString(profile.TraitPreferences.Contains(proto.ID) ? "quirks-window-remove" : "quirks-window-add");
    }
}
