using System.Linq;
using System.Numerics;
using Content.Client.Corvax.Sponsors;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;

namespace Content.Client.ADT.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class SpeciesWindow : FancyWindow
{
    public event Action<ProtoId<SpeciesPrototype>>? ChooseAction;

    public HumanoidCharacterProfile Profile;
    private readonly IEntityManager _entityManager;
    private readonly IPrototypeManager _proto;

    public SpeciesWindow(HumanoidCharacterProfile profile, IPrototypeManager proto, IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        Profile = profile;
        _entityManager = entMan;
        _proto = proto;
        foreach (var item in _proto.EnumeratePrototypes<SpeciesPrototype>().Where(x => x.RoundStart))
        {
            var button = new Button()
            {
                HorizontalExpand = true,
                Text = Loc.GetString(item.Name),
            };
            SpeciesContainer.AddChild(button);
        }
    }

    private void SelectSpecies(ProtoId<SpeciesPrototype> protoId)
    {
        var proto = _proto.Index(protoId);
        var mob = _entityManager.Spawn(proto.Prototype);
        Mob.SetEntity(mob);
    }
}
