using System.Numerics;
using Content.Client.Message;
using Content.Client.RichText;
using Content.Client.UserInterface.RichText;
using Content.Shared.MassMedia.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Utility;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NewsReaderUiFragment : BoxContainer
{
    public event Action? OnNextButtonPressed;
    public event Action? OnPrevButtonPressed;
    public event Action? OnNotificationSwithPressed;

    // ADT-Tweak: комментарии к новостям
    public event Action<string>? OnCommentSubmitted;

    private bool _hasArticle;
    private bool _commentsVisible;
    private const int MinCommentsHeight = 70;
    private const int MaxCommentsHeight = 400;

    public NewsReaderUiFragment()
    {
        RobustXamlLoader.Load(this);

        Next.OnPressed += _ => OnNextButtonPressed?.Invoke();
        Prev.OnPressed += _ => OnPrevButtonPressed?.Invoke();
        NotificationSwitch.OnPressed += _ => OnNotificationSwithPressed?.Invoke();

        CommentsButton.OnPressed += _ => ToggleComments();
        CommentsSplitter.OnDragged += delta => AdjustCommentsHeight(delta);

        CommentInput.OnTextChanged += args =>
        {
            // ADT-Tweak: ограничение длины комментария
            if (args.Text.Length > 200)
                CommentInput.Text = args.Text[..200];

            CommentSendButton.Disabled = string.IsNullOrWhiteSpace(CommentInput.Text);
        };
        CommentInput.OnTextEntered += _ => SubmitComment();
        CommentSendButton.OnPressed += _ => SubmitComment();
    }

    private void SubmitComment()
    {
        if (!_hasArticle || string.IsNullOrWhiteSpace(CommentInput.Text))
            return;

        var content = CommentInput.Text.Trim();
        if (content.Length == 0)
            return;

        OnCommentSubmitted?.Invoke(content);
        CommentInput.Text = string.Empty;
        CommentSendButton.Disabled = true;
    }

    private void ToggleComments()
    {
        _commentsVisible = !_commentsVisible;
        CommentsPanel.Visible = _commentsVisible;
        CommentsSplitter.Visible = _commentsVisible;
    }

    private void AdjustCommentsHeight(float delta)
    {
        var newHeight = CommentsPanel.MinHeight + delta;
        CommentsPanel.MinHeight = Math.Clamp(newHeight, MinCommentsHeight, MaxCommentsHeight);
    }

    public void UpdateState(NewsArticle article, int targetNum, int totalNum, bool notificationOn)
    {
        PageNum.Visible = true;
        PageText.Visible = true;
        ShareTime.Visible = true;
        Author.Visible = true;
        CommentsButton.Visible = true;
        _hasArticle = true;

        var commentCount = article.Comments?.Count ?? 0;
        CommentsButton.Text = Loc.GetString("news-read-ui-comments-button",
            ("count", commentCount));
        CommentsPanel.Visible = _commentsVisible;
        CommentsSplitter.Visible = _commentsVisible;

        PageName.Text = article.Title;
        PageText.SetMessage(FormattedMessage.FromMarkupPermissive(article.Content), UserFormattableTags.BaseAllowedTags);

        PageNum.Text = $"{targetNum}/{totalNum}";

        NotificationSwitch.Text = Loc.GetString(notificationOn ? "news-read-ui-notification-on" : "news-read-ui-notification-off");

        var shareTime = article.ShareTime.ToString(@"hh\:mm\:ss");
        ShareTime.SetMarkup(Loc.GetString("news-read-ui-time-prefix-text") + " " + shareTime);

        var author = Loc.GetString("news-read-ui-author-prefix") + " " + (article.Author ?? Loc.GetString("news-read-ui-no-author"));
        Author.SetMessage(FormattedMessage.FromMarkupPermissive(author), UserFormattableTags.BaseAllowedTags);

        Prev.Disabled = targetNum <= 1;
        Next.Disabled = targetNum >= totalNum;

        UpdateComments(article.Comments);
    }

    public void UpdateEmptyState(bool notificationOn)
    {
        PageNum.Visible = false;
        PageText.Visible = false;
        ShareTime.Visible = false;
        Author.Visible = false;
        CommentsButton.Visible = false;
        CommentsPanel.Visible = false;
        CommentsSplitter.Visible = false;
        _hasArticle = false;

        PageName.Text = Loc.GetString("news-read-ui-not-found-text");

        NotificationSwitch.Text = Loc.GetString(notificationOn ? "news-read-ui-notification-on" : "news-read-ui-notification-off");

        CommentsList.RemoveAllChildren();
    }

    private void UpdateComments(List<NewsComment>? comments)
    {
        CommentsList.RemoveAllChildren();

        if (comments == null || comments.Count == 0)
        {
            CommentsList.AddChild(new Label()
            {
                Text = Loc.GetString("news-read-ui-comment-no-comments"),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 4),
            });
            return;
        }

        for (var idx = 0; idx < comments.Count; idx++)
        {
            var comment = comments[idx];
            var row = new PanelContainer()
            {
                HorizontalExpand = true,
            };

            var inner = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(4, 2),
            };

            var authorLabel = new Label()
            {
                Text = (comment.Author ?? Loc.GetString("news-read-ui-no-author")) + " (" + comment.ShareTime.ToString(@"hh\:mm\:ss") + ")",
                StyleClasses = { "LabelSmall" },
                HorizontalExpand = true,
                Modulate = new Color(0.62f, 0.72f, 0.85f),
            };
            var contentLabel = new Label()
            {
                Text = comment.Content,
                HorizontalExpand = true,
            };

            inner.AddChild(authorLabel);
            inner.AddChild(contentLabel);
            row.AddChild(inner);
            row.StyleClasses.Add(idx % 2 == 0 ? "PanelBackgroundBaseDark" : "PanelBackgroundLight");

            CommentsList.AddChild(row);
        }

        CommentsScroll.InvalidateMeasure();
        if (CommentsList.Parent is ScrollContainer scroll)
            scroll.SetScrollValue(new Vector2(0, float.MaxValue));
    }
}

/// <summary>
///     ADT-Tweak: thin draggable strip used to resize the comments section.
/// </summary>
public sealed class CommentsSplitterControl : Control
{
    public event Action<float>? OnDragged;

    private bool _dragging;
    private float _lastGlobalY;

    public CommentsSplitterControl()
    {
        MouseFilter = MouseFilterMode.Stop;
        DefaultCursorShape = CursorShape.VResize;
        MinSize = new Vector2(0, 6);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);
        if (args.Function == EngineKeyFunctions.UIClick)
        {
            _dragging = true;
            _lastGlobalY = args.PointerLocation.Position.Y / UIScale;
        }
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);
        if (args.Function == EngineKeyFunctions.UIClick)
            _dragging = false;
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);
        if (!_dragging)
            return;

        var delta = args.GlobalPosition.Y - _lastGlobalY;
        _lastGlobalY = args.GlobalPosition.Y;
        OnDragged?.Invoke(delta);
    }
}
