- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 28800 #8 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 #5 hrs
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Resomi
      - Vox
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigmedicGear
  equipment:
    ears: ClothingHeadsetBrigmedic
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol

