- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 28800 #8 hrs #ADT-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 #5 hrs #ADT-RoleTime
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigmedicGear
  equipment:
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
#    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
#    socks: ClothingUnderwearSocksNormal
#  underweart: ClothingUnderwearTopBraWhite # Sirena-Underwear
#  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
#  innerClothingSkirt: ADTClothingUniformSkirtBrigmedicTurtleneck
#  satchel: ClothingBackpackSatchelBrigmedicFilled
#  duffelbag: ClothingBackpackDuffelBrigmedicFilled

