using Robust.Client.AutoGenerated;
using Content.Shared.Atmos;
using Robust.Client.UserInterface.XAML;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Microsoft.VisualBasic;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Supermatter;

[GenerateTypedNameReferences]
public sealed partial class SupermatterControlWindow : FancyWindow
{
	public SupermatterControlWindow()
	{
    RobustXamlLoader.Load(this);
    IoCManager.InjectDependencies(this);
	}


	public void UpdatePercents(string procent)
	{
		ProcentsLabel.Text = $"Целостность: {procent}%";
	}

	public void UpdateGases(Dictionary<Gas, float> gases)
	{
		GasesLabel.Text = "";
		foreach (var gas in gases)
		{
			GasesLabel.Text = GasesLabel.Text + gas + "\n";
		}
	}
}