using System.Linq;
using System.Numerics;
using Content.Client.Resources;
using Content.Shared.ADT.MedicalAssembler;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Content.Shared.Kitchen;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.ADT.MedicalAssembler;

[GenerateTypedNameReferences]
public sealed partial class MedicalAssemblerMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly Texture _lockTexture;

    private float MaxCustomVolume => _state?.MaxCustomVolume ?? 5f;

    private readonly List<string> _recipeIds = new();
    private MedicalAssemblerUpdateState? _state;
    private string? _selectedRecipeId;
    private readonly Dictionary<string, FixedPoint2> _customRecipe = new();
    private string _customStyleId = "medipen";
    public event Action<string>? OnCraftPressed;
    public event Action? OnEjectPressed;
    public event Action<MedicalAssemblerCreateCustomMessage>? OnCreateCustomPressed;

    private static readonly (string Id, string LocKey)[] MedipenStyles =
    {
        ("medipen", "medical-assembler-style-medipen"),
        ("firstaid", "medical-assembler-style-firstaid"),
        ("hypovolemic", "medical-assembler-style-hypovolemic"),
        ("stimpen", "medical-assembler-style-stimpen"),
        ("oxapen", "medical-assembler-style-oxapen"),
        ("bicpen", "medical-assembler-style-bicpen"),
        ("dexpen", "medical-assembler-style-dexpen"),
    };

    public MedicalAssemblerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entMan.System<SpriteSystem>();
        _lockTexture = _resourceCache.GetTexture(new ResPath("/Textures/Interface/VerbIcons/lock-red.svg.192dpi.png"));

        RecipeList.OnItemSelected += args =>
        {
            _selectedRecipeId = _recipeIds[args.ItemIndex];
            UpdateDetails();
        };
        CraftButton.OnPressed += _ =>
        {
            if (_selectedRecipeId is { } id)
                OnCraftPressed?.Invoke(id);
        };
        EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();

        CustomStyleButton.OnItemSelected += args =>
        {
            CustomStyleButton.SelectId(args.Id);
            _customStyleId = args.Id < MedipenStyles.Length ? MedipenStyles[args.Id].Id : _customStyleId;
        };
        CreateCustomButton.OnPressed += _ => SendCreateCustom();
        foreach (var (id, locKey) in MedipenStyles)
            CustomStyleButton.AddItem(Loc.GetString(locKey));

        Tabs.SetTabTitle(0, Loc.GetString("medical-assembler-recipes-tab"));
        Tabs.SetTabTitle(1, Loc.GetString("medical-assembler-custom-tab"));
    }

    public void UpdateState(MedicalAssemblerUpdateState state)
    {
        _state = state;
        _recipeIds.Clear();
        RecipeList.Clear();

        foreach (var entry in state.Recipes)
        {
            _recipeIds.Add(entry.RecipeId);
            var recipe = _proto.Index<FoodRecipePrototype>(entry.RecipeId);
            var name = GetEntityName(recipe.Result);
            var icon = entry.Unlocked ? GetResultIcon(recipe) : _lockTexture;
            var iconScale = entry.Unlocked ? 1f : 0.5f;

            RecipeList.AddItem(name, icon, selectable: entry.Unlocked, iconScale: iconScale);
        }

        MaterialsLabel.Text = state.Materials.Length == 0
            ? Loc.GetString("medical-assembler-no-materials")
            : string.Join(", ", state.Materials.Select(entry => $"{GetEntityName(entry.PrototypeId)} ×{entry.Count}"));

        BeakerLabel.Text = state.HasBeaker
            ? Loc.GetString("medical-assembler-beaker-volume", ("volume", state.BeakerVolume), ("capacity", state.BeakerCapacity))
            : Loc.GetString("medical-assembler-no-beaker");

        Tabs.SetTabVisible(1, state.CustomTabUnlocked);
        RefreshCustomUi();

        if (_selectedRecipeId != null && !state.Recipes.Any(entry => entry.RecipeId == _selectedRecipeId))
            _selectedRecipeId = null;

        if (_selectedRecipeId == null)
        {
            RecipeList.ClearSelected();
            ResultNameLabel.Text = "";
            ResultIcon.Texture = null;
            RequirementsLabel.SetMessage("");
            UnlockStatusLabel.Text = "";
            CraftButton.Disabled = true;
        }
        else
        {
            UpdateDetails();
        }
    }

    private void UpdateDetails()
    {
        if (_selectedRecipeId is not { } id
            || _state is not { } state
            || !_proto.TryIndex<FoodRecipePrototype>(id, out var recipe))
        {
            return;
        }

        var entry = state.Recipes.FirstOrDefault(recipeEntry => recipeEntry.RecipeId == id);
        var unlocked = entry?.Unlocked ?? false;

        ResultNameLabel.Text = GetEntityName(recipe.Result);
        ResultIcon.Texture = unlocked ? GetResultIcon(recipe) : _lockTexture;
        UnlockStatusLabel.Text = unlocked
            ? Loc.GetString("medical-assembler-unlocked")
            : Loc.GetString("medical-assembler-locked");
        UnlockStatusLabel.FontColorOverride = unlocked ? new Color(0.43f, 1f, 0.65f) : new Color(1f, 0.48f, 0.48f);

        var markup = new System.Text.StringBuilder();
        markup.AppendLine("[bold]" + Loc.GetString("medical-assembler-requires") + "[/bold]");

        if (state.ReagentMultiplier < 1f)
        {
            var percent = MathF.Round((1f - state.ReagentMultiplier) * 100f);
            markup.AppendLine(Loc.GetString("medical-assembler-reagent-discount", ("percent", percent)));
        }

        foreach (var (solidProtoId, quantity) in recipe.IngredientsSolids)
        {
            var have = CountMaterial(state, solidProtoId);
            var ok = have >= quantity;
            markup.AppendLine($"- {GetEntityName(solidProtoId)} ×{quantity} " +
                              (ok
                                  ? $"[color=#6DFFA5]({have})[/color]"
                                  : $"[color=#FF7A7A]({have})[/color]"));
        }

        foreach (var (reagentId, quantity) in recipe.IngredientsReagents)
        {
            var required = GetRequiredReagent(quantity, state.ReagentMultiplier);
            var have = GetReagentAmount(state, reagentId);
            var ok = have >= required;
            var name = GetReagentName(reagentId);
            var available = Loc.GetString("medical-assembler-available", ("volume", have));
            markup.AppendLine($"- {name} {required}u " +
                              (ok
                                  ? $"[color=#6DFFA5]({available})[/color]"
                                  : $"[color=#FF7A7A]({available})[/color]"));
        }

        if (FormattedMessage.TryFromMarkup(markup.ToString(), out var message))
            RequirementsLabel.SetMessage(message);

        var canCraft = unlocked && recipe.IngredientsSolids.All(entry2 => CountMaterial(state, entry2.Key) >= entry2.Value)
            && recipe.IngredientsReagents.All(entry2 => GetReagentAmount(state, entry2.Key) >= GetRequiredReagent(entry2.Value, state.ReagentMultiplier));
        CraftButton.Disabled = !canCraft;
    }

    private Texture? GetResultIcon(FoodRecipePrototype recipe)
    {
        if (!_proto.TryIndex<EntityPrototype>(recipe.Result, out var resultProto))
            return null;

        return _spriteSystem.Frame0(resultProto);
    }

    private string GetEntityName(string protoId)
    {
        if (!_proto.TryIndex<EntityPrototype>(protoId, out var proto))
            return protoId;

        return proto.Name;
    }

    private string GetReagentName(string reagentId)
    {
        if (!_proto.TryIndex<ReagentPrototype>(reagentId, out var reagent))
            return reagentId;

        return reagent.LocalizedName;
    }

    private static FixedPoint2 CountMaterial(MedicalAssemblerUpdateState state, string protoId)
    {
        var total = FixedPoint2.Zero;
        foreach (var entry in state.Materials)
        {
            if (entry.PrototypeId == protoId)
                total += entry.Count;
        }

        return total;
    }

    private static FixedPoint2 GetReagentAmount(MedicalAssemblerUpdateState state, string reagentId)
    {
        var total = FixedPoint2.Zero;
        if (state.BeakerReagents == null)
            return total;

        foreach (var reagent in state.BeakerReagents)
        {
            if (reagent.Reagent.Prototype == reagentId)
                total += reagent.Quantity;
        }

        return total;
    }

    #region Кастомная вкладка

    private void RefreshCustomUi()
    {
        var styleIdx = Array.FindIndex(MedipenStyles, style => style.Id == _customStyleId);
        if (styleIdx >= 0)
            CustomStyleButton.SelectId(styleIdx);

        RebuildCustomBeakerList();
        UpdateCustomRecipeList();
        UpdateCustomStatus();
    }

    private void RebuildCustomBeakerList()
    {
        CustomBeakerList.RemoveAllChildren();
        if (_state is not { BeakerReagents: { } reagents })
            return;

        var total = GetCustomTotal();
        foreach (var reagent in reagents)
        {
            var available = reagent.Quantity - _customRecipe.GetValueOrDefault(reagent.Reagent.Prototype);
            if (available <= 0)
                continue;

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6 };
            var label = new Label
            {
                Text = $"{GetReagentName(reagent.Reagent.Prototype)} ({available}u)",
                HorizontalExpand = true,
            };
            var addButton = new Button
            {
                Text = "+1",
                MinSize = new Vector2(36, 0),
                Disabled = total >= MaxCustomVolume,
            };
            var reagentId = reagent.Reagent.Prototype;
            addButton.OnPressed += _ =>
            {
                if (GetCustomTotal() >= MaxCustomVolume)
                    return;

                _customRecipe[reagentId] = _customRecipe.GetValueOrDefault(reagentId) + FixedPoint2.New(1);
                RefreshCustomUi();
            };
            row.AddChild(label);
            row.AddChild(addButton);
            CustomBeakerList.AddChild(row);
        }
    }

    private void UpdateCustomRecipeList()
    {
        CustomRecipeList.RemoveAllChildren();
        foreach (var (reagentId, quantity) in _customRecipe)
        {
            if (quantity <= 0)
                continue;

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6 };
            var label = new Label
            {
                Text = $"{GetReagentName(reagentId)} — {quantity}u",
                HorizontalExpand = true,
            };
            var removeButton = new Button
            {
                Text = "-1",
                MinSize = new Vector2(36, 0),
            };
            removeButton.OnPressed += _ =>
            {
                var newQuantity = _customRecipe.GetValueOrDefault(reagentId) - FixedPoint2.New(1);
                if (newQuantity <= 0)
                    _customRecipe.Remove(reagentId);
                else
                    _customRecipe[reagentId] = newQuantity;

                RefreshCustomUi();
            };
            row.AddChild(label);
            row.AddChild(removeButton);
            CustomRecipeList.AddChild(row);
        }
    }

    private void UpdateCustomStatus()
    {
        if (_state == null)
            return;

        var total = GetCustomTotal();
        CustomTotalLabel.Text = Loc.GetString("medical-assembler-custom-total", ("volume", total), ("max", MaxCustomVolume));
        CustomTotalLabel.FontColorOverride = total > FixedPoint2.New(MaxCustomVolume) ? Color.Red : new Color(0.43f, 1f, 0.65f);

        // доступность: есть рецепт и все реагенты есть в мензурке
        var canCreate = total > 0 && total <= FixedPoint2.New(MaxCustomVolume) && _state.BeakerReagents != null;
        if (canCreate)
        {
            foreach (var (reagentId, quantity) in _customRecipe)
            {
                if (GetReagentAmount(_state, reagentId) < quantity)
                {
                    canCreate = false;
                    break;
                }
            }
        }

        CreateCustomButton.Disabled = !canCreate;
    }

    private FixedPoint2 GetCustomTotal()
    {
        var total = FixedPoint2.Zero;
        foreach (var quantity in _customRecipe.Values)
            total += quantity;

        return total;
    }

    private void SendCreateCustom()
    {
        if (_customRecipe.Count == 0)
            return;

        var reagents = new List<ReagentQuantity>();
        foreach (var (reagentId, quantity) in _customRecipe)
            reagents.Add(new ReagentQuantity(new ProtoId<ReagentPrototype>(reagentId), quantity));

        OnCreateCustomPressed?.Invoke(new MedicalAssemblerCreateCustomMessage("medipen", _customStyleId, reagents));
    }

    #endregion

    private static FixedPoint2 GetRequiredReagent(FixedPoint2 quantity, float multiplier)
    {
        return FixedPoint2.New(quantity.Float() * multiplier);
    }
}
