using System.Linq;
using Content.Shared.ADT.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class CreateGroupPopup : DefaultWindow
{
    private const int MaxNameLength = 32;

    private readonly List<(uint number, CheckBox box)> _memberBoxes = new();
    private uint _ownNumber;

    public event Action<string, bool, List<uint>>? OnGroupCreated;

    public CreateGroupPopup()
    {
        RobustXamlLoader.Load(this);

        ContentsContainer.Margin = new Thickness(3);

        CancelButton.OnPressed += _ => Close();
        CreateButton.OnPressed += _ => CreateGroup();

        NameInput.OnTextChanged += args =>
        {
            if (args.Text.Length > MaxNameLength)
                NameInput.Text = args.Text[..MaxNameLength];
            ValidateInputs();
        };

        PublicCheck.OnToggled += _ => ValidateInputs();
    }

    public void SetContacts(List<NanoChatRecipient>? contacts, uint ownNumber)
    {
        _memberBoxes.Clear();
        MembersList.RemoveAllChildren();
        _ownNumber = ownNumber;

        if (contacts == null)
            return;

        foreach (var contact in contacts.OrderBy(c => c.Name))
        {
            if (contact.Number == _ownNumber)
                continue;

            var box = new CheckBox()
            {
                Text = $"{contact.Name} (#{contact.Number:D4})",
                HorizontalExpand = true,
            };
            box.OnToggled += _ => ValidateInputs();
            MembersList.AddChild(box);
            _memberBoxes.Add((contact.Number, box));
        }
    }

    public void ClearInputs()
    {
        NameInput.Text = string.Empty;
        PublicCheck.Pressed = false;
        foreach (var (_, box) in _memberBoxes)
            box.Pressed = false;
        ValidateInputs();
    }

    private void ValidateInputs()
    {
        CreateButton.Disabled = string.IsNullOrWhiteSpace(NameInput.Text);
    }

    private void CreateGroup()
    {
        var name = NameInput.Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
            return;

        var members = _memberBoxes
            .Where(m => m.box.Pressed)
            .Select(m => m.number)
            .ToList();

        OnGroupCreated?.Invoke(name, PublicCheck.Pressed, members);
        Close();
    }

}
