using System.Linq;
using System.Numerics;
using Content.Shared.ADT.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class GroupMembersPopup : DefaultWindow
{
    private uint _groupNumber;
    private uint _ownNumber;
    private bool _isOwner;

    public uint GroupNumber => _groupNumber;

    public event Action<uint>? OnInvite;
    public event Action<uint>? OnKick;
    public event Action? OnLeave;
    public event Action? OnDelete;

    public GroupMembersPopup()
    {
        RobustXamlLoader.Load(this);

        ContentsContainer.Margin = new Thickness(3);

        LeaveButton.OnPressed += _ =>
        {
            OnLeave?.Invoke();
            Close();
        };
        DeleteGroupButton.OnPressed += _ =>
        {
            OnDelete?.Invoke();
            Close();
        };
        InviteButton.OnPressed += _ => Invite();
        InviteNumberInput.OnTextChanged += args =>
        {
            if (args.Text.Length > 4)
                InviteNumberInput.Text = args.Text[..4];

            var digits = string.Concat(args.Text.Where(char.IsDigit));
            if (digits != args.Text)
                InviteNumberInput.Text = digits;

            InviteButton.Disabled = !uint.TryParse(InviteNumberInput.Text, out _);
        };
        InviteNumberInput.OnTextEntered += _ => Invite();
    }

    public void SetGroup(NanoChatGroup group, uint ownNumber)
    {
        _groupNumber = group.Number;
        _ownNumber = ownNumber;
        _isOwner = group.Owner == ownNumber;

        GroupNameLabel.Text = group.Name + "  (" +
            Loc.GetString("nano-chat-group-members-count", ("count", group.Members.Count)) + ")";
        DeleteGroupButton.Visible = _isOwner;
        LeaveButton.Text = Loc.GetString(_isOwner ? "nano-chat-group-leave-owner" : "nano-chat-group-leave");

        MembersList.RemoveAllChildren();
        foreach (var member in group.Members.OrderBy(m => m.Name))
        {
            var nameLabel = new Label()
            {
                Text = member.Name + (string.IsNullOrEmpty(member.JobTitle) ? "" : $" ({member.JobTitle})") + $" #{member.Number:D4}",
                HorizontalExpand = true,
                ClipText = true,
            };

            var panel = new PanelContainer()
            {
                HorizontalExpand = true,
            };
            var row = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };
            row.AddChild(nameLabel);

            if (_isOwner && member.Number != ownNumber)
            {
                var kickButton = new Button()
                {
                    Text = Loc.GetString("nano-chat-group-kick"),
                    MinSize = new Vector2(80, 28),
                    MaxSize = new Vector2(80, 28),
                    Margin = new Thickness(4, 0, 0, 0),
                };
                kickButton.AddStyleClass("OpenBoth");
                var memberNumber = member.Number;
                kickButton.OnPressed += _ =>
                {
                    OnKick?.Invoke(memberNumber);
                    Close();
                };
                row.AddChild(kickButton);
            }

            panel.AddChild(row);
            MembersList.AddChild(panel);
        }

        InviteNumberInput.Text = string.Empty;
        InviteButton.Disabled = true;
    }

    private void Invite()
    {
        if (!uint.TryParse(InviteNumberInput.Text, out var number))
            return;

        if (number == _ownNumber)
            return;

        OnInvite?.Invoke(number);
        InviteNumberInput.Text = string.Empty;
        InviteButton.Disabled = true;
    }
}
