using System.Linq;
using System.Numerics;
using Content.Shared.ADT.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatLookupView : PanelContainer
{
    private const int MaxGroupNameLength = 32;

    private List<NanoChatRecipient>? _contacts;
    private readonly HashSet<uint> _selectedMembers = new();
    private HashSet<uint> _recipientNumbers = new();
    private uint _ownNumber;
    private bool _atRecipientLimit;
    private bool _createMode;

    public NanoChatLookupView()
    {
        RobustXamlLoader.Load(this);

        CreateGroupButton.OnPressed += _ => EnterCreateMode();
        CancelCreateButton.OnPressed += _ => ExitCreateMode();
        ConfirmCreateButton.OnPressed += _ => CreateGroup();
        GroupNameInput.OnTextChanged += args =>
        {
            if (args.Text.Length > MaxGroupNameLength)
                GroupNameInput.Text = args.Text[..MaxGroupNameLength];
            UpdateConfirmButton();
        };
        SearchInput.OnTextChanged += _ => UpdateContactList(_contacts, _ownNumber);
    }

    public event Action<string, bool, List<uint>>? OnCreateGroupRequest;
    public event Action<NanoChatRecipient>? OnStartChat;

    public void UpdateContactList(NanoChatUiState state)
    {
        _contacts = state.Contacts;
        _ownNumber = state.OwnNumber;
        _recipientNumbers = new HashSet<uint>(state.Recipients.Keys);
        _atRecipientLimit = state.MaxRecipients <= state.Recipients.Count + state.Groups.Count;
        UpdateContactList(_contacts, _ownNumber);
    }

    /// <summary>Перерисовывает список контактов с учётом поиска и режима создания группы.</summary>
    private void UpdateContactList(List<NanoChatRecipient>? contacts, uint ownNumber)
    {
        ContactsList.RemoveAllChildren();

        if (contacts == null)
        {
            ContactsList.AddChild(new Label() { Text = Loc.GetString("nano-chat-look-up-no-server") });
            return;
        }

        var query = SearchInput.Text.Trim();
        var digits = string.Concat(query.Where(char.IsDigit));
        var filtered = contacts
            .Where(c => c.Number != ownNumber)
            .Where(c => MatchesQuery(c, query, digits))
            .OrderBy(c => c.Name)
            .ToList();

        if (filtered.Count == 0)
        {
            // Номер вне телефонной книги: подсказываем вместо молчаливого пустого списка.
            var hint = query.Length > 0 && digits.Length > 0
                ? Loc.GetString("nano-chat-search-number-not-found", ("number", digits))
                : Loc.GetString("nano-chat-search-no-results");
            ContactsList.AddChild(new Label()
            {
                Text = hint,
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 8),
            });
            return;
        }

        for (var idx = 0; idx < filtered.Count; idx++)
        {
            var contact = filtered[idx];
            var row = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };

            // Чекбокс выбора участника появляется только в режиме создания группы.
            if (_createMode)
            {
                var memberBox = new CheckBox()
                {
                    HorizontalExpand = false,
                    Margin = new Thickness(4, 0, 4, 0),
                    // Выбор переживает перерисовку (например, при вводе в поиск).
                    Pressed = _selectedMembers.Contains(contact.Number),
                };
                memberBox.OnToggled += _ =>
                {
                    if (memberBox.Pressed)
                        _selectedMembers.Add(contact.Number);
                    else
                        _selectedMembers.Remove(contact.Number);
                };
                row.AddChild(memberBox);
            }

            var nameLabel = new Label()
            {
                Text = contact.Name,
                HorizontalExpand = true,
                ClipText = true,
            };
            var numberLabel = new Label()
            {
                Text = $"#{contact.Number:D4}",
                HorizontalAlignment = HAlignment.Right,
                Margin = new Thickness(0, 0, 36, 0),
            };
            row.AddChild(nameLabel);
            row.AddChild(numberLabel);

            // В режиме создания кнопка «+» не нужна: строка выбирается чекбоксом.
            if (!_createMode)
            {
                var startChatButton = new Button()
                {
                    Text = "+",
                    HorizontalAlignment = HAlignment.Right,
                    MinSize = new Vector2(32, 32),
                    MaxSize = new Vector2(32, 32),
                    ToolTip = Loc.GetString("nano-chat-new-chat"),
                };
                startChatButton.AddStyleClass("OpenBoth");
                if (contact.Number == ownNumber ||
                    _recipientNumbers.Contains(contact.Number) ||
                    _atRecipientLimit)
                {
                    startChatButton.Disabled = true;
                }
                startChatButton.OnPressed += _ => OnStartChat?.Invoke(contact);
                row.AddChild(startChatButton);
            }

            var panel = new PanelContainer()
            {
                HorizontalExpand = true,
            };
            panel.AddChild(row);

            var styleClass = idx % 2 == 0 ? "PanelBackgroundBaseDark" : "PanelBackgroundLight";
            panel.StyleClasses.Add(styleClass);

            ContactsList.AddChild(panel);
        }
    }

    private static bool MatchesQuery(NanoChatRecipient contact, string query, string digits)
    {
        if (query.Length == 0)
            return true;

        // Совпадение по имени (без учёта регистра) или по номеру.
        if (contact.Name.Contains(query, StringComparison.OrdinalIgnoreCase))
            return true;

        return digits.Length > 0 && contact.Number.ToString().Contains(digits);
    }

    private void EnterCreateMode()
    {
        _createMode = true;
        CreateGroupPanel.Visible = true;
        CreateGroupButtons.Visible = false;
        ConfirmGroupButtons.Visible = true;
        GroupNameInput.Text = string.Empty;
        PublicCheck.Pressed = false;
        UpdateConfirmButton();
        UpdateContactList(_contacts, _ownNumber);
    }

    private void ExitCreateMode()
    {
        _createMode = false;
        _selectedMembers.Clear();
        CreateGroupPanel.Visible = false;
        CreateGroupButtons.Visible = true;
        ConfirmGroupButtons.Visible = false;
        UpdateContactList(_contacts, _ownNumber);
    }

    private void UpdateConfirmButton()
    {
        ConfirmCreateButton.Disabled = string.IsNullOrWhiteSpace(GroupNameInput.Text);
    }

    private void CreateGroup()
    {
        var name = GroupNameInput.Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
            return;

        var members = _selectedMembers.ToList();

        OnCreateGroupRequest?.Invoke(name, PublicCheck.Pressed, members);
        ExitCreateMode();
    }
}
