using System.Numerics;
using Content.Shared.ADT.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatLookupView : PanelContainer
{
    public NanoChatLookupView()
    {
        RobustXamlLoader.Load(this);
    }

    public event Action<NanoChatRecipient>? OnStartChat;
    public event Action? OnCreateGroupRequest;

    public void UpdateContactList(NanoChatUiState state)
    {
        ContactsList.RemoveAllChildren();

        // Create group button
        var createGroupButton = new Button()
        {
            Text = Loc.GetString("nano-chat-create-group"),
            HorizontalExpand = true,
            StyleClasses = { "OpenBoth" },
            Margin = new Thickness(0, 0, 0, 4),
        };
        createGroupButton.OnPressed += _ => OnCreateGroupRequest?.Invoke();
        ContactsList.AddChild(createGroupButton);

        if (state.Contacts is not { } contacts)
        {
            ContactsList.AddChild(new Label() { Text = Loc.GetString("nano-chat-look-up-no-server") });
            return;
        }

        for (var idx = 0; idx < contacts.Count; idx++)
        {
            var contact = contacts[idx];
            var nameLabel = new Label()
            {
                Text = contact.Name,
                HorizontalAlignment = HAlignment.Left,
                HorizontalExpand = true
            };
            var numberLabel = new Label()
            {
                Text = $"#{contacts[idx].Number:D4}",
                HorizontalAlignment = HAlignment.Right,
                Margin = new Thickness(0, 0, 36, 0),
            };
            var startChatButton = new Button()
            {
                Text = "+",
                HorizontalAlignment = HAlignment.Right,
                MinSize = new Vector2(32, 32),
                MaxSize = new Vector2(32, 32),
                ToolTip = Loc.GetString("nano-chat-new-chat"),
            };
            startChatButton.AddStyleClass("OpenBoth");
            if (contact.Number == state.OwnNumber || state.Recipients.ContainsKey(contact.Number) || state.MaxRecipients <= state.Recipients.Count + state.Groups.Count)
            {
                startChatButton.Disabled = true;
            }
            startChatButton.OnPressed += _ => OnStartChat?.Invoke(contact);

            var panel = new PanelContainer()
            {
                HorizontalExpand = true,
            };
            var row = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };

            row.AddChild(nameLabel);
            row.AddChild(numberLabel);
            row.AddChild(startChatButton);
            panel.AddChild(row);

            var styleClass = idx % 2 == 0 ? "PanelBackgroundBaseDark" : "PanelBackgroundLight";
            panel.StyleClasses.Add(styleClass);

            ContactsList.AddChild(panel);
        }
    }
}
