- type: dungeonConfig
  id: Bunker
  data:
    colors:
      Decals: "#FFFFFFFF"
    entities:
      Cabling: CableApcExtension
      CornerWalls: WallReinforced
      Walls: WallSolid
    spawnGroups:
      #CornerClutter: BaseClutter
      Entrance: AirlockCentcomHatch
      EntranceFlank: ReinforcedWindow
      Junction: AirlockCentcomHatch
      WallMounts: ScienceLabsWalls
      Window: ReinforcedGirder
    tiles:
      FallbackTile: FloorGrayConcrete
    whitelists:
      Rooms:
        tags:
        - SalvageBunker
  layers:
  - !type:PrototypeDunGen
    proto: PlanetBase

- type: dungeonConfig
  id: Medicine
  generator: !type:PrefabDunGen
    roomWhitelist:
      - SalvageMedicine
    presets:
      - Bucket
      - Wow
      - SpaceShip
      - Tall
  postGeneration:
    - !type:CorridorPostGen
      width: 3

    - !type:DungeonEntrancePostGen
      count: 2

    - !type:RoomEntrancePostGen
      entities:
        - CableApcExtension
        - AirlockMedicalGlass

    - !type:EntranceFlankPostGen
      entities:
        - Grille
        - Window

    - !type:ExternalWindowPostGen
      entities:
        - Grille
        - Window

    - !type:WallMountPostGen
      spawns:
        # Posters
        - id: RandomPosterLegit
          orGroup: content
        - id: ExtinguisherCabinetFilled
          prob: 0.2
          orGroup: content
        - id: RandomPainting
          prob: 0.05
          orGroup: content
        - id: IntercomCommon
          prob: 0.1
          orGroup: content
        - id: DefibrillatorCabinetFilled
          prob: 0.1
          orGroup: content

    - !type:BoundaryWallPostGen
      tile: FloorSteel
      wall: WallSolid
      cornerWall: WallReinforced

    - !type:JunctionPostGen
      width: 1

    - !type:JunctionPostGen

    - !type:AutoCablingPostGen

    - !type:CorridorDecalSkirtingPostGen
      color: "#00d0ffd5"
      cardinalDecals:
        South: BrickTileWhiteLineS
        East: BrickTileWhiteLineE
        North: BrickTileWhiteLineN
        West: BrickTileWhiteLineW
      cornerDecals:
        SouthEast: BrickTileWhiteCornerSe
        SouthWest: BrickTileWhiteCornerSw
        NorthEast: BrickTileWhiteCornerNe
        NorthWest: BrickTileWhiteCornerNw
      pocketDecals:
        SouthWest: BrickTileWhiteInnerSw
        SouthEast: BrickTileWhiteInnerSe
        NorthWest: BrickTileWhiteInnerNw
        NorthEast: BrickTileWhiteInnerNe

- type: dungeonConfig
  id: Botany
  generator: !type:PrefabDunGen
    roomWhitelist:
      - SalvageBotany
    presets:
      - Bucket
      - Wow
      - SpaceShip
      - Tall
  postGeneration:
    - !type:CorridorPostGen
      width: 3

    - !type:DungeonEntrancePostGen
      count: 2

    - !type:RoomEntrancePostGen
      entities:
        - CableApcExtension
        - AirlockMedicalGlass

    - !type:EntranceFlankPostGen
      entities:
        - Grille
        - Window

    - !type:ExternalWindowPostGen
      entities:
        - Grille
        - Window

    - !type:WallMountPostGen
      spawns:
        # Posters
        - id: RandomPosterLegit
          orGroup: content
        - id: ExtinguisherCabinetFilled
          prob: 0.2
          orGroup: content
        - id: RandomPainting
          prob: 0.05
          orGroup: content
        - id: IntercomCommon
          prob: 0.1
          orGroup: content

    - !type:BoundaryWallPostGen
      tile: FloorConcrete
      wall: WallSolid
      cornerWall: WallReinforced

    - !type:JunctionPostGen
      width: 1

    - !type:JunctionPostGen

    - !type:AutoCablingPostGen
