using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.Administration.PlayersDashboard;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.Administration.UI.PlayersDashboard;

[GenerateTypedNameReferences]
public sealed partial class PlayersDashboardWindow : FancyWindow
{
    public PlayersDashboardWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(PlayersDashboardEuiState state)
    {
        TotalLabel.Text = state.Total.ToString();
        QueueLabel.Text = state.Queue.ToString();
        LobbyLabel.Text = state.Lobby.ToString();
        GhostsLabel.Text = state.Ghosts.ToString();
        AdminGhostsLabel.Text = state.AdminGhosts.ToString();
        InGameLabel.Text = state.InGame.ToString();
        OtherLabel.Text = state.Other.ToString();
        AdminsLabel.Text = state.Admins.ToString();
    }
}
