using Content.Client.ADT.PDA;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System.Numerics;

namespace Content.Client.PDA;

[Virtual]
[GenerateTypedNameReferences]
public partial class PdaWindow : BaseWindow
{

    public string? BorderColor
    {
        get => Background.ActualModulateSelf.ToHex();

        set => Background.ModulateSelfOverride = Color.FromHex(value, Color.White);
    }

    public string? AccentHColor
    {
        get => AccentH.ActualModulateSelf.ToHex();

        set
        {
            AccentH.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentH.Visible = value != null;
        }
    }

    public string? AccentVColor
    {
        get => AccentV.ActualModulateSelf.ToHex();

        set
        {
            AccentV.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentV.Visible = value != null;
        }
    }

    public PdaWindow()
    {
        RobustXamlLoader.Load(this);

        CloseButton.OnPressed += _ => Close();
        XamlChildren = ContentsContainer.Children;

        AccentH.Visible = false;
        AccentV.Visible = false;
    }

    /// <summary>
    /// ADT-Tweak: Dark CRT scanlines + chrome from secondary accent (screen stays monitor-dark).
    /// </summary>
    public void ApplyMonitorTheme(in PdaInteriorPalette palette)
    {
        ContentBackground.LightLine = palette.ScanLight;
        ContentBackground.DarkLine = palette.ScanDark;
        ContentBorder.ModulateSelfOverride = palette.Chrome;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}
