using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.ADT.Chat.UI;

[GenerateTypedNameReferences]
public sealed partial class CustomEmotesWindow : FancyWindow
{
    public event Action<string>? OnApply;

    public CustomEmotesWindow()
    {
        RobustXamlLoader.Load(this);

        HintLabel.SetMessage(Loc.GetString("adt-custom-emotes-hint"));
        EntriesEdit.Placeholder = new Rope.Leaf(Loc.GetString("adt-custom-emotes-placeholder"));

        EntriesEdit.OnTextChanged += _ => UpdateStatus();
        ApplyButton.OnPressed += _ => OnApply?.Invoke(Rope.Collapse(EntriesEdit.TextRope));
    }

    public void SetEntries(string raw)
    {
        EntriesEdit.TextRope = new Rope.Leaf(raw);
        UpdateStatus();
    }

    private void UpdateStatus()
    {
        var raw = Rope.Collapse(EntriesEdit.TextRope);
        var valid = CustomEmoteParser.Parse(raw).Count;
        var bad = CustomEmoteParser.CountInvalidLines(raw);

        StatusLabel.Text = bad == 0
            ? Loc.GetString("adt-custom-emotes-status", ("count", valid))
            : Loc.GetString("adt-custom-emotes-status-bad", ("count", valid), ("bad", bad));
    }
}
