using System.IO;
using System.Linq;
using System.Numerics;
using System.Threading;
using Content.Client.ADT.Lobby.UI;
using Content.Client.ADT.Traits.UI;
using Content.Client.Guidebook;
using System.Reflection;
using Content.Client.Humanoid;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Stylesheets;
using Content.Client.Sprite;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.ADT.CCVar;
using Content.Client.Corvax.Sponsors;
using Content.Shared.CCVar;
using Content.Shared.Clothing;
using Content.Shared.Corvax.CCCVars;
using Content.Shared.GameTicking;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Mobs;
using Content.Shared.Body;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Timer = Robust.Shared.Timing.Timer;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Robust.Shared.Toolshed.Errors;
using Robust.Shared.Utility;
using Direction = Robust.Shared.Maths.Direction;
using static Content.Client.Corvax.SponsorOnlyHelpers; // Corvax-Sponsors
using Content.Client.Corvax.TTS; // Corvax-TTS
using Content.Client.ADT.UserInterface.Controls;
using Content.Client.ADT.CharecterFlavor;
using Content.Shared.ADT.CharecterFlavor;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly IResourceManager _resManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;
        private readonly LobbyUIController _controller;
        private readonly IDynamicTypeFactory _factory;  // ADT SAI Custom
        [Dependency] private readonly DocumentParsingManager _parsingMan = default!;

        private readonly SpriteSystem _sprite;

        // CCvar.
        private int _maxNameLength;

        private TTSTab? _ttsTab; // Corvax-TTS

        /// <summary>
        /// If we're attempting to save.
        /// </summary>
        public event Action? Save;

        /// <summary>
        /// The character slot for the current profile.
        /// </summary>
        public int? CharacterSlot;

        /// <summary>
        /// The work in progress profile being edited.
        /// </summary>
        public HumanoidCharacterProfile? Profile;

        private Direction _previewRotation = Direction.North;

        private bool _isDirty;

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        private ISawmill _sawmill;

        private SpeciesWindow? _speciesWindow;  // ADT Species window


        private MarkingsViewModel _markingsModel = new();

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings,
            IDynamicTypeFactory factory)    // ADT SAI Custom
        {
            RobustXamlLoader.Load(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            _resManager = resManager;
            _requirements = requirements;
            _factory = factory; // ADT SAI Custom
            _controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _sprite = _entManager.System<SpriteSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);

            Markings.SetModel(_markingsModel);

            ImportButton.OnPressed += args =>
            {
                ImportProfile();
            };

            ExportButton.OnPressed += args =>
            {
                ExportProfile();
            };

            ExportImageButton.OnPressed += args =>
            {
                ExportImage();
            };

            OpenImagesButton.OnPressed += args =>
            {
                _resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            };

            ResetButton.OnPressed += args =>
            {
                SetProfile((HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
            };

            SaveButton.OnPressed += args =>
            {
                Save?.Invoke();
            };

            #region Left

            #region Name

            NameEdit.OnTextChanged += args => { SetName(args.Text); };
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            NameRandomize.OnPressed += args => RandomizeName();
            RandomizeEverythingButton.OnPressed += args => { RandomizeEverything(); };
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");

            #endregion Name

            #region Appearance

            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));

            #region Sex

            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex)args.Id);
            };

            #endregion Sex

            #region Age

            AgeEdit.OnTextChanged += args =>
            {
                if (!int.TryParse(args.Text, out var newAge))
                    return;

                SetAge(newAge);
            };

            #endregion Age

            #region Gender

            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int)Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int)Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int)Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int)Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender)args.Id);
            };

            #endregion Gender


            // ADT Barks Start
            #region Voice

            if (configurationManager.GetCVar(ADTCCVars.BarksEnabled))
            {
                BarksContainer.Visible = true;
                InitializeBarks();
            }

            #endregion
            // ADT Barks End

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                OnSkinColorOnValueChanged();
            };

            // ADT Species Window start
            NewSpeciesButton.OnToggled += args =>
            {
                if (Profile == null)
                    return;

                _speciesWindow?.Dispose();

                if (!args.Pressed)
                {
                    _speciesWindow = null;
                }
                else
                {
                    _speciesWindow = new(
                        Profile,
                        prototypeManager,
                        entManager,
                        _controller,
                        _resManager,
                        _parsingMan);

                    _speciesWindow.OpenCenteredLeft();
                    var oldProfile = Profile.Clone();
                    _speciesWindow.ChooseAction += args =>
                    {
                        SetSpecies(args);
                        OnSkinColorOnValueChangedKeepColor(oldProfile);
                        _speciesWindow?.Dispose();
                        _speciesWindow = null;
                        var name1 = _prototypeManager.Index(Profile?.Species ?? "Human").Name;
                        NewSpeciesButton.Text = Loc.GetString(name1);
                        NewSpeciesButton.Pressed = false;
                        this.SetDefaultLanguages();
                    };
                    _speciesWindow.OnClose += () =>
                    {
                        NewSpeciesButton.Pressed = false;
                        _speciesWindow = null;
                    };
                }
            };
            // ADT Species Window end

            #region Skin

            Skin.OnValueChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
            _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV
            _rgbSkinColorSelector.OnColorChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            #endregion

            #region SpawnPriority

            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"), (int)value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference)args.Id);
            };

            #endregion SpawnPriority

            #region Eyes

            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithEyeColor(newColor));
                _markingsModel.SetOrganEyeColor(Profile.Appearance.EyeColor);
                ReloadProfilePreview();
            };

            #endregion Eyes

            #endregion Appearance

            // ADT Languages start
            #region Languages
            RefreshLanguages();
            #endregion Languages
            // ADT Languages end
            #region Jobs

            /*TabContainer.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-jobs-tab")); // ADT Languages tweak
            Вынесено в HumanoidProfileEditor в регионе InvokeRefresh, чтобы не накладывало названия друг на друга*/

            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-stay-in-lobby-button"),
                (int)PreferenceUnavailableMode.StayInLobby);
            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-spawn-as-overflow-button",
                              ("overflowJob", Loc.GetString(SharedGameTicker.FallbackOverflowJobName))),
                (int)PreferenceUnavailableMode.SpawnAsOverflow);

            PreferenceUnavailableButton.OnItemSelected += args =>
            {
                PreferenceUnavailableButton.SelectId(args.Id);
                Profile = Profile?.WithPreferenceUnavailable((PreferenceUnavailableMode)args.Id);
                SetDirty();
            };

            _jobCategories = new Dictionary<string, BoxContainer>();

            RefreshAntags();
            RefreshJobs();

            #endregion Jobs

            /*TabContainer.SetTabTitle(4, Loc.GetString("humanoid-profile-editor-antags-tab"));   // ADT Languages tweak
            Вынесено в HumanoidProfileEditor в регионе InvokeRefresh, чтобы не накладывало названия друг на друга*/

            RefreshTraits();
            Traits.OnTraitsChanged += OnTraitsSelectionChanged; // ADT-Tweak new Traits

            /*TabContainer.SetTabTitle(5, Loc.GetString("humanoid-profile-editor-traits-tab")); // Corvax-TTS-Edit
            Вынесено в HumanoidProfileEditor в регионе InvokeRefresh, чтобы не накладывало названия друг на друга*/

            #region Markings

            /*TabContainer.SetTabTitle(6, Loc.GetString("humanoid-profile-editor-markings-tab")); // ADT Languages tweak
            Вынесено в HumanoidProfileEditor в регионе InvokeRefresh, чтобы не накладывало названия друг на друга*/

            _markingsModel.MarkingsChanged += (_, _) => OnMarkingChange();
            _markingsModel.MarkingsReset += OnMarkingChange;

            #endregion Markings

            RefreshFlavorText();

            RefreshVoiceTab(); // Corvax-TTS

            // ADT-Tweak start. Корректно вставляем вкладки для кастомизации персонажа и их названия
            #region InvokeRefresh
            bool ttsIsEnabled = _cfgManager.GetCVar(CCCVars.TTSEnabled);
            int valueTTSEnable = ttsIsEnabled ? 1 : 0; // Переменная для перехода на следующий индекс вкладки, если ТТС включён, чтобы их названия не накладывались друг на друга

            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));
            if (ttsIsEnabled)
                TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-voice-tab"));

            TabContainer.SetTabTitle(1 + valueTTSEnable, Loc.GetString("humanoid-profile-editor-languages-tab"));
            TabContainer.SetTabTitle(2 + valueTTSEnable, Loc.GetString("humanoid-profile-editor-jobs-tab"));
            TabContainer.SetTabTitle(3 + valueTTSEnable, Loc.GetString("humanoid-profile-editor-antags-tab"));
            TabContainer.SetTabTitle(4 + valueTTSEnable, Loc.GetString("humanoid-profile-editor-traits-tab"));
            TabContainer.SetTabTitle(5 + valueTTSEnable, Loc.GetString("humanoid-profile-editor-markings-tab"));

            if (_allowFlavorText)
                TabContainer.SetTabTitle(TabContainer.ChildCount - 1, Loc.GetString("humanoid-profile-editor-flavortext-tab"));

            #endregion
            // ADT-Tweak end.

            #region Dummy

            SpriteRotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCw();
                SetPreviewRotation(_previewRotation);
            };
            SpriteRotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCcw();
                SetPreviewRotation(_previewRotation);
            };

            #endregion Dummy

            #endregion Left

            ShowClothes.OnToggled += args =>
            {
                ReloadPreview();
            };

            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;

            UpdateSpeciesGuidebookIcon();
            ReloadPreview();
            IsDirty = false;
        }

        // Corvax-TTS-Start
        #region Voice

        private void RefreshVoiceTab()
        {
            if (!_cfgManager.GetCVar(CCCVars.TTSEnabled))
                return;

            _ttsTab = new TTSTab();
            var children = new List<Control>();
            foreach (var child in TabContainer.Children)
                children.Add(child);

            TabContainer.RemoveAllChildren();

            for (int i = 0; i < children.Count; i++)
            {
                if (i == 1) // Set the tab to the 2nd place.
                {
                    TabContainer.AddChild(_ttsTab);
                }
                TabContainer.AddChild(children[i]);
            }

            /*TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-voice-tab"));
            Вынесено в HumanoidProfileEditor в регионе InvokeRefresh, чтобы не накладывало названия друг на друга*/

            _ttsTab.OnVoiceSelected += voiceId =>
            {
                SetVoice(voiceId);
                _ttsTab.SetSelectedVoice(voiceId);
            };

            _ttsTab.OnPreviewRequested += voiceId =>
            {
                _entManager.System<TTSSystem>().RequestPreviewTTS(voiceId);
            };
        }

        private void UpdateTTSVoicesControls()
        {
            if (Profile is null || _ttsTab is null)
                return;

            _ttsTab.UpdateControls(Profile, Profile.Sex, Profile.Species); //ADT-tweak: добавлена раса
            _ttsTab.SetSelectedVoice(Profile.Voice);
        }

        #endregion
        // Corvax-TTS-End

        private void SetDirty()
        {
            // If it equals default then reset the button.
            if (Profile == null || _preferencesManager.Preferences?.SelectedCharacter.MemberwiseEquals(Profile) == true)
            {
                IsDirty = false;
                return;
            }

            // TODO: Check if profile matches default.
            IsDirty = true;
        }

        /// <summary>
        /// Reloads the entire dummy entity for preview.
        /// </summary>
        /// <remarks>
        /// This is expensive so not recommended to run if you have a slider.
        /// </remarks>
        private void ReloadPreview()
        {
            if (Profile == null)
                return;

            SpriteView.LoadPreview(Profile, JobOverride, ShowClothes.Pressed);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        /// <summary>
        /// Resets the profile to the defaults.
        /// </summary>
        public void ResetToDefault()
        {
            SetProfile(
                (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                _preferencesManager.Preferences?.SelectedCharacterIndex);
        }

        /// <summary>
        /// Sets the editor to the specified profile with the specified slot.
        /// </summary>
        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            CharacterSlot = slot;
            IsDirty = false;
            JobOverride = null;

            UpdateNameEdit();
            UpdateFlavorTextEdit();
            UpdateSexControls();
            UpdateGenderControls();
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();
            UpdateTTSVoicesControls(); // Corvax-TTS
            UpdateBarkVoicesControls(); // ADT Barks

            RefreshLanguages(); // ADT Languages
            RefreshAntags();
            RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            RefreshTraits();
            RefreshFlavorText();
            ReloadPreview();

            if (Profile != null)
            {
                PreferenceUnavailableButton.SelectId((int)Profile.PreferenceUnavailable);
            }
        }

        /// <summary>
        /// A slim reload that only updates the entity itself and not any of the job entities, etc.
        /// </summary>
        private void ReloadProfilePreview()
        {
            if (Profile == null || !_entManager.EntityExists(SpriteView.PreviewDummy))
                return;

            _entManager.System<SharedVisualBodySystem>().ApplyProfileTo(SpriteView.PreviewDummy, Profile);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        //ADT-tweak-start: Юрл для хэдшота
        private CancellationTokenSource? _headshotRequestCts;
        private string? _lastHeadshotUrl;

        private async void OnHeadshotUrlChange(string content)
        {
            if (Profile is null)
                return;

            var url = content.Trim();

            if (url == _lastHeadshotUrl)
                return;

            _lastHeadshotUrl = url;

            Profile = Profile.WithHeadshotUrl(url);
            SetDirty();

            // Отменяем предыдущий запрос
            _headshotRequestCts?.Cancel();
            _headshotRequestCts?.Dispose();
            _headshotRequestCts = null;

            _headshotRequestCts = new CancellationTokenSource();

            var cts = _headshotRequestCts.Token;

            try
            {
                // Debounce: ждём 500мс перед запросом
                await Timer.Delay(500, cts);
                OnHeadshotPreviewRequestedDelayed(url);
            }
            catch (OperationCanceledException)
            {
                // Запрос отменён — это нормально
            }
        }

        private void OnHeadshotPreviewRequestedDelayed(string url)
        {
            if (Profile is null)
                return;

            if (!_entManager.EntityExists(SpriteView.PreviewDummy))
                return;

            var flavor = _entManager.EnsureComponent<CharacterFlavorComponent>(SpriteView.PreviewDummy);
            flavor.FlavorText = Profile.FlavorText ?? string.Empty;
            flavor.HeadshotUrl = url;

            var controller = UserInterfaceManager.GetUIController<CharacterFlavorUiController>();
            controller.OpenPreviewMenu(SpriteView.PreviewDummy);

            // Попросить сервер скачать и прислать картинку для предпросмотра хэдшота.
            if (!string.IsNullOrWhiteSpace(url))
            {
                _entManager.System<CharecterFlavorSystem>().RequestHeadshotPreview(url);
            }
        }

        private void OnFlavorPreviewRequested()
        {
            if (Profile is null)
                return;

            if (!_entManager.EntityExists(SpriteView.PreviewDummy))
                return;

            var flavor = _entManager.EnsureComponent<CharacterFlavorComponent>(SpriteView.PreviewDummy);
            flavor.FlavorText = Profile.FlavorText ?? string.Empty;
            flavor.HeadshotUrl = Profile.HeadshotUrl ?? string.Empty;

            var controller = UserInterfaceManager.GetUIController<CharacterFlavorUiController>();
            controller.OpenPreviewMenu(SpriteView.PreviewDummy);

            // Попросить сервер скачать и прислать картинку для предпросмотра хэдшота.
            if (!string.IsNullOrWhiteSpace(Profile.HeadshotUrl))
            {
                _entManager.System<CharecterFlavorSystem>().RequestHeadshotPreview(Profile.HeadshotUrl);
            }
        }
        //ADT-tweak-end

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _loadoutWindow?.Dispose();
            _loadoutWindow = null;

            _headshotRequestCts?.Cancel();
            _headshotRequestCts = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();
            _entManager.DeleteEntity(SpriteView.PreviewDummy);
            SpriteView.PreviewDummy = EntityUid.Invalid;
        }

        // Corvax-TTS-Start
        private void SetVoice(string newVoice)
        {
            Profile = Profile?.WithVoice(newVoice);
            IsDirty = true;
        }
        // Corvax-TTS-End
        // ADT Barks start
        private void SetBarkProto(string prototype)
        {
            Profile = Profile?.WithBarkProto(prototype);
            ReloadPreview();
            SetDirty();
        }

        private void SetBarkPitch(float pitch)
        {
            Profile = Profile?.WithBarkPitch(Math.Clamp(pitch, _cfgManager.GetCVar(ADTCCVars.BarksMinPitch), _cfgManager.GetCVar(ADTCCVars.BarksMaxPitch)));
            ReloadPreview();
            SetDirty();
        }

        private void SetBarkMinVariation(float variation)
        {
            Profile = Profile?.WithBarkMinVariation(Math.Clamp(variation, _cfgManager.GetCVar(ADTCCVars.BarksMinDelay), Profile.Bark.MaxVar));
            ReloadPreview();
            SetDirty();
        }

        private void SetBarkMaxVariation(float variation)
        {
            Profile = Profile?.WithBarkMaxVariation(Math.Clamp(variation, Profile.Bark.MinVar, _cfgManager.GetCVar(ADTCCVars.BarksMaxDelay)));
            ReloadPreview();
            SetDirty();
        }
        // ADT Barks end

        private void UpdateSaveButton()
        {
            SaveButton.Disabled = Profile is null || !IsDirty;
            ResetButton.Disabled = Profile is null || !IsDirty;
        }

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction) ((int) direction % 4 * 2);
        }

        // ADT Species Window start
        private void OnSkinColorOnValueChangedKeepColor(HumanoidCharacterProfile previous)
        {
            if (Profile is null) return;

            var skinTypeStr = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
            var color = previous.Appearance.SkinColor;

            switch (skinTypeStr)
            {
                case "HumanToned":
                    // Просто оставить предыдущий цвет
                    break;

                case "Hues":
                    color = AdjustBrightness(color, 0.9f, 1.0f);
                    break;

                case "TintedHues":
                    color = AdjustSaturation(color, 0.1f);
                    break;

                case "VoxFeathers":
                    color = ClampColor(color, 29f / 360f, 174f / 360f, 0.2f, 0.88f, 0.36f, 0.55f);
                    break;

                default:
                    // Если неизвестный тип, оставляем как есть
                    break;
            }

            _rgbSkinColorSelector.Color = color;
            ReloadProfilePreview();
        }

        // Простейшие вспомогательные функции:
        private Color AdjustBrightness(Color color, float min, float max)
        {
            var hsv = Color.ToHsv(color);
            hsv.Z = Math.Clamp(hsv.Z, min, max);
            return Color.FromHsv(hsv);
        }

        private Color AdjustSaturation(Color color, float maxSaturation)
        {
            var hsv = Color.ToHsv(color);
            hsv.Y = Math.Min(hsv.Y, maxSaturation);
            return Color.FromHsv(hsv);
        }

        private Color ClampColor(Color color, float minH, float maxH, float minS, float maxS, float minV, float maxV)
        {
            var hsv = Color.ToHsv(color);
            hsv.X = Math.Clamp(hsv.X, minH, maxH);
            hsv.Y = Math.Clamp(hsv.Y, minS, maxS);
            hsv.Z = Math.Clamp(hsv.Z, minV, maxV);
            return Color.FromHsv(hsv);
        }
        // ADT Species Window end
    }
}
