    using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Client.UserInterface.Systems.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

        private const string DiscordUrl = "https://discord.gg/nPrxW7Yb6b";

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(ParallaxBackground, LayoutPreset.Wide);
            SetAnchorPreset(VignetteDuty, LayoutPreset.Wide);
            SetAnchorPreset(CharacterSetupState, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
            LobbyBackground.SetMarkup(Loc.GetString("lobby-state-background-no-background-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            CharacterSetupButton_Duty.OnPressed += _ => SwitchState(LobbyGuiState.CharacterSetup);

            // LocalDuty — ObserveButton теперь LobbyAnimatedButton
            ObserveButton.OnPressed += _ => _consoleHost.ExecuteCommand("observe");

            // LocalDuty — Руководство
            GuideButton.OnPressed += _ => UserInterfaceManager.GetUIController<GuidebookUIController>().ToggleGuidebook();

            // LocalDuty — Дискорд
            DiscordButton.OnPressed += _ => IoCManager.Resolve<IUriOpener>().OpenUri(DiscordUrl);

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    // LocalDuty — CharacterSetupState теперь полноэкранный слой,
                    // правую панель скрываем чтобы не мешала
                    CharacterSetupState.Visible = true;
                    RightSide.Visible = false;

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();
                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}