using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Content.Client.Corvax.Sponsors;
using Robust.Shared.Configuration;
using Content.Shared.ADT.CCVar;
using Content.Client.ADT.Discord;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly SponsorsManager _sponsorsManager = default!;
        [Dependency] private readonly DiscordIdManager _discordIdManager = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        private float _updateTimer;
        private bool _panelUpdate = false;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            SetAnchorPreset(ShowInterfaceContainer, LayoutPreset.Wide); // ADT-Tweak
            SetAnchorPreset(ShowInterface, LayoutPreset.BottomLeft); // ADT-Tweak

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            // ADT-Tweak-Start
            HideInterface.OnPressed += _ => {
                SwitchState(LobbyGuiState.ScreenSaver);
            };
            ShowInterface.OnPressed += _ => {
                SwitchState(LobbyGuiState.Default);
            };

            if (_cfg.GetCVar(ADTCCVars.ShowLobbyPanelEnable))
            {
                LobbyPanelLeftTop.Visible = true;
                _panelUpdate = true;
                UpdateButtons();
            }
            else
            {
                _panelUpdate = false;
                LobbyPanelLeftTop.Visible = false;
            }
            // ADT-Tweak-End
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;
            // ADT-Tweak-Start
            ShowInterfaceContainer.Visible = false;
            MainContainer.Visible = true;
            // ADT-Tweak-End

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;

                // ADT-Tweak-Start
                case LobbyGuiState.ScreenSaver:
                    ShowInterfaceContainer.Visible = true;
                    MainContainer.Visible = false;
                    break;
                // ADT-Tweak-End
            }
        }
        // ADT-Tweak-Start: Обновление кнопок
        protected override void FrameUpdate(FrameEventArgs args)
        {
            if (!_panelUpdate)
                return;

            base.FrameUpdate(args);

            // Обновляем раз в 5 секунд
            _updateTimer += args.DeltaSeconds;
            if (_updateTimer > 5.0f)
            {
                _updateTimer = 0;
                UpdateButtons();
            }
        }
        // ADT-Tweak-End
        // ADT-Tweak-Start: Покраска кнопок в зависимости от спонсорки и привязки к Discord
        private void UpdateButtons()
        {
            // Проверяем статус спонсорки
            if (_sponsorsManager?.TryGetInfo(out var sponsorInfo) == true && sponsorInfo != null)
            {
                UpdateSponsorButtonColor(true, sponsorInfo.Tier);
            }
            else
            {
                UpdateSponsorButtonColor(false, null);
            }
            SponsorInfoButton.Visible = true;

            // Проверяем статус Discord
            if (_discordIdManager?.TryGetDiscordId(out var discordId) == true && discordId != null)
            {
                UpdateDiscordLincButtonColor(true);
            }
            else
            {
                UpdateDiscordLincButtonColor(false);
            }
            DiscordLinkButton.Visible = true;
        }

        public void UpdateSponsorButtonColor(bool hasSponsor, int? sponsorTier)
        {
            if (SponsorInfoButton == null)
                return;

            SponsorInfoButton.ModulateSelfOverride = hasSponsor
                ? Color.FromHex("#1966ff")  // Синий
                : Color.FromHex("#AB3232"); // Красный

            SponsorInfoButton.Text = hasSponsor && sponsorTier != null
                ? $"Уровень спонсорства: {sponsorTier}"
                : "Уровень спонсорства: нет :(";
        }

        public void UpdateDiscordLincButtonColor(bool hasLincDiscord)
        {
            if (DiscordLinkButton == null)
                return;

            DiscordLinkButton.ModulateSelfOverride = hasLincDiscord
                ? Color.FromHex("#5da130")  // Зелёный
                : Color.FromHex("#AB3232"); // Красный

            DiscordLinkButton.Text = hasLincDiscord
                ? "Discord привязан"
                : "Привязать Discord";
        }
        // ADT-Tweak-end

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup,
            ScreenSaver, // ADT-Tweak
        }
    }
}
