using System.Numerics;          //ADT-Tweak - New PDA UI
using Content.Client.ADT.PDA;   //ADT-Tweak- New PDA UI
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;   //ADT-Tweak- New PDA UI
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWindow : BaseWindow   //ADT-Tweak - New PDA UI - BaseWindow for MedTek
{
    private static readonly Color DefaultSecondary = Color.FromHex("#447987"); //ADT-Tweak

    public HealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
        //ADT-Tweak Start
        CloseButton.OnPressed += _ => Close();
        ApplyMonitorTheme(DefaultSecondary);
        //ADT-Tweak End
    }

    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        HealthAnalyzer.Populate(msg.State);
    }

    //ADT-Tweak Start: New UI Theme
    private void ApplyMonitorTheme(Color secondary)
    {
        var palette = PdaInteriorTheme.FromSecondary(secondary);
        ContentBackground.LightLine = palette.ScanLight;
        ContentBackground.DarkLine = palette.ScanDark;
        ContentBorder.ModulateSelfOverride = palette.Chrome;
        Background.ModulateSelfOverride = Color.White;
        HealthAnalyzer.ApplyDividerColor(palette.Divider);
        HealthAnalyzer.ApplyMonitorTextTheme(palette.Fg);
    }
    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
    //ADT-Tweak End

}
