- type: entity
  name: mutant
  id: BaseMobMutant
  parent: [ SimpleMobBase, MobCombat ]
  abstract: true
  description: It looks so much like jelly. I wonder what it tastes like?
  components:
  - type: Sprite
    drawdepth: Mobs
    sprite: Mobs/Aliens/slimes.rsi
    layers:
    - map: [ "enum.DamageStateVisualLayers.Base" ]
      state: blue_adult_slime
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.30
        density: 80
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: MobThresholds
    thresholds:
      0: Alive
      120: Dead
  - type: MovementSpeedModifier
    baseWalkSpeed: 2
    baseSprintSpeed: 4
  - type: FootstepModifier
    footstepSoundCollection:
      path: /Audio/Effects/Footsteps/slime1.ogg
      params:
        volume: 3
  - type: Tag
    tags:
    - FootstepSound
    - DoorBumpOpener
  - type: Butcherable
    butcheringType: Knife
    spawned:
    - id: FoodMeatSlime
      amount: 2
  - type: Respirator
    damage:
      types:
        Asphyxiation: 0.2
    damageRecovery:
      types:
        Asphyxiation: -1.0
    maxSaturation: 15
  - type: Damageable
    damageContainer: Biological
    damageModifierSet: Slime
  - type: Bloodstream
    bloodReagent: Slime
    bloodlossDamage:
      types:
        Bloodloss:
          0.5
    bloodlossHealDamage:
      types:
        Bloodloss:
          -0.25
  - type: Barotrauma
    damage:
      types:
        Blunt: 0.45
  - type: Reactive
    groups:
      Flammable: [ Touch ]
      Extinguish: [ Touch ]
    reactions:
    - reagents: [ Water, SpaceCleaner ]
      methods: [ Touch ]
      effects:
      - !type:WashCreamPieReaction
    - reagents: [ Water ]
      methods: [ Touch ]
      effects:
      - !type:HealthChange
        scaleByQuantity: true
        damage:
          types:
            Heat: 0.15
      - !type:PopupMessage
        type: Local
        messages: [ "slime-hurt-by-water-popup" ]
        probability: 0.25
  - type: Body
    prototype: Slimes
    requiredLegs: 1
  - type: MeleeWeapon
    altDisarm: false
    soundHit:
        path: /Audio/Weapons/punch3.ogg
    angle: 0
    animation: WeaponArcPunch
    damage:
      types:
        Blunt: 6
        Structural: 4
        Caustic: 4
  - type: InteractionPopup
    successChance: 0.5
    interactSuccessString: petting-success-slimes
    interactFailureString: petting-failure-generic
  - type: Speech
    speechVerb: Slime
    speechSounds: Slime
  - type: TypingIndicator
    proto: slime
