using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.Guidebook.Ashwalkers;

[GenerateTypedNameReferences]
public sealed partial class GuideAshwalkerChip : PanelContainer
{
    public GuideAshwalkerChip()
    {
        RobustXamlLoader.Load(this);
    }

    public GuideAshwalkerChip(string text, Color accent) : this()
    {
        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = AshwalkerGuideColors.ChipBackground,
            BorderThickness = new Thickness(1),
            BorderColor = accent.WithAlpha(0.55f),
        };

        TextLabel.SetMarkupPermissive($"[color={AshwalkerGuideColors.ToMarkup(accent)}]{text}[/color]");
    }
}
