using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.ADT.Guidebook.Ashwalkers;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideAshwalkerLootEmbed : BoxContainer, IDocumentTag, ISearchableControl
{
    [Dependency] private ILogManager _logManager = default!;
    [Dependency] private IPrototypeManager _prototype = default!;

    private readonly ISawmill _sawmill;

    public GuideAshwalkerLootEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("guidebook.ashwalkers.loot");
        MouseFilter = MouseFilterMode.Stop;
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;

        if (!args.TryGetValue("Entity", out var id))
        {
            _sawmill.Error("Ashwalker loot embed is missing the Entity argument");
            return false;
        }

        if (!_prototype.TryIndex<EntityPrototype>(id, out var proto))
        {
            _sawmill.Error($"Unknown entity prototype \"{id}\"");
            return false;
        }

        args.TryGetValue("Guaranteed", out var guaranteed);
        args.TryGetValue("Chance", out var chance);
        args.TryGetValue("Note", out var note);

        GenerateControl(id, proto, guaranteed, chance, note);

        control = this;
        return true;
    }

    private void GenerateControl(string id, EntityPrototype proto, string? guaranteed, string? chance, string? note)
    {
        AccentBar.PanelOverride = new StyleBoxFlat { BackgroundColor = AshwalkerGuideColors.Success };

        IconContainer.AddChild(new GuideEntityEmbed(id, false, false));

        var name = Loc.TryGetString($"ent-{id}", out var locName) ? locName : proto.Name;
        NameLabel.SetMarkupPermissive($"[bold][color={AshwalkerGuideColors.ToMarkup(AshwalkerGuideColors.Success)}]{name}[/color][/bold]");

        BuildGuaranteed(guaranteed);
        BuildChance(chance);

        if (string.IsNullOrWhiteSpace(note))
            return;

        NoteLabel.Visible = true;
        NoteLabel.SetMarkupPermissive(note);
    }

    private void BuildGuaranteed(string? guaranteed)
    {
        if (string.IsNullOrWhiteSpace(guaranteed))
            return;

        foreach (var item in guaranteed.Split('|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            GuaranteedContainer.AddChild(new GuideAshwalkerChip(item, AshwalkerGuideColors.Success));
        }

        if (GuaranteedContainer.ChildCount == 0)
            return;

        GuaranteedBox.Visible = true;
        GuaranteedHeader.SetMarkupPermissive(Loc.GetString("adt-ashwalker-guide-guaranteed"));
    }

    private void BuildChance(string? chance)
    {
        if (string.IsNullOrWhiteSpace(chance))
            return;

        foreach (var entry in chance.Split('|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var split = entry.Split(':', 2);
            if (split.Length != 2 || !float.TryParse(split[1].Trim(), NumberStyles.Float, CultureInfo.InvariantCulture, out var percent))
                continue;

            ChanceContainer.AddChild(AshwalkerGuideWidgets.BuildBarRow(split[0].Trim(), percent, AshwalkerGuideColors.Accent));
        }

        if (ChanceContainer.ChildCount == 0)
            return;

        ChanceBox.Visible = true;
        ChanceHeader.SetMarkupPermissive(Loc.GetString("adt-ashwalker-guide-chance"));
    }
}
