using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.ADT.Guidebook.Ashwalkers;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideAshwalkerGearEmbed : BoxContainer, IDocumentTag, ISearchableControl
{
    [Dependency] private readonly ILogManager _logManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly ISawmill _sawmill;

    public GuideAshwalkerGearEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("guidebook.ashwalkers.gear");
        MouseFilter = MouseFilterMode.Stop;
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;

        if (!args.TryGetValue("Entity", out var id))
        {
            _sawmill.Error("Ashwalker gear embed is missing the Entity argument");
            return false;
        }

        if (!_prototype.TryIndex<EntityPrototype>(id, out var proto))
        {
            _sawmill.Error($"Unknown entity prototype \"{id}\"");
            return false;
        }

        args.TryGetValue("Craft", out var craft);
        args.TryGetValue("CraftTime", out var craftTime);
        args.TryGetValue("Damage", out var damage);
        args.TryGetValue("Armor", out var armor);
        args.TryGetValue("Note", out var note);

        GenerateControl(id, proto, craft, craftTime, damage, armor, note);

        control = this;
        return true;
    }

    private void GenerateControl(string id, EntityPrototype proto, string? craft, string? craftTime, string? damage, string? armor, string? note)
    {
        AccentBar.PanelOverride = new StyleBoxFlat { BackgroundColor = AshwalkerGuideColors.Accent };

        IconContainer.AddChild(new GuideEntityEmbed(id, false, false));

        var name = Loc.TryGetString($"ent-{id}", out var locName) ? locName : proto.Name;
        NameLabel.SetMarkupPermissive($"[bold][color={AshwalkerGuideColors.ToMarkup(AshwalkerGuideColors.Accent)}]{name}[/color][/bold]");

        BuildCraft(craft, craftTime);
        BuildDamage(damage);
        BuildArmor(armor);

        if (string.IsNullOrWhiteSpace(note))
            return;

        NoteLabel.Visible = true;
        NoteLabel.SetMarkupPermissive(note);
    }

    private void BuildCraft(string? craft, string? craftTime)
    {
        if (!string.IsNullOrWhiteSpace(craft))
        {
            foreach (var ingredient in craft.Split('|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                CraftContainer.AddChild(new GuideAshwalkerChip(ingredient, AshwalkerGuideColors.Accent));
            }
        }

        if (!string.IsNullOrWhiteSpace(craftTime))
        {
            CraftContainer.AddChild(new GuideAshwalkerChip(Loc.GetString("adt-ashwalker-guide-craft-time", ("seconds", craftTime)), AshwalkerGuideColors.Note));
        }

        if (CraftContainer.ChildCount == 0)
            return;

        CraftBox.Visible = true;
        CraftHeader.SetMarkupPermissive(Loc.GetString("adt-ashwalker-guide-craft"));
    }

    private void BuildDamage(string? damage)
    {
        if (string.IsNullOrWhiteSpace(damage))
            return;

        foreach (var entry in damage.Split('|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var split = entry.Split(':', 2);
            if (split.Length != 2)
                continue;

            DamageContainer.AddChild(AshwalkerGuideWidgets.BuildTextRow(split[0].Trim(), split[1].Trim()));
        }

        if (DamageContainer.ChildCount == 0)
            return;

        DamageBox.Visible = true;
        DamageHeader.SetMarkupPermissive(Loc.GetString("adt-ashwalker-guide-damage"));
    }

    private void BuildArmor(string? armor)
    {
        if (string.IsNullOrWhiteSpace(armor))
            return;

        foreach (var entry in armor.Split('|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var split = entry.Split(':', 2);
            if (split.Length != 2 || !float.TryParse(split[1].Trim(), NumberStyles.Float, CultureInfo.InvariantCulture, out var percent))
                continue;

            ArmorContainer.AddChild(AshwalkerGuideWidgets.BuildBarRow(split[0].Trim(), percent, AshwalkerGuideColors.Accent));
        }

        if (ArmorContainer.ChildCount == 0)
            return;

        ArmorBox.Visible = true;
        ArmorHeader.SetMarkupPermissive(Loc.GetString("adt-ashwalker-guide-armor"));
    }
}
