- type: job
  id: ADTBattleShipMedicTSF
  name: job-name-medic-tsf
  description: job-description-medic-tsf
  playTimeTracker: JobADTBattleShipMedicTSF
  requirements:
    - !type:SpeciesRequirement
      inverted: false
      species:
      - Human
      - Reptilian
      - Dwarf
      - Moth
      - VulpkaninSpecies
    - !type:OverallPlaytimeRequirement
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400 #4 hrs
  startingGear: ADTBattleShipMedicTSFGear
  icon: "JobIconMedicTSF"
  supervisors: job-supervisors-tsf-commander
  canBeAntag: false
  access:
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  - Medical
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSF
    - type: FriendlyFire
      enabled: true
    - type: FriendlyFireToggleable

- type: startingGear
  id: ADTBattleShipMedicTSFGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetERTSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ADTBaseUplinkBOBERT
  storage:
    back:
    - BoxSurvivalEngineering
    - BoxZiptie
    - CrowbarRed
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
