- type: job
  id: ADTBattleShipPilotTSF
  name: job-name-pilot-tsf
  description: job-description-pilot-tsf
  playTimeTracker: JobADTBattleShipPilotTSF
  requirements:
    - !type:SpeciesRequirement
      inverted: false
      species:
      - Human
      - Reptilian
      - Dwarf
    - !type:OverallPlaytimeRequirement
      time: 72000 #20 hrs 
  startingGear: ADTBattleShipPilotTSFGear
  icon: "JobIconPilotTSF"
  supervisors: job-supervisors-tsf-gunner
  canBeAntag: false
  overrideConsoleVisibility: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Engineering
  - External
  - Atmospherics
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSF
    - type: FriendlyFire
      enabled: true
    - type: FriendlyFireToggleable

- type: startingGear
  id: ADTBattleShipPilotTSFGear
  equipment:
    jumpsuit: ADTShipBattleClothingUniformGunnerTSF
    back: ADTShipBattleClothingBlackBackpackJetTSF
    shoes: ADTShipBattleClothingShoesBootsMagFleet
    # head: ADTShipBattleClothingHeadHatGunnerTSF
    eyes: ClothingEyesGlassesMeson
    gloves: ADTShipBattleClothingHandsGlovesGunnerBlack
    outerClothing: ADTShipBattleClothingOuterHardsuitPilotTSF
    id: ADTShipBattleDogtagPilotTSF
    ears: ADTShipBattleClothingHeadsetPilotTSF
    belt: ADTShipBattleClothingBeltWarbelt
    # pocket1: DoubleEmergencyOxygenTankFilled
    # pocket2: ADTBaseUplinkBOBERT
    underwearb: ADTClothingUnderwearBottomBoxersWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksBlack
  storage:
    back:
    - BoxSurvivalEngineering
    - CrowbarRed
    - SpaceCash500
    - ADTShipBattleClothingHeadHelmetHardsuitPilotTSF
