- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
  - !type:OverallPlaytimeRequirement
      time: 3600 #1 hrs # Corvax-RoleTime
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
    - type: MimePowers
    - type: FrenchAccent

- type: startingGear
  id: MimeGear
  equipment:
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesColorWhite
    pocket1: CrayonMime
    pocket2: Paper
    id: MimePDA
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampMime

- type: entity
  id: ActionMimeInvisibleWall
  name: Create Invisible Wall
  description: Create an invisible wall in front of you, if placeable there.
  components:
  - type: InstantAction
    priority: -1
    useDelay: 30
    icon:
      sprite: Structures/Walls/solid.rsi
      state: full
    event: !type:InvisibleWallActionEvent
