using Content.Client.Message;
using Content.Shared.Heretic.Prototypes;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.Guidebook.Heretic;

[GenerateTypedNameReferences]
public sealed partial class GuideHereticStageRow : PanelContainer
{
    public GuideHereticStageRow()
    {
        RobustXamlLoader.Load(this);
    }

    public GuideHereticStageRow(
        HereticKnowledgePrototype knowledge,
        ListingPrototype listing,
        Color accent,
        SpriteSystem sprite) : this()
    {
        var ascension = knowledge.Stage >= 9;
        var badgeColor = ascension ? HereticGuideColors.Ascension : accent;

        if (knowledge.SideKnowledge)
            badgeColor = HereticGuideColors.Side;

        StageBadge.PanelOverride = new StyleBoxFlat { BackgroundColor = badgeColor };
        StageLabel.Text = knowledge.Stage.ToString();

        if (listing.Icon != null)
            StageIcon.Texture = sprite.Frame0(listing.Icon);

        var name = listing.Name != null ? Loc.GetString(listing.Name) : knowledge.ID;
        var suffix = string.Empty;

        if (knowledge.SideKnowledge)
            suffix = $"  [color={HereticGuideColors.ToMarkup(HereticGuideColors.Side)}]{Loc.GetString("heretic-guide-stage-side")}[/color]";
        else if (ascension)
            suffix = $"  [color={HereticGuideColors.ToMarkup(HereticGuideColors.Ascension)}]{Loc.GetString("heretic-guide-stage-ascension")}[/color]";

        NameLabel.SetMarkupPermissive($"[bold]{name}[/bold]{suffix}");
        CostLabel.SetMarkupPermissive(Loc.GetString("heretic-guide-stage-cost", ("cost", GetCost(listing))));

        DescriptionHeading.Title = Loc.GetString("heretic-guide-stage-details");

        if (listing.Description != null)
            DescriptionLabel.SetMarkupPermissive(Loc.GetString(listing.Description));
        else
            DescriptionLabel.SetMarkupPermissive(Loc.GetString("heretic-guide-ritual-no-description"));
    }

    private static int GetCost(ListingPrototype listing)
    {
        foreach (var (_, amount) in listing.Cost)
        {
            return amount.Int();
        }

        return 0;
    }
}
