- type: entity
  id: BaseStationGoal
  abstract: true
  components:
    - type: StationGoal
      goals:
      #ADT-Tweak - стандартные цели заменены на транзит в рамках эксперимента
      # - Shuttle
      # - Singularity
      # - SolarPanels
      # - Artifacts
      # - Bank
      # - Zoo
      # - MiningOutpost
      # - Tesla
      - ADTStationGoalTransitBase
      - ADTStationGoalTransitResourses
      - ADTStationGoalTransitUpgrade
      - ADTStationGoalTransitServiceDecor
      - ADTStationGoalTransitServiceTransport
      - ADTStationGoalTransitArtifact
      - ADTStationGoalTransitMedicine
      - ADTStationGoalTransitContraband
      - ADTStationGoalMultiple

- type: entity
  id: BaseStationSiliconLawNTDefault
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: NTDefault
