- type: entity
  id: BaseStationGoal
  abstract: true
  components:
    - type: StationGoal
      goals:
      #ADT-Tweak - стандартные цели заменены на транзит в рамках эксперимента
      # - Shuttle
      # - Singularity
      # - SolarPanels
      # - Artifacts
      # - Bank
      # - Zoo
      # - MiningOutpost
      # - Tesla
      - ADTStationGoalTransportShuttle
      - ADTStationGoalDock
      - ADTStationGoalDormitory
      - ADTStationGoalTournament
      - ADTStationGoalRestavration
      - ADTStationGoalBridge
      - ADTStationGoalMail
      - ADTStationGoalAmbusol
      - ADTStationGoalStorage
      - ADTStationGoalMedbay
      - ADTStationGoalMech
      - ADTStationGoalAnomaly
      - ADTStationGoalKillbox
      - ADTStationGoalGreenhouses
      - ADTStationGoalOutpost
      - ADTStationGoalSolars
      # - ADTStationGoalTransitBase
      - ADTStationGoalTransitResourses
      - ADTStationGoalTransitUpgrade
      - ADTStationGoalTransitServiceDecor
      - ADTStationGoalTransitServiceTransport
      - ADTStationGoalTransitArtifact
      - ADTStationGoalTransitMedicine
      # - ADTStationGoalTransitContraband
      - ADTStationGoalMultiple1
      - ADTStationGoalMultiple2
      - ADTStationGoalMultiple3
      - ADTStationGoalMultiple4
      - ADTStationGoalMultiple5
      - ADTStationGoalMultiple6
      - ADTStationGoalMultiple7
      - ADTStationGoalMultiple8
      - ADTStationGoalMultiple9
      - ADTStationGoalMultiple10

- type: entity
  id: BaseStationSiliconLawNTDefault
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: NTDefault
