- type: technology
  id: CrystalManipulation
  name: research-technology-crystal-manipulation
  icon:
    sprite: /Textures/ADT/Bluespace_crystall/crystal_art.rsi
    state: crystal
  discipline: Experimental
  tier: 2
  cost: 15000
  recipeUnlocks:
  - ADTMaterialBScrystalArt
  # ADT Research Console Rework start
  position: 2,-2
  requiredTech:
  - AlternativeResearch
  # ADT Research Console Rework end

- type: latheRecipePack
  id: BluespaceCrystalTech
  recipes:
  - ADTMaterialBScrystalArt


- type: latheRecipe
  id: ADTMaterialBScrystalArt
  result: ADTMaterialBScrystalArt1
  completetime: 5
  materials:
    Plasma: 200
    Diamond: 200
    ADTBScrystal: 100
