- type: technology
  id: CrystalManipulation
  name: research-technology-crystal-manipulation
  icon:
    sprite: /Textures/ADT/Bluespace_crystall/crystall.rsi
    state: crystall
  discipline: Experimental
  tier: 2
  cost: 15000
  recipeUnlocks:
  - MaterialBScrystalArt
  # ADT Research Console Rework start
  position: 2,-1
  requiredTech:
  - AlternativeResearch
  # ADT Research Console Rework end

- type: latheRecipePack
  id: BluespaceCrystalTech
  recipes:
  - MaterialBScrystalArt


- type: latheRecipe
  id: MaterialBScrystalArt
  result: MaterialBScrystalArt1
  completetime: 5
  materials:
    Plasma: 200
    Diamond: 200
    BScrystal: 100
