- type: entity
  id: ADTCrateSecurityBrigmedic
  abstract: true
  parent: CrateSecgear
  components:
  - type: StorageFill
    contents:
      - id: BrigmedicPDA
      - id: ADTClothingHeadHatBeretBrigmedic
      - id: ClothingBackpackDuffelBrigmedic
      - id: ClothingBackpackBrigmedic
      - id: ClothingBackpackSatchelBrigmedic
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingHeadsetBrigmedic
      - id: ClothingOuterCoatAMG
      - id: ClothingOuterHardsuitBrigmedic
      - id: ClothingUniformJumpskirtOfLife
      - id: ClothingHeadHelmetSecurityMedic
      - id: WeaponDisabler
      - id: MedkitCombatFilled
      - id: MedkitAdvancedFilled
