- type: startingGear
  id: SpaceSecService
  equipment:
    jumpsuit: ADTSpaceSecUniformService
    back: ClothingBackpackSatchelFilled
    shoes: ClothingShoesColorBlack
    id: ADTSpaceSecServiceIDCard
    ears: ADTSpaceSecClothingHeadset
#    underwearb: ClothingUnderwearBottomBoxersWhite
#    socks: ClothingUnderwearSocksNormal
    neck: ADTSpaceSecToken
#  underweart: ClothingUnderwearTopBraWhite
#  underwearb: ClothingUnderwearBottomPantiesWhite
