using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Numerics;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared.ADT.EntityEffects;
using Content.Shared.Chemistry.Reaction;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.EntityEffects;
using ReactiveReagentEffectEntry = Content.Shared.Chemistry.Reaction.ReactiveReagentEffectEntry;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.ADT.Guidebook.Xenobiology;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideXenobiologyReactionEmbed : BoxContainer, IDocumentTag, ISearchableControl
{
    [Dependency] private readonly IComponentFactory _componentFactory = default!;
    [Dependency] private readonly IEntitySystemManager _systems = default!;
    [Dependency] private readonly ILogManager _logManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private const float ChipWidth = 80f;

    private static readonly Dictionary<string, int> ReagentOrder = new()
    {
        ["Water"] = 0,
        ["Plasma"] = 1,
        ["Blood"] = 2,
        ["Radium"] = 3,
    };

    private readonly ISawmill _sawmill;

    public GuideXenobiologyReactionEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("guidebook.xenobiology.reaction");
        MouseFilter = MouseFilterMode.Stop;
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;

        if (!args.TryGetValue("Extract", out var extractId))
        {
            _sawmill.Error("Xenobiology reaction embed is missing the Extract argument");
            return false;
        }

        if (!_prototype.TryIndex<EntityPrototype>(extractId, out var extract))
        {
            _sawmill.Error($"Unknown slime extract prototype \"{extractId}\"");
            return false;
        }

        args.TryGetValue("Tier", out var tierStr);
        var tier = int.TryParse(tierStr, out var parsedTier) ? parsedTier : 0;

        GenerateControl(extract, tier);

        control = this;
        return true;
    }

    private void GenerateControl(EntityPrototype extract, int tier)
    {
        var accent = XenobiologyGuideColors.ForTier(tier);
        AccentBar.PanelOverride = new StyleBoxFlat { BackgroundColor = accent };

        var embed = new GuideEntityEmbed(extract.ID, false, false)
        {
            Scale = new Vector2(2.5f, 2.5f),
        };
        embed.ToolTip = GetLocalizedName(extract.ID, extract);
        ExtractViewContainer.AddChild(embed);

        var name = GetLocalizedName(extract.ID, extract);
        NameLabel.SetMarkupPermissive($"[bold][color={XenobiologyGuideColors.ToMarkup(accent)}]{name}[/color][/bold]");

        var tierColor = XenobiologyGuideColors.ForTier(tier);
        TierBadge.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = tierColor,
            BorderThickness = new Thickness(1),
            BorderColor = XenobiologyGuideColors.NodeOutline,
        };
        TierLabel.SetMarkupPermissive($"[bold][color=#1c1a22]{Loc.GetString("xenobio-guide-tier", ("tier", tier))}[/color][/bold]");

        if (!extract.TryGetComponent<ReactiveComponent>(out var reactive, _componentFactory)
            || reactive.Reactions == null
            || reactive.Reactions.Count == 0)
        {
            _sawmill.Warning($"Slime extract \"{extract.ID}\" has no reactions to show");
            return;
        }

        var entries = reactive.Reactions
            .Where(x => x.Reagents != null && x.Reagents.Count > 0)
            .OrderBy(x => ReagentOrder.GetValueOrDefault(x.Reagents!.First(), 4))
            .ToList();

        foreach (var entry in entries)
        {
            AddReactionRow(entry);
        }
    }

    private void AddReactionRow(ReactiveReagentEffectEntry entry)
    {
        var reagentId = entry.Reagents!.First();
        var color = XenobiologyGuideColors.ForReagent(reagentId);
        var reagentName = _prototype.TryIndex<ReagentPrototype>(reagentId, out var reagent)
            ? reagent.LocalizedName
            : reagentId;

        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 4, 0, 0),
            HorizontalExpand = true,
        };

        var chip = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = color.WithAlpha(0.16f),
                BorderThickness = new Thickness(1),
                BorderColor = color.WithAlpha(0.7f),
            },
            MinWidth = ChipWidth,
            VerticalAlignment = VAlignment.Center,
        };
        var chipBox = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Margin = new Thickness(4, 2, 4, 2),
        };
        chipBox.AddChild(new RichTextLabel
        {
            HorizontalAlignment = HAlignment.Center,
            Text = Loc.GetString("xenobio-guide-reagent-chip", ("reagent", reagentName), ("color", XenobiologyGuideColors.ToMarkup(color))),
        });
        chip.AddChild(chipBox);
        row.AddChild(chip);

        var effectPanel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#2a2730"),
                BorderThickness = new Thickness(1),
                BorderColor = XenobiologyGuideColors.Border,
            },
            Margin = new Thickness(8, 0, 0, 0),
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        effectPanel.AddChild(new RichTextLabel
        {
            Margin = new Thickness(6, 2, 6, 2),
            Text = $"[font size=11]{DescribeEffects(entry)}[/font]",
        });
        row.AddChild(effectPanel);

        ReactionBox.AddChild(row);
    }

    private string DescribeEffects(ReactiveReagentEffectEntry entry)
    {
        var parts = new List<string>();

        foreach (var effect in entry.Effects)
        {
            if (effect is MakeUnreactiveEntityEffect)
                continue;

            var text = effect.EntityEffectGuidebookText(_prototype, _systems);
            if (string.IsNullOrWhiteSpace(text))
                continue;

            parts.Add(text);
        }

        return parts.Count > 0
            ? string.Join(", ", parts)
            : Loc.GetString("xenobio-guide-reaction-none");
    }

    private string GetLocalizedName(string id, EntityPrototype proto)
    {
        return Loc.TryGetString($"ent-{id}", out var name) ? name : proto.Name;
    }
}