using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.MidroundCustomization;

[GenerateTypedNameReferences]
public sealed partial class MidroundCustomizationWindow : DefaultWindow
{
    public MidroundCustomizationWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
