import os
import yaml
from yaml.constructor import SafeConstructor

# Обработка пользовательских тегов, чтобы их игнорировать

class IgnoreUnknownTagsConstructor(yaml.SafeLoader):
    pass

def ignore_unknown(loader, node):
    return None

# Универсальный игнор любых пользовательских YAML-тегов вида `!type:*` и любых `!CustomTag`
def ignore_unknown_multi(loader, tag_suffix, node):
    return None

yaml.add_multi_constructor('!type:', ignore_unknown_multi, Loader=IgnoreUnknownTagsConstructor)
yaml.add_multi_constructor('!', ignore_unknown_multi, Loader=IgnoreUnknownTagsConstructor)

yaml.add_constructor('!type:SoundPathSpecifier', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ContainerSlot', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:Container', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PolygonShape', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:WeldJoint', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PhysShapeAabb', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DamageTrigger', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DoActsBehavior', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlaySoundBehavior', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SpawnEntitiesBehavior', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CableDeviceNode', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RoleTimeRequirement', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DepartmentTimeRequirement', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:OverallPlaytimeRequirement', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AddComponentSpecial', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:GiveItemOnHolidaySpecial', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CreateGas', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:GiveItemOnHolidaySpecial', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CreateEntityReactionEffect', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ExplosionReactionEffect', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:StorageWelded', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SpawnPrototype', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SetStackCount', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:WallmountCondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlaySound', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AppearanceChange', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:GivePrototype', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AppearanceChange', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:EntityAnchored', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AppearanceChange', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AdminLog', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AppearanceChange', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SnapToGrid', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AppearanceChange', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DestroyEntity', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ContainerEmpty', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DeleteEntity', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SetAnchor', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BuildMech', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PopupEveryone', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BoardNodeEntity', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ContainerNotEmpty', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TileNotBlocked', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:FlammableTileReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlantAdjustNutrition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ActivateArtifact', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AddImplantSpecial', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PowerWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:InvisibleWallActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PopupMessage', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AreaReactionEffect', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:EmptyAllContainers', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:Locked', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:EmptyContainer', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:MinSolution', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:WirePanel', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AllWiresCut', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DoorBolted', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DoorWelded', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:VisualizerDataInt', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SetWiresPanelSecurity', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ConditionalAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DamageEntity', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NoUnstackableInTile', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:EmptyOrWindowValidInTile', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlantAdjustWater', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlantAdjustHealth', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SatiateThirst', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlantAdjustToxins', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlantAdjustWeeds', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlantAdjustHealth', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:Oxygenate', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CreateEntityTileReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CleanTileReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:HealthChange', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NoiseDunGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RandomSpawnsLoot', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PrefabDunGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BiomeMetaLayer', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ImageParallaxTextureSource', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:HTNPrimitiveTask', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:HTNCompoundTask', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:QuadraticCurve', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:HasOrdersPrecondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BuckledPrecondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ActiveHandFreePrecondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NanotrasenNameGenerator', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TeleportSpellEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ChangeComponentsSpellEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DoorBoltWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:EmpReactionEffect', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SolutionEmpty', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:HasTag', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DeleteEntitiesInContainer', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AddContainer', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NoWindowsInTile', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlantAdjustPests', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AdjustReagent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ExtinguishTileReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlantAdjustMutationLevel', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PryTileReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:MovespeedModifier', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlantCryoxadone', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ModifyLungGas', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CleanDecalsReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ChemCleanBloodstream', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SpillTileReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BiomePostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BiomeMarkerLoot', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BiomeEntityLayer', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:GeneratedParallaxTextureSource', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ActiveHandComponentPrecondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:GunAmmoPrecondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:InventoryQuery', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PulledPrecondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:WorldSpawnSpellEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SmiteSpellEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:InstantSpawnSpellEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ProjectileSpellEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:KnockSpellEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TileType', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ChangeConstructionNodeBehavior', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PhysShapeCircle', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:JobRequirementLoadoutEffect', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RngGhostRoleRaffleDecider', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ElectrocutionNode', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DamageTypeTrigger', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:EmptyAllContainersBehaviour', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PortablePipeNode', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DoorBoltLightWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AttemptElectrocute', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:MachineFrameRegenerateProgress', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ChemVomit', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SatiateHunger', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SpillIfPuddlePresentTileReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:GenericStatusEffect', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:FlammableReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlantPhalanximine', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AdjustAlert', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlantAdjustMutationMod', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:Emote', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:MarkerLayerPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CorridorPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BiomeDummyLayer', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:InContainerPrecondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ComponentFilter', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:WashCreamPieReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:GibBehavior', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:GroupLoadoutEffect', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SolutionExplosionBehavior', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DumpCanisterBehavior', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TegNodeGenerator', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SpillBehavior', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ExplodeBehavior', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AdjacentNode', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CableTerminalPortNode', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CableTerminalNode', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CableNode', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PipeNode', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:EjectVendorItems', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SoundCollectionSpecifier', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AddToSolutionReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TriggerBehavior', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:Single', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:FadeBehaviour', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DoorTimingWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:MachineFrameComplete', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AdjustTemperature', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ModifyBleedAmount', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ExtinguishReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:Drunk', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CauseZombieInfection', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:Jitter', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:Electrocute', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ModifyBloodLevel', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ModifyBleedAmount', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RobustHarvest', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DungeonEntrancePostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BiomeTileLayer', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:KeyExistsPrecondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TargetAmmoCon', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TegNodeCirculator', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SpawnGasBehavior', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PortPipeNode', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PulseBehaviour', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleJetpackEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RandomizeBehaviour', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DumpRestockInventory', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BorgModuleActionSelectedEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:MechGrabberUi', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SummonActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TabletopParchisSetup', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TabletopEmptySetup', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TabletopChessSetup', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TabletopCheckerSetup', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TabletopEmptySetup', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TabletopBackgammonSetup', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:OpenUiActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DisguiseToggleNoRotEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NotekeeperUi', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:OpenBehavior', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:WearableReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BooActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:GuardianToggleActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DragonSpawnRiftActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleIntrinsicUIEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:Bool', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RatKingRaiseArmyActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:EmptyContainersBehaviour', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TattooColoring', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SimpleColoring', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CategoryColoring', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:EyeColoring', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BurnBodyBehavior', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleMagbootsEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:StethoscopeActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleMaskEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:StoreWhitelistCondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ListingLimitedStockCondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AlarmThresholdSetting', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlasmaFireReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ResistFire', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ScreamActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SpiderWebActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:MeleeSpeechConfigureActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RevenantShopActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RevertPolymorphActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:MechToggleEquipmentEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:GibActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CritSuccumbEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleLawsScreenEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ChineseNewYear', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AlwaysTrueRule', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DoorSafetyWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RaiseEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:Ignite', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ResetNarcolepsy', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CureZombieInfection', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:Polymorph', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlantAffectGrowth', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RoomEntrancePostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BiomeDecalLayer', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ComponentQuery', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ColorCycleBehaviour', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:MechSoundboardUi', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DisguiseToggleAnchoredEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NewsReaderUi', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleLightingActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DevourActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RatKingDomainActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SkinColoring', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BuyerWhitelistCondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TritiumFireReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RemoveCuffs', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ZombifySelfActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SericultureActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RevenantDefileActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PolymorphActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:MechOpenUiEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ReformEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CritFakeDeathEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:Custom', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:InSpaceRule', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DevourActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AccessWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ChemHealEyeDamage', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PlantDiethylamine', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:EntranceFlankPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TargetAmmoMatchesCon', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CrewManifestUi', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleFoVActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ActionGunShootEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RatKingOrderActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BuyerJobCondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:FrezonCoolantReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RemoveEnsnare', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:OpenStorageImplantEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RevenantOverloadLightsActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CreateThrowingStarEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:MechEjectPilotEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CritLastWordsEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:WeekdayInMonth', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:GridInRangeRule', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CreateThrowingStarEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:VendingMachineContrabandWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:MakeSentient', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TargetDistanceCon', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NetProbeUi', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleGhostsActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BuyerDepartmentCondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:FrezonProductionReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:Unbuckle', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ActivateImplantEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RevenantBlightActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RecallKatanaEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DayOfYear', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NearbyAccessRule', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:VendingMachineEjectItemWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ReduceRotting', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ExternalWindowPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TargetAccessibleCon', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:LogProbeUi', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleGhostHearingActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AmmoniaOxygenReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleInternals', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:UseFreedomImplantEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RevenantMalfunctionActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NinjaEmpEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:FridayThirteenth', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NearbyTilesPercentRule', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NearbyAccessRule', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NearbyComponentsRule', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleStealthEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:OpenUplinkImplantEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:StopPiloting', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:N2ODecompositionReaction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:WallMountPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SpeechWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NearbyEntitiesRule', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DashEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:UseScramImplantEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BreakVow', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:FoodValueCon', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BoundaryWallPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AirAlarmPanicWire', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BoundaryWallPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:OnMapGridRule', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:UseDnaScramblerImplantEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:RetakeVow', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TargetIsAliveCon', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:JunctionPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AtmosMonitorDeviceNetWire', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:MorphIntoGeras', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:StopBeingPulled', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DrinkValueCon', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AutoCablingPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ListenWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleClothingEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:StopPulling', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:NearbyHostilesQuery', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CornerClutterPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ArcadeOverflowWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleCombatActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CornerClutterPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TargetHealthCon', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CorridorDecalSkirtingPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ArcadePlayerInvincibleWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:VoiceMaskSetNameEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TargetInLOSOrCurrentCon', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:WormCorridorPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ArcadeEnemyInvincibleWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:VendingMachineSelfDispenseEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:OrderedTargetCon', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CorridorClutterPostGen', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:CryoPodEjectLockWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ArtifactSelfActivateEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:TargetMeleeCon', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ParticleAcceleratorKeyboardWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ClearAllOverlaysEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:PuddleFilter', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ParticleAcceleratorLimiterWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:EggLayInstantActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ParticleAcceleratorPowerWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SleepActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ParticleAcceleratorStrengthWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:WakeActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ActivateWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:FireStarterActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BoltWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DelayWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleEyesActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ProceedWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BoomWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:SpeciesLoadoutEffect', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleEmotePanelActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:LanguageMenuActionEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AngelDustPolyEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DiseaseAdjustReagent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:LogWireAction', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:AmeShieldIntegrity', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ChemCauseDisease', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ChemMiasmaPoolSource', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ChargeSpellEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:BuyBeforeCondition', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DiseasePopUp', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:DiseaseHealthChange', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ChemCureDisease', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)
yaml.add_constructor('!type:ToggleGhostVisibilityToAllEvent', ignore_unknown, Loader=IgnoreUnknownTagsConstructor)


def find_top_level_dir(start_dir):
    marker_file = 'SpaceStation14.sln'
    current_dir = start_dir
    while True:
        if marker_file in os.listdir(current_dir):
            return current_dir
        parent_dir = os.path.dirname(current_dir)
        if parent_dir == current_dir:
            print(f"Не удалось найти {marker_file} начиная с {start_dir}")
            exit(-1)
        current_dir = parent_dir

def collect_entity_ids(root_folder):
    entity_ids = []

    for subdir, _, files in os.walk(root_folder):
        for file in files:
            if file.endswith('.yml'):
                file_path = os.path.join(subdir, file)
                with open(file_path, 'r', encoding='utf-8') as f:
                    try:
                        data = yaml.load(f, Loader=IgnoreUnknownTagsConstructor)
                        if data:
                            if isinstance(data, dict) and data.get('type') == 'entity':
                                entity_ids.append(data.get('id'))
                            elif isinstance(data, list):
                                for item in data:
                                    if item.get('type') == 'entity':
                                        entity_ids.append(item.get('id'))
                    except yaml.YAMLError as e:
                        print(f"Ошибка при обработке файла {file_path}: {e}")

    return entity_ids

def save_ids_to_file(entity_ids, output_file):
    entity_ids.sort()

    with open(output_file, 'w', encoding='utf-8') as f:
        for entity_id in entity_ids:
            f.write(entity_id + '\n')

# Определяем текущий путь скрипта
script_dir = os.path.dirname(os.path.abspath(__file__))

main_folder = find_top_level_dir(script_dir)

# Путь к папке Prototypes относительно текущего местоположения скрипта
root_folder = os.path.join(main_folder, './Resources/Prototypes')

# Проверяем существование директории
if not os.path.exists(root_folder):
    print(f"Папка {root_folder} не найдена!")
    exit(1)

# Укажите имя выходного файла
output_file = os.path.join(script_dir, 'entity_ids.txt')

# Собираем все entity id
entity_ids = collect_entity_ids(root_folder)

# Сохраняем отсортированные id в файл
save_ids_to_file(entity_ids, output_file)

# Выводим количество собранных id в консоль
print(f"Собрано {len(entity_ids)} entity IDs")

print(f"Собранные entity IDs сохранены в файл {output_file}")
