- type: job
  id: Borg
  name: job-name-ADTSecBorg
  description: job-description-borg
  playTimeTracker: JobSecBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 216000 # 60 hrs
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgGeneric
