using System.Diagnostics.CodeAnalysis;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.ADT.Guidebook.WorldAnvil;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideWorldAnvilUpgradeEmbed : BoxContainer, IDocumentTag, ISearchableControl
{
    [Dependency] private readonly ILogManager _logManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly ISawmill _sawmill;

    public GuideWorldAnvilUpgradeEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("guidebook.world-anvil.upgrade");
        MouseFilter = MouseFilterMode.Stop;
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;

        if (!args.TryGetValue("Base", out var baseId))
        {
            _sawmill.Error("World anvil upgrade embed is missing the Base argument");
            return false;
        }

        if (!args.TryGetValue("Result", out var resultId))
        {
            _sawmill.Error("World anvil upgrade embed is missing the Result argument");
            return false;
        }

        GenerateControl(baseId, resultId);

        control = this;
        return true;
    }

    private void GenerateControl(string baseId, string resultId)
    {
        var accent = WorldAnvilGuideColors.Magmite;
        AccentBar.PanelOverride = new StyleBoxFlat { BackgroundColor = accent };

        if (_prototype.TryIndex<EntityPrototype>(baseId, out var baseProto))
        {
            var baseEmbed = new GuideEntityEmbed(baseId, false, false);
            baseEmbed.ToolTip = GetLocalizedName(baseId, baseProto);
            BaseViewContainer.AddChild(baseEmbed);
        }
        else
        {
            _sawmill.Error($"World anvil upgrade has unknown base prototype \"{baseId}\"");
        }

        ArrowLabel.SetMarkupPermissive($"[color={WorldAnvilGuideColors.ToMarkup(accent)}]→[/color]");

        if (_prototype.TryIndex<EntityPrototype>(resultId, out var resultProto))
        {
            var resultEmbed = new GuideEntityEmbed(resultId, false, false);
            resultEmbed.ToolTip = GetLocalizedName(resultId, resultProto);
            ResultViewContainer.AddChild(resultEmbed);

            var name = GetLocalizedName(resultId, resultProto);
            var description = GetLocalizedDescription(resultId, resultProto);

            NameLabel.SetMarkupPermissive($"[bold][color={WorldAnvilGuideColors.ToMarkup(accent)}]{name}[/color][/bold]");
            DescriptionLabel.SetMarkupPermissive(description ?? Loc.GetString("world-anvil-guide-no-description"));
        }
        else
        {
            _sawmill.Error($"World anvil upgrade has unknown result prototype \"{resultId}\"");
        }
    }

    private string? GetLocalizedName(string id, EntityPrototype proto)
    {
        return Loc.TryGetString($"ent-{id}", out var name) ? name : proto.Name;
    }

    private string? GetLocalizedDescription(string id, EntityPrototype proto)
    {
        return Loc.TryGetString($"ent-{id}.desc", out var description) ? description : proto.Description;
    }
}