using System.Diagnostics.CodeAnalysis;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.Guidebook.WorldAnvil;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideWorldAnvilQuote : BoxContainer, IDocumentTag
{
    public GuideWorldAnvilQuote()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;

        string text;
        if (args.TryGetValue("Loc", out var locId))
            text = Loc.GetString(locId);
        else if (args.TryGetValue("Text", out var raw))
            text = raw;
        else
            return false;

        var color = WorldAnvilGuideColors.Accent;
        if (args.TryGetValue("Color", out var colorArg)
            && Color.TryFromHex(colorArg) is { } parsed)
        {
            color = parsed;
        }

        Bar.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
        QuoteLabel.SetMarkupPermissive($"[italic][color={WorldAnvilGuideColors.ToMarkup(color)}]{text}[/color][/italic]");

        control = this;
        return true;
    }
}