using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Changeling;
using Content.Shared.Humanoid;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.ADT.Changeling.UI;

[GenerateTypedNameReferences]
public sealed partial class ChangelingTransformMenu : RadialMenu
{
    [Dependency] private readonly EntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private readonly HumanoidProfileSystem _profileSystem;
    private readonly SpriteSystem _spriteSystem;
    public List<NetEntity> Forms = new();
    public ChangelingMenuType Type = ChangelingMenuType.Transform;
    public NetEntity Target = NetEntity.Invalid;

    public event Action<NetEntity>? OnSelectForm;

    public ChangelingTransformMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _spriteSystem = _entManager.System<SpriteSystem>();
        _profileSystem = _entManager.System<HumanoidProfileSystem>();
    }

    public void Populate(RequestChangelingFormsMenuEvent args)
    {
        var parent = FindControl<RadialContainer>("Main");

        foreach (var item in args.HumanoidData)
        {
            if (Forms.Contains(item.NetEntity))
                return;

            var dummy = _entManager.SpawnEntity(_proto.Index(item.Profile.Species).DollPrototype, MapCoordinates.Nullspace);
            // Добавляем компонент HumanoidProfileComponent, если его нет
            if (!_entManager.HasComponent<HumanoidProfileComponent>(dummy))
            {
                var profileComp = _entManager.AddComponent<HumanoidProfileComponent>(dummy);
            }

            // Применяем профиль через новую систему
            _profileSystem.ApplyProfileTo(dummy, item.Profile);

            // Создаём SpriteView для отображения
            var face = new SpriteView();
            face.SetEntity(dummy);

            var button = new ChangelingTransformMenuButton
            {
                StyleClasses = { "RadialMenuButton" },
                SetSize = new Vector2(64f, 64f),
                ToolTip = Loc.GetString(item.Name ?? string.Empty),
                Entity = item.NetEntity,
                Profile = item.Profile,
                Name = item.Name,
                SeparatorColor = Color.Black,
                BackgroundColor = new Color(173, 33, 42, 128),
                HoverBackgroundColor = new Color(224, 22, 36, 128),
                BorderColor = new Color(224, 22, 36, 128),
                HoverBorderColor = new Color(224, 22, 36, 128),
                DrawBorder = true
            };

            button.AddChild(face);
            parent.AddChild(button);
            Forms.Add(item.NetEntity);
        }

        foreach (var child in Children)
        {
            if (child is not RadialContainer container)
                continue;
            AddLingClickAction(container);
        }
    }
    private void AddLingClickAction(RadialContainer container)
    {
        foreach (var child in container.Children)
        {
            if (child is not ChangelingTransformMenuButton castChild)
                continue;

            castChild.OnButtonUp += _ =>
            {
                OnSelectForm?.Invoke(castChild.Entity);
            };
        }
    }
}


public sealed class ChangelingTransformMenuButton : RadialMenuButtonWithSector
{
    public NetEntity Entity;
    public HumanoidCharacterProfile? Profile;
    public new string? Name;
}
