using System.Linq;
using System.Numerics;
using Content.Client.ADT.UserInterface.Controls;
using Content.Client.UserInterface.Controls;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostTargetWindow : DefaultWindow
    {
        private string _searchText = string.Empty;

        // ADT-TWEAK START
        private List<GhostWarp> _originalGhostWarps = [];
        private bool _showWithMindOnly = true;

        private Dictionary<string, List<GhostWarp>> _alivePlayers = [];
        private Dictionary<string, List<GhostWarp>> _deadPlayers = [];
        private Dictionary<string, List<GhostWarp>> _ghostPlayers = [];
        private Dictionary<string, List<GhostWarp>> _leftPlayers = [];
        private Dictionary<string, List<GhostWarp>> _aliveAntags = [];
        private Dictionary<string, List<GhostWarp>> _deadAntags = [];
        private Dictionary<string, List<GhostWarp>> _unknown = [];

        private Dictionary<string, List<GhostWarp>> _places = [];

        // ADT-TWEAKEND

        public event Action<NetEntity>? WarpClicked;
        public event Action? OnGhostnadoClicked;

        public GhostTargetWindow()
        {
            RobustXamlLoader.Load(this);
            SearchBar.OnTextChanged += OnSearchTextChanged;
            GhostnadoButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();
            MindFilterCheckBox.OnToggled += OnMindFilterToggled;
        }

       // ADT-TWEAK START
        public void Populate()
        {
            GhostTeleportContainer.DisposeAllChildren();
            FilterWarps();
            AddButtons(); // <<< ВАЖНО: вызываем AddButtons() здесь!
        }

        private void FilterWarps()
        {
            _alivePlayers.Clear();
            _deadPlayers.Clear();
            _ghostPlayers.Clear();
            _leftPlayers.Clear();
            _aliveAntags.Clear();
            _deadAntags.Clear();
            _unknown.Clear();
            _places.Clear();

            var unknownLabel = Loc.GetString("game-ticker-unknown-role");

            foreach (var warp in _originalGhostWarps)
            {
                if (_showWithMindOnly && !warp.HasMind)
                    continue;

                if (!string.IsNullOrEmpty(_searchText)
                    && !warp.DisplayName.Contains(_searchText, StringComparison.OrdinalIgnoreCase)
                    && !warp.SubGroup.Contains(_searchText, StringComparison.OrdinalIgnoreCase)
                    && !(warp.Description?.Contains(_searchText, StringComparison.OrdinalIgnoreCase) ?? false))
                    continue;

                if (warp.Group == WarpGroup.Location)
                {
                    FilterLocalWarps(_places, warp, null);
                    continue;
                }

                if (warp.Group.HasFlag(WarpGroup.Ghost))
                {
                    FilterLocalWarps(_ghostPlayers, warp, null);
                    continue;
                }

                if (warp.Group.HasFlag(WarpGroup.Antag))
                {
                    if (warp.Group.HasFlag(WarpGroup.Left))
                        FilterLocalWarps(_leftPlayers, warp, null);
                    else if (warp.Group.HasFlag(WarpGroup.Dead))
                        FilterLocalWarps(_deadAntags, warp, null);
                    else
                        FilterLocalWarps(_aliveAntags, warp, null);
                    continue;
                }

                if (warp.Group.HasFlag(WarpGroup.Department))
                {
                    if (warp.Group.HasFlag(WarpGroup.Left))
                        FilterLocalWarps(_leftPlayers, warp, null);
                    else if (warp.Group.HasFlag(WarpGroup.Dead))
                        FilterLocalWarps(_deadPlayers, warp, null);
                    else
                        FilterLocalWarps(_alivePlayers, warp, null);
                    continue;
                }

                if (warp.SubGroup == unknownLabel)
                    FilterLocalWarps(_unknown, warp, null);
            }
        }

        private void FilterLocalWarps(Dictionary<string, List<GhostWarp>> groups, GhostWarp warp, WarpGroup? group)
        {
            if (group != null && !warp.Group.HasFlag(group))
               return;

            if (!groups.TryGetValue(warp.SubGroup, out var list))
            {
                list = [];
                groups.Add(warp.SubGroup, list);
            }

            list.Add(warp);
        }

        // ADT-TWEAK END

        public void UpdateWarps(List<GhostWarp> warps) // ADT-TWEAK
        {
            // ADT-TWEAK START
            _originalGhostWarps = warps;
            Populate();
            // ADT-TWEAK END
        }

        private void OnMindFilterToggled(BaseButton.ButtonToggledEventArgs args)
        {
            _showWithMindOnly = args.Pressed;
            Populate();
        }

        private void AddButtons()
        {
            // Добавляем проверку на наличие данных
            var hasData = _aliveAntags.Count > 0 || _deadAntags.Count > 0 ||
                          _alivePlayers.Count > 0 ||
                          _ghostPlayers.Count > 0 || _leftPlayers.Count > 0 ||
                          _deadPlayers.Count > 0 ||
                          _unknown.Count > 0 || _places.Count > 0;

            if (!hasData)
            {
                // Добавляем сообщение, если нет данных
                var noDataLabel = new Label
                {
                    Text = Loc.GetString("ghost-teleport-menu-no-targets"),
                    StyleClasses = { "LabelBig" },
                    Align = Label.AlignMode.Center,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                };
                GhostTeleportContainer.AddChild(noDataLabel);
                return;
            }

            // ADT-TWEAK START
            AddButtons(_aliveAntags, "ghost-teleport-menu-antagonists-label");
            AddButtons(_deadAntags, "ghost-teleport-menu-dead-antagonists-label");
            AddButtons(_alivePlayers, "ghost-teleport-menu-alive-label");
            AddButtons(_ghostPlayers, "ghost-teleport-menu-ghosts-label");
            AddButtons(_leftPlayers, "ghost-teleport-menu-left-label", true);
            AddButtons(_deadPlayers, "ghost-teleport-menu-dead-label", true);
            AddUnknownSection();
            AddButtons(_places, "ghost-teleport-menu-locations-label", true);
        }

        private void AddUnknownSection()
        {
            if (_unknown.Count == 0)
                return;

            var mainContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SeparationOverride = 5
            };

            mainContainer.AddChild(CreateSectionHeader("ghost-teleport-menu-unknown-label"));

            var subBox = new FlexBox
            {
                AlignContent = FlexBox.FlexAlignContent.SpaceBetween
            };

            foreach (var warps in _unknown.Values)
            foreach (var warp in warps)
                subBox.AddChild(CreateWarpButton(warp));

            mainContainer.AddChild(subBox);
            GhostTeleportContainer.AddChild(mainContainer);
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            _searchText = args.Text.ToLower();
            Populate();
        }

        private void AddButtons(Dictionary<string, List<GhostWarp>> sortedWarps, string text, bool enableOtherCategory = false)
        {
            if(sortedWarps.Count == 0)
                return;

            var mainContainer = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SeparationOverride = 5
            };

            var header = CreateSectionHeader(text);
            mainContainer.AddChild(header);

            var otherContainer = new FlexBox()
            {
                AlignContent = FlexBox.FlexAlignContent.SpaceBetween
            };

            var sortedSubCategories = sortedWarps.OrderByDescending(kvp =>
            {
                var warps = kvp.Value;
                if (warps == null || warps.Count == 0)
                    return int.MinValue;
                return warps.Min(w => w.DepartmentWeight);
            }).ToList();

            foreach (var (subCategory, warps) in sortedSubCategories)
            {
                if(warps.Count == 0)
                    continue;

                var isOtherContainer = enableOtherCategory && (string.IsNullOrEmpty(subCategory) || warps.Count == 1);

                var subBox = new FlexBox()
                {
                    AlignContent = FlexBox.FlexAlignContent.SpaceBetween
                };

                var departmentLabel = new Label
                {
                    Text = Loc.GetString("ghost-teleport-menu-subgroup-label",
                        ("name", string.IsNullOrEmpty(subCategory) ? Loc.GetString("ghost-teleport-menu-other-label") : subCategory),
                        ("count", warps.Count)),
                    StyleClasses = { "LabelSecondaryColor" }
                };

                foreach (var warp in warps)
                {
                    var playerButton = CreateWarpButton(warp);

                    if(!isOtherContainer)
                        subBox.AddChild(playerButton);
                    else
                        otherContainer.AddChild(playerButton);
                }

                if(!isOtherContainer)
                {
                    mainContainer.AddChild(departmentLabel);
                    mainContainer.AddChild(subBox);
                }
            }

            if (enableOtherCategory && otherContainer.ChildCount > 0)
            {
                var otherLabel = new Label
                {
                    Text = Loc.GetString("ghost-teleport-menu-other-label") + ": " + otherContainer.ChildCount,
                    StyleClasses = { "LabelSecondaryColor" }
                };

                mainContainer.AddChild(otherLabel);
                mainContainer.AddChild(otherContainer);
            }

            GhostTeleportContainer.AddChild(mainContainer);
        }

        private Button CreateWarpButton(GhostWarp warp)
        {
            var playerButton = new Button
            {
                Text = warp.DisplayName,
                TextAlign = Label.AlignMode.Right,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                SizeFlagsStretchRatio = 1,
                ModulateSelfOverride = warp.Color,
                ToolTip = warp.Description,
                TooltipDelay = 0.1f,
                MinSize = new Vector2(150, 0),
                ClipText = false,
                HorizontalExpand = true,
            };

            if (warp.DisplayName.Length > 20)
            {
                playerButton.Label.StyleClasses.Add("FontSizeSmall");
            }

            playerButton.Label.ModulateSelfOverride = GetTextColor(warp.Color);
            playerButton.OnPressed += _ => WarpClicked?.Invoke(warp.Entity);

            return playerButton;
        }

        private Control CreateSectionHeader(string text, bool useStripeBack = true)
        {
            var label = new Label
            {
                Text = Loc.GetString(text),
                StyleClasses = { "LabelBig" },
                Align = Label.AlignMode.Center,
            };

            if (!useStripeBack)
                return label;

            var stripe = new StripeBack()
            {
                HorizontalExpand = true
            };
            stripe.AddChild(label);

            return stripe;
        }

        public static Color GetTextColor(Color? background)
        {
            if (background is null)
                return Color.White;

            var luminance = (0.299 * background.Value.R +
                0.587 * background.Value.G +
                0.114 * background.Value.B);

            return luminance > 0.5 ? Color.Black : Color.White;
        }
        // ADT-TWEAK END
    }
}
