using Content.Client.Corvax.Sponsors;
using Content.Shared.ADT.SlimeHair;
using Content.Shared.Corvax.TTS;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client.ADT.SlimeHair;

[GenerateTypedNameReferences]
public sealed partial class SlimeHairWindow : DefaultWindow
{
    public Action<(int slot, string id)>? OnHairSelected;
    public Action<(int slot, Marking marking)>? OnHairColorChanged;
    public Action<int>? OnHairSlotRemoved;
    public Action? OnHairSlotAdded;

    public Action<(int slot, string id)>? OnFacialHairSelected;
    public Action<(int slot, Marking marking)>? OnFacialHairColorChanged;
    public Action<int>? OnFacialHairSlotRemoved;
    public Action? OnFacialHairSlotAdded;

    public Action<string>? OnVoiceChanged;

    private readonly IPrototypeManager _prototypeManager = IoCManager.Resolve<IPrototypeManager>();
    private readonly SponsorsManager _sponsorsManager = IoCManager.Resolve<SponsorsManager>();

    private List<TTSVoicePrototype> _voiceList = new();

    public SlimeHairWindow()
    {
        RobustXamlLoader.Load(this);

        HairPicker.OnMarkingSelect += args => OnHairSelected!(args);
        HairPicker.OnColorChanged += args => OnHairColorChanged!(args);
        HairPicker.OnSlotRemove += args => OnHairSlotRemoved!(args);
        HairPicker.OnSlotAdd += delegate { OnHairSlotAdded!(); };

        FacialHairPicker.OnMarkingSelect += args => OnFacialHairSelected!(args);
        FacialHairPicker.OnColorChanged += args => OnFacialHairColorChanged!(args);
        FacialHairPicker.OnSlotRemove += args => OnFacialHairSlotRemoved!(args);
        FacialHairPicker.OnSlotAdd += delegate { OnFacialHairSlotAdded!(); };

        VoiceButton.OnItemSelected += args =>
        {
            VoiceButton.SelectId(args.Id);
            OnVoiceChanged?.Invoke(_voiceList[args.Id].ID);
        };

        _voiceList = _prototypeManager
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(o => o.RoundStart)
            .OrderBy(o => Loc.GetString(o.Name))
            .ToList();
    }

    public void UpdateState(SlimeHairUiState state)
    {
        HairPicker.UpdateData(state.Hair, state.Species, state.HairSlotTotal);
        FacialHairPicker.UpdateData(state.FacialHair, state.Species, state.FacialHairSlotTotal);

        UpdateVoice(state.Sex, state.Voice);

        if (!HairPicker.Visible && !FacialHairPicker.Visible)
        {
            AddChild(new Label { Text = Loc.GetString("magic-mirror-component-activate-user-has-no-hair") });
        }
    }

    private void UpdateVoice(Sex sex, string currentVoice)
    {
        VoiceButton.Clear();

        var firstVoiceChoiceId = 1;
        for (var i = 0; i < _voiceList.Count; i++)
        {
            var voice = _voiceList[i];
            if (!HumanoidCharacterProfile.CanHaveVoice(voice, sex))
                continue;

            var name = Loc.GetString(voice.Name);
            VoiceButton.AddItem(name, i);

            if (firstVoiceChoiceId == 1)
                firstVoiceChoiceId = i;

            if (voice.SponsorOnly &&
                _sponsorsManager.TryGetInfo(out var sponsor) &&
                !sponsor.AllowedMarkings.Contains(voice.ID))
            {
                VoiceButton.SetItemDisabled(VoiceButton.GetIdx(i), true);
            }
        }

        var voiceChoiceId = _voiceList.FindIndex(x => x.ID == currentVoice);
        if (!VoiceButton.TrySelectId(voiceChoiceId) &&
            VoiceButton.TrySelectId(firstVoiceChoiceId))
        {
            OnVoiceChanged?.Invoke(_voiceList[firstVoiceChoiceId].ID);
        }
    }
}
