using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.SeedDna;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using System.Linq;

namespace Content.Client.ADT.SeedDna.UI;

[GenerateTypedNameReferences]
public sealed partial class SeedDnaConsoleWindow : FancyWindow
{
    private readonly List<SeedDnaConsoleWindowRow> _allRows = [];

    private bool _seedIsPresent;
    private bool _dnaDiskIsPresent;

    public event Action<string, SeedDnaTransferDirection, bool>? OnGeneTransfer;

    public SeedDnaConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ExtractAllButton.OnPressed += _ =>
        {
            DisableAllButtons();
            OnGeneTransfer?.Invoke(string.Empty, SeedDnaTransferDirection.SeedToDisk, true);
        };

        ReplaceAllButton.OnPressed += _ =>
        {
            DisableAllButtons();
            OnGeneTransfer?.Invoke(string.Empty, SeedDnaTransferDirection.DiskToSeed, true);
        };
    }

    /// <summary>
    /// Выполняется всегда при открытии или обновлении состояния UI.
    /// </summary>
    public void UpdateState(SeedDnaConsoleBoundUserInterfaceState state)
    {
        UpdateEjectButtons(state);

        if (!ValidateSeed(state))
            return;

        CleanRows();
        FillRows(state);
        UpdateButtonsAll(state);
        UpdateSellPanel(state);

        PointsLabel.Text = Loc.GetString("seed-dna-points", ("points", state.Points), ("max", state.MaxPoints));
        PointsLabel.ToolTip = Loc.GetString("seed-dna-points-tooltip");
        SellButton.ToolTip = Loc.GetString("seed-dna-sell-tooltip");
    }

    private void UpdateEjectButtons(SeedDnaConsoleBoundUserInterfaceState state)
    {
        _seedIsPresent = state.IsSeedsPresent;
        _dnaDiskIsPresent = state.IsDnaDiskPresent;

        SeedButton.Text = state.IsSeedsPresent
            ? Loc.GetString("seed-dna-eject-btn")
            : Loc.GetString("seed-dna-insert-btn");
        SeedLabel.Text = state.SeedsName;

        DnaDiskButton.Text = state.IsDnaDiskPresent
            ? Loc.GetString("seed-dna-eject-btn")
            : Loc.GetString("seed-dna-insert-btn");
        DnaDiskLabel.Text = state.DnaDiskName;
    }

    /// <summary>
    /// Проверка возможности использования семян
    /// </summary>
    private bool ValidateSeed(SeedDnaConsoleBoundUserInterfaceState state)
    {
        if (state is { IsSeedsPresent: true } && state.Genes.All(entry => entry.SeedValue == null))
        {
            InvalidSeedLabel.Visible = true;
            MutationContainer.Visible = false;
            return false;
        }

        InvalidSeedLabel.Visible = false;
        MutationContainer.Visible = true;
        return true;
    }

    private void CleanRows()
    {
        MutationContainer.Children.Clear();
        ExtractAllButton.Disabled = true;
        ReplaceAllButton.Disabled = true;

        _allRows.Clear();
    }

    private void FillRows(SeedDnaConsoleBoundUserInterfaceState state)
    {
        foreach (var entry in state.Genes)
        {
            var row = new SeedDnaConsoleWindowRow(entry, OnGeneTransferPressed);
            MutationContainer.AddChild(row);
            _allRows.Add(row);
        }
    }

    private void OnGeneTransferPressed(string geneId, SeedDnaTransferDirection direction, bool all)
    {
        if (all)
            return;

        foreach (var row in _allRows)
        {
            if (row.GeneId == geneId)
            {
                row.DisableButtons();
                break;
            }
        }

        OnGeneTransfer?.Invoke(geneId, direction, false);
    }

    private void UpdateButtonsAll(SeedDnaConsoleBoundUserInterfaceState state)
    {
        if (!_seedIsPresent || !_dnaDiskIsPresent)
            return;

        if (_allRows.Any(row => row.CanExtract))
            ExtractAllButton.Disabled = false;

        if (_allRows.Any(row => row.CanReplace))
            ReplaceAllButton.Disabled = false;
    }

    private void UpdateSellPanel(SeedDnaConsoleBoundUserInterfaceState state)
    {
        if (state.IsSeedsPresent && !state.SeedModified)
        {
            SellPriceLabel.Text = Loc.GetString("seed-dna-sell-not-modified");
            SellButton.Disabled = true;
            return;
        }

        SellPriceLabel.Text = Loc.GetString("seed-dna-sell-price", ("price", state.SellPrice));
        SellButton.Disabled = !state.CanSell;
    }

    private void DisableAllButtons()
    {
        ExtractAllButton.Disabled = true;
        ReplaceAllButton.Disabled = true;

        foreach (var row in _allRows)
        {
            row.DisableButtons();
        }
    }
}
