using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.SeedDna;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.SeedDna.UI;

[GenerateTypedNameReferences]
public sealed partial class SeedDnaConsoleWindow : FancyWindow
{
    private readonly List<SeedDnaConsoleWindowRow> _allRows = [];

    public event Action<string, SeedDnaTransferDirection>? OnGeneTransfer;

    public SeedDnaConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    /// <summary>
    /// Выполняется всегда при открытии или обновлении состояния UI.
    /// </summary>
    public void UpdateState(SeedDnaConsoleBoundUserInterfaceState state)
    {
        UpdateEjectButtons(state);
        UpdateSellPanel(state);

        PointsLabel.Text = Loc.GetString("seed-dna-points", ("points", state.Points), ("max", state.MaxPoints));
        PointsLabel.ToolTip = Loc.GetString("seed-dna-points-tooltip");
        SellButton.ToolTip = Loc.GetString("seed-dna-sell-tooltip");

        if (!ValidateSeed(state))
            return;

        CleanRows();
        FillRows(state);
    }

    private void UpdateEjectButtons(SeedDnaConsoleBoundUserInterfaceState state)
    {
        SeedButton.Text = state.IsSeedsPresent
            ? Loc.GetString("seed-dna-eject-btn")
            : Loc.GetString("seed-dna-insert-btn");
        SeedLabel.Text = state.SeedsName;

        DnaDiskButton.Text = state.IsDnaDiskPresent
            ? Loc.GetString("seed-dna-eject-btn")
            : Loc.GetString("seed-dna-insert-btn");
        DnaDiskLabel.Text = state.DnaDiskName;
    }

    /// <summary>
    /// Проверка возможности использования семян
    /// </summary>
    private bool ValidateSeed(SeedDnaConsoleBoundUserInterfaceState state)
    {
        if (state is { IsSeedsPresent: true } && state.Genes.All(entry => entry.SeedValue == null))
        {
            InvalidSeedLabel.Visible = true;
            MutationContainer.Visible = false;
            return false;
        }

        InvalidSeedLabel.Visible = false;
        MutationContainer.Visible = true;
        return true;
    }

    private void CleanRows()
    {
        MutationContainer.Children.Clear();
        _allRows.Clear();
    }

    private void FillRows(SeedDnaConsoleBoundUserInterfaceState state)
    {
        foreach (var entry in state.Genes)
        {
            var row = new SeedDnaConsoleWindowRow(entry, OnGeneTransferPressed);
            MutationContainer.AddChild(row);
            _allRows.Add(row);
        }
    }

    private void OnGeneTransferPressed(string geneId, SeedDnaTransferDirection direction)
    {
        foreach (var row in _allRows)
        {
            if (row.GeneId == geneId)
            {
                row.DisableButtons();
                break;
            }
        }

        OnGeneTransfer?.Invoke(geneId, direction);
    }

    private void UpdateSellPanel(SeedDnaConsoleBoundUserInterfaceState state)
    {
        if (state.IsSeedsPresent && !state.SeedModified)
        {
            SellPriceLabel.Text = Loc.GetString("seed-dna-sell-not-modified");
            SellButton.Disabled = true;
            return;
        }

        SellPriceLabel.Text = Loc.GetString("seed-dna-sell-price", ("price", state.SellPrice));
        SellButton.Disabled = !state.CanSell;
    }
}