- type: loadout
  id: HeadofSecurityMantleShoulder
  equipment:
    neck: ClothingNeckMantleHOSShoulder
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS


- type: loadout
  id: HoSPDA
  equipment:
    id: HoSPDA

- type: loadout
  id: ADTSheriffPDA
  equipment:
    id: ADTSheriffPDA
