using Content.Shared.ADT.Sponsors;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.Sponsors.UI;

[GenerateTypedNameReferences]
public sealed partial class SponsorColorsWindow : DefaultWindow
{
    private readonly SponsorManager _sponsors;

    private bool _refreshing;

    private Color? _pendingOoc;
    private Color? _pendingGhost;

    private bool _dirty;
    private int _inFlight;

    public SponsorColorsWindow(SponsorManager sponsors)
    {
        RobustXamlLoader.Load(this);

        _sponsors = sponsors;

        OocSelector.OnColorChanged += color =>
        {
            if (_refreshing)
                return;

            _pendingOoc = color;
            MarkDirty();
        };

        GhostSelector.OnColorChanged += color =>
        {
            if (_refreshing)
                return;

            _pendingGhost = color;
            MarkDirty();
        };

        OocResetButton.OnPressed += _ =>
        {
            _pendingOoc = null;
            MarkDirty();
            RenderColors();
        };

        GhostResetButton.OnPressed += _ =>
        {
            _pendingGhost = null;
            MarkDirty();
            RenderColors();
        };

        ApplyButton.OnPressed += _ => Apply();

        _sponsors.Updated += Refresh;
        Refresh();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            _sponsors.Updated -= Refresh;
    }

    private void MarkDirty()
    {
        _dirty = true;
        UpdateApplyState();
    }

    private void UpdateApplyState()
    {
        ApplyButton.Disabled = !_dirty;
        DirtyLabel.Visible = _dirty;
    }

    private void Apply()
    {
        if (!_dirty)
            return;

        _dirty = false;
        _inFlight++;

        _sponsors.RequestColors(_pendingOoc, _pendingGhost);
        UpdateApplyState();
    }

    private void Refresh()
    {
        if (_inFlight > 0)
            _inFlight--;

        if (_inFlight == 0 && !_dirty)
        {
            _pendingOoc = _sponsors.Colors.Ooc;
            _pendingGhost = _sponsors.Colors.Ghost;
        }

        var data = _sponsors.Data;

        OocSection.Visible = data.AllowCustomOocColor;

        var hasPresets = data.GhostColors.Count > 0;
        GhostSection.Visible = data.AllowCustomGhostColor || hasPresets;
        GhostSelector.Visible = data.AllowCustomGhostColor;

        var anySection = OocSection.Visible || GhostSection.Visible;
        HintLabel.Visible = !anySection;
        ApplyDivider.Visible = anySection;
        ApplySection.Visible = anySection;

        BuildGhostPresets(data);
        RenderColors();
    }

    private void RenderColors()
    {
        _refreshing = true;

        try
        {
            OocSelector.Color = _pendingOoc ?? _sponsors.Data.OocColor ?? Color.White;
            GhostSelector.Color = _pendingGhost ?? Color.White;
        }
        finally
        {
            _refreshing = false;
        }

        UpdateApplyState();
    }

    private void BuildGhostPresets(SponsorData data)
    {
        GhostPresets.RemoveAllChildren();

        if (data.AllowCustomGhostColor)
            return;

        foreach (var color in data.GhostColors)
        {
            var button = new Button
            {
                Text = "  ",
                ModulateSelfOverride = color,
                MinWidth = 32,
            };

            var picked = color;

            button.OnPressed += _ =>
            {
                _pendingGhost = picked;
                MarkDirty();
            };

            GhostPresets.AddChild(button);
        }
    }
}
