name: "Labels: PR"

# ADT-Tweak-start
on:
  workflow_dispatch:
#on:
#- pull_request_target
# ADT-Tweak-end

jobs:
  labeler:
    if: github.actor != 'IanComradeBot'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:                # ADT Tweak by Schrodinger
        sync-labels: true  # Поправил auto-labels
