name: Publish SD

on:
  workflow_dispatch:
  # schedule:
  # - cron: '0 6 * * *'

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml
    - uses: actions/checkout@v4.2.2
      with:
        submodules: 'recursive'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 9.0.x

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform linux-x64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    #- name: Update Build Info
    #  run: |
    #    chmod +x Tools/gen_build_info.py
    #    Tools/gen_build_info.py

    # - name: Install rsync
    #   run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Transfer binary
      env:
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_PATH: ${{ secrets.SSH_PATH }}
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -P $SSH_PORT release/SS14.Server_linux-x64.zip release/SS14.Client.zip $SSH_PATH
    #   rsync -av -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p $SSH_PORT" release/SS14.Server_linux-x64.zip $SSH_PATH
