name: Publish SD

on:
  workflow_dispatch:
  # schedule:
  # - cron: '0 6 * * *'

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml

    - uses: actions/checkout@v4.2.2
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 9.0.x

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform linux-x64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Update Build Info
      run: |
        chmod +x Tools/gen_build_info.py
        Tools/gen_build_info.py

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync
    
    - name: Upload to server via rsync
      run: rsync -av -e "ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" release/SS14.Server_linux-x64.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}
      
      
     #- name: Shuffle files around
     # run: |
     #  mkdir "release/${{ github.sha }}"
     #  mv release/*.zip "release/${{ github.sha }}"

    
